### ISSUE TITLE
Program crashes computer when refreshing sensors

### ISSUE THREAD

**Issue by gavishhh** [Rem0o/FanControl.Releases#1015]
Whenever I refresh the sensors to get the app started, my computer crashes. If I uncheck a few, it says that an error has been recorded to the error log. Please see error log below:

**Is there a log.txt file next to FanControl.exe with recent date entries?**

8/14/2022 10:06:36 PM: Unhandled exception in FanControl v1.0.0.0
8/14/2022 10:06:36 PM: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at FanControl.MVVM.AsyncCommand.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
8/14/2022 10:06:42 PM: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 3493.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationState.ApplicationStateHasChanged(Boolean& isNew)
8/14/2022 10:07:07 PM: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 3493.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationState.ApplicationStateHasChanged(Boolean& isNew)
8/14/2022 10:33:24 PM: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at FanControl.Domain.ApplicationState.ApplicationPartialStateHasChanged(String key, Boolean& isNew)
   at FanControl.ViewModels.SensorSettingsViewModel.<OpenSensorSettingsDialog>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.AssistedSetup.<RunSensorSettings>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.AssistedSetup.<Run>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<MainWindow_Loaded>d__20.MoveNext()
8/14/2022 10:33:34 PM: Unhandled exception in FanControl v1.0.0.0
8/14/2022 10:33:34 PM: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at FanControl.MVVM.AsyncCommand.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
8/14/2022 10:33:49 PM: Unhandled exception in FanControl v1.0.0.0
8/14/2022 10:33:49 PM: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at FanControl.MVVM.AsyncCommand.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
8/14/2022 10:35:28 PM: Unhandled exception in FanControl v1.0.0.0
8/14/2022 10:35:28 PM: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at FanControl.MVVM.AsyncCommand.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Relevant hardware specs and setup**
Gigabyte H170N wifi motherboard
i7-7700k CPU

Thanks!

**Comment by Rem0o** [comment]
Seems like something is wrong with your json file while deserialization occurs. Try and delete your CACHE file and start fresh, see if it still occurs.

**Comment by gavishhh** [comment]
I tried that and it still crashed again. Any thoughts?

**Comment by Rem0o** [comment]
Delete every json file in your FanControl folder.

**Comment by gavishhh** [comment]
I tried that and the application wouldn't load. I deleted the folder and
unzipped it from the download to start fresh and when I got up to the part
about checking the sensors, the computer crashed again.

**Comment by SoraKagami** [comment]
@gavishhh What version of FanControl are you running, and what version of .NET do you have installed?
Also as a just in case, is your window's language set to English or another language?

In the meantime I would suggest trying the following:
1. Making sure your .NET is up to date, or at least compatible with FanControl
2. Trying a different version of FanControl
3. If the primary display language isn't set to English, try switching to English and see if the error goes away.

Good luck!

**Comment by gavishhh** [comment]
Thanks for your reply. Everything is up to date. If you'd like to send me
the exe's for net and fan control, I can reinstall them both.

Aside question, I'm planning on switching to a supermicro x12 or x13
motherboards. Is your software compatible with these boards?

**Comment by gavishhh** [comment]
Good morning, I wanted to follow up and see if you had any updates on this,
please? Thank you!

**Comment by Rem0o** [comment]
It ain't really a matter of the board itself, more the controller chip it uses.  Most of the time this information is not really featured/marketed, and as such you need to look directly at the board.

List of chips supported: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Chip.cs

**Comment by gavishhh** [comment]
Thanks. How would I see if the Supermicro X12SCA-5F is supported based on
this list?

**Comment by Rem0o** [comment]
@gavishhh  you got as fair as a shot as I do to spot the superio chip it uses. Did a quick google search, couldn't find the info online, and there is no high-res picture I could find to try and spot it on the board directly.

**Comment by gavishhh** [comment]
Thanks. I emailed Supermicro, let's see what they have to say.

**Comment by gavishhh** [comment]
I found a high res pic of the motherboard here. Where do I look to see what
controller it has?
https://www.tweaktown.com/image.php?image=https://static.tweaktown.com/content/9/9/9938_07_intel-xeon-1390p-and-supermicro-x12-motherboard-review_full.jpg
<https://mailtrack.io/trace/link/8f1e91c72d5056a84e44483c1e216f08456338b3?url=https%3A%2F%2Fwww.tweaktown.com%2Fimage.php%3Fimage%3Dhttps%3A%2F%2Fstatic.tweaktown.com%2Fcontent%2F9%2F9%2F9938_07_intel-xeon-1390p-and-supermicro-x12-motherboard-review_full.jpg&userId=1344614&signature=e02e9d701612b551>

**Comment by Rem0o** [comment]
It's most likely something like this chip : 
![image](https://user-images.githubusercontent.com/14118956/187732984-5ef776b0-7b89-4a01-90da-930625f4ed93.png)

But we can't read what written on it, too blurry.

**Comment by Rem0o** [comment]
Nevermind, found it: 
![Screenshot 2022-08-31 125956](https://user-images.githubusercontent.com/14118956/187737118-a695b073-6709-4a64-b932-d42d51cc868f.png)

It's a nuvoton chip.

**Comment by gavishhh** [comment]
Awesome! Does that mean it's supported?

**Comment by Rem0o** [comment]
@gavishhh  Without knowing the exact model, again, can't tell.

These are the supported chips: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/c7ff2efd91bc582742e703461267443d9ba5a901/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/Chip.cs

**Comment by gavishhh** [comment]
Thanks! I tried it on a different motherboard and the program seems to
work! The one issue that I'm having is I'm trying to control fan speeds
based on HDD temps. The HDD temps are not showing up as a source option in
your app. What could be causing this? Thanks!

**Comment by Rem0o** [comment]
You got to make sure the storage checkbox is enabled in sensor settings.

**Comment by gavishhh** [comment]
Still not showing up. They're attached to an LSI HBA card. Any thoughts?
Thanks!

**Comment by Rem0o** [comment]
> They're attached to an LSI HBA card. Any thoughts?

Bingo. That's not supported.

**Comment by gavishhh** [comment]
Damn, damn, damn. Any thoughts on a workaround? Any plans to support in the
future?

**Comment by gavishhh** [comment]
I would be happy to donate to have that feature added in. Is that something
you would be amenable to?
