### ISSUE TITLE
LibreHardwareMonitor could not initialize

### ISSUE THREAD

**Issue by fmohican** [Rem0o/FanControl.Releases#1016]
**Describe the bug**

[screeenshot](https://img.aniro.me/images/2022/08/16/f7aa445a1b85d842ea88ba6b279d8e99.png)

**Is there a log.txt file next to FanControl.exe with recent date entries?**

```
16/08/2022 00:43:38: System.Management.ManagementException: Invalid namespace 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
16/08/2022 00:43:38: LibreHardwareMonitor could not initialize or has no sensors. See the error log for more details.
```
**Relevant hardware specs and setup**

MSI B550 Tomahawk with 4 fans PWN
Ryzen 9 3950x cooled by Nocuta ND15 (PWN)
RTX 3080 Triple Fan, but just two are reconised.

**Comment by Rem0o** [comment]
Deactivate storage sensors.

**Comment by fmohican** [comment]
flawless. thanks.
