### ISSUE TITLE
Version 122 breaks compatibility with previous setup

### ISSUE THREAD

**Issue by scchow** [Rem0o/FanControl.Releases#1019]
**Describe the bug**

I updated to version 122 via the popup prompt. When it restarted, I got an "Could not load the configuration" error (see screenshot). 

Then, when I tried to close fan control, it tried to prompt me to save or discard changes because somehow the configuration had changed. I selected "Discard" and received the same "Could not load the configuration error" as above and dumped me back to the main screen. 

I could not close fancontrol normally and had to use the Task Manager to kill the process. 

I reverted back to version 121, cleared the log file, and repeated the process to verify the bug. The resulting error that was recorded in `log.txt` is copy/pasted below.

For now, I have reverted back to version 121, and everything seems to work as before.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
```
8/17/2022 7:02:06 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MixSensorViewModel.<>c__DisplayClass32_0.<set_SelectedSensors>b__0(ISensorSourceViewModel s)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at FanControl.ViewModels.MixSensorViewModel.set_SelectedSensors(IEnumerable`1 value)
   at FanControl.ViewModels.MixSensorViewModel.Deserialize(IMixSensorConfig mixSensor, ObservableCollection`1 tempSensors, IDialogService dialogService, ApplicationClock applicationClock, Func`2 validateCustomSensorNameAndNotify, Action`1 delete)
   at FanControl.App.<>c__DisplayClass24_0.<RegisterTypes>b__16(MainWindowViewModel c, SerializableMixSensor ms)
   at FanControl.ViewModels.CustomSensorProvider`1.<Deserialize>d__4.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state)
```

**Relevant hardware specs and setup**

RTX 3080, 5600x

Here is a pastebin of the [config JSON](https://pastebin.com/vqTUS3xb) that currently works with v121 if that helps with debugging.

**Screenshots**

![image](https://user-images.githubusercontent.com/11098209/185275939-d80b54c3-3c68-43bc-b119-d1d957cc90e7.png)

**Comment by Dark4Codrutz** [comment]
same issue here
my log is a bit different:
`18/08/2022 08:42:06: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.Domain.CustomSensors.MixSensor.Update()
   at FanControl.ViewModels.MixSensorViewModel.GetUpdatedValue()
   at FanControl.ViewModels.CustomSensorViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`
[Standard - Rework - Copy.json.txt](https://github.com/Rem0o/FanControl.Releases/files/9368255/Standard.-.Rework.-.Copy.json.txt)

**Comment by Rem0o** [comment]
Reuploaded the version.   Run Updater.exe again.

**Comment by scchow** [comment]
Was able to successfully update this time. Thanks for the prompt update!
