### ISSUE TITLE
V122: NullReferenceException thrown: When sensor missing in "Mix Sensor" 

### ISSUE THREAD

**Issue by mdac3564444** [Rem0o/FanControl.Releases#1020]
DESCRIPTION:
Added "Mix" custom sensor with removable hard drive in it. When hard drive is removed program can't load. Error message displayed "Could not load the configuration. An Unexpected error has occurred". Log file details "object not set to an instance of an object".

ERROR LOG:
8/18/2022 10:29:09 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MixSensorViewModel.<>c__DisplayClass32_0.<set_SelectedSensors>b__0(ISensorSourceViewModel s)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at FanControl.ViewModels.MixSensorViewModel.set_SelectedSensors(IEnumerable`1 value)
   at FanControl.ViewModels.MixSensorViewModel.Deserialize(IMixSensorConfig mixSensor, ObservableCollection`1 tempSensors, IDialogService dialogService, ApplicationClock applicationClock, Func`2 validateCustomSensorNameAndNotify, Action`1 delete)
   at FanControl.App.<>c__DisplayClass24_0.<RegisterTypes>b__16(MainWindowViewModel c, SerializableMixSensor ms)
   at FanControl.ViewModels.CustomSensorProvider`1.<Deserialize>d__4.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state)

SETUP:
Windows 10 21H2 build 19044.1288
AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz, 32gb ram.
Asus Tuf Gaming WIFI Pro motherboard (version 1)

**Comment by Rem0o** [comment]
Rerun updater.exe

**Comment by Rem0o** [comment]
See V123.

**Comment by Rem0o** [comment]
Dup. of https://github.com/Rem0o/FanControl.Releases/issues/1023
