### ISSUE TITLE
Fans don't step up

### ISSUE THREAD

**Issue by jamesyera** [Rem0o/FanControl.Releases#1030]
**Describe the bug**
I have spent awhile trying to narrow the issue to something as specific as I can. When my fan adjusts speed associated with a normal curve, they follow their stepup percentages, but occasionally (often at peak of curve) it will not step up a final time and will signal overriden by external source. Potentially it's not updating quickly enough somewhere along the way from the sensor reading to applying the curve and doesn't register the most recent update? As I've been able to observe, the curve will report the proper speed but the fan controller will not apply said percentage, remaining one step down from reported by associated curve.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
Msi Z690 proa ddr4 (mobo settings chassis fans all 50% flat)
noctua fans all pwm a12x25's, nf 12, and s12a's, all direct to mobo headers w y cables where necessary.
12th gen i7

**Comment by jamesyera** [comment]
6/29/2022 15:45:24: Unhandled exception in FanControl v1.0.0.0
6/29/2022 15:45:24: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR
   at FanControl.Models.NVApiControlSensor.HandleException(NVIDIAApiException exception)
   at FanControl.Models.NVApiControlSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
7/4/2022 2:51:39: LibreHardwareMonitor could not initialize or has no sensors. See the error log for more details.
7/4/2022 2:51:39: An exception occured with this dialog view: MessageDialog
7/4/2022 2:51:39: System.InvalidOperationException: DialogHost is already open.
   at MaterialDesignThemes.Wpf.DialogHost.<ShowInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaterialDesignThemes.Wpf.DialogHost.<Show>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass9_0`1.<<ShowDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<ShowDialog>d__9`1.MoveNext()
7/4/2022 2:53:00: LibreHardwareMonitor could not initialize or has no sensors. See the error log for more details.
8/16/2022 9:51:28: Unhandled exception in FanControl v1.0.0.0
8/16/2022 9:51:28: System.InvalidOperationException: Dialog session has ended.
   at MaterialDesignThemes.Wpf.DialogSession.Close(Object parameter)
   at FanControl.Domain.DialogService.<>c__DisplayClass13_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

snippet from log file if relevant

**Comment by Rem0o** [comment]
Screenshot when that's happening with your control card expanded + fan curve visible.

**Comment by jamesyera** [comment]
![image](https://user-images.githubusercontent.com/111711364/185971012-43ddc654-a0e2-4e2f-96e7-61fac8fbed02.png)

Here is an instance I was able to capture. This behavior in the screenshot is when the fans are stepping down. The behavior is the same just my fan curve would read 75% but fans will sometimes read 71% and get 'stuck' if you will. According to curves, the first four should all be 30%, however the 3rd and 4th from the left are one step up and holding (while being 'overridden'), despite the curves reading solid 30% the whole time.

Hope this is helpful!

**Comment by Rem0o** [comment]
Does this still occurs with V125?

**Comment by jamesyera** [comment]
Updated and seems to be fixed now, thanks!
