### ISSUE TITLE
Broken Latest Release 123

### ISSUE THREAD

**Issue by IronBeardKnight** [Rem0o/FanControl.Releases#1031]
It appears you have broken the application as fan and pump control on both manual settings and auto/personal map no longer respond to temp changes.

When triggering a find censor feature it does spin up the pump and fans for a moment while detecting but then nothing.

**Comment by IronBeardKnight** [comment]
Nothing in the error log specific  either only errors about my corsair psu.

3/06/2022 2:42:43 PM: LibreHardwareMonitor.Hardware.Psu.Corsair.CommunicationProtocolError: Error communicating with the PSU controller at \\?\hid#vid_1b1c&pid_1c08#7&39377f5c&0&0000#{xxxxx-xxx-xxxx-xxx-xxxxxx}: Can't read vendor string
   at LibreHardwareMonitor.Hardware.Psu.Corsair.UsbApi.FwInfo(HidStream stream)
   at LibreHardwareMonitor.Hardware.Psu.Corsair.CorsairPsu..ctor(HidDevice device, ISettings settings, Int32 index)
   at LibreHardwareMonitor.Hardware.Psu.Corsair.CorsairPsuGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()

**Comment by ZilgornZeypher** [comment]
I also noticed that just today when my temps on my loop where high. (It's been hot here lately so didn't notice that the temps were higher than they should have been). All of my fan's minus the ones plugged into the CPU fan header on my Asus X570 strix e were running though everything was running at low rpms.
