### ISSUE TITLE
V123 makes previous configurations unuseable.

### ISSUE THREAD

**Issue by lvent** [Rem0o/FanControl.Releases#1032]
V122 works fine, however the moment I upgrade to V123 my configuration no longer works.

`
22/08/2022 09:20:03: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.TimeAverageSensorViewModel.Deserialize(ITimeAverageSensorConfig timeAverageSensor, ObservableCollection`1 tempSensors, IDialogService dialogService, IApplicationClock applicationClock, Func`2 validateCustomSensorNameAndNotify, Action`1 deleteCustomSensor)
   at FanControl.App.<>c__DisplayClass24_0.<RegisterTypes>b__18(MainWindowViewModel c, SerializableTimeAverageSensor ms)
   at FanControl.ViewModels.CustomSensorProvider`1.<Deserialize>d__4.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state)`

[Config.zip](https://github.com/Rem0o/FanControl.Releases/files/9391726/Config.zip)

**Comment by Madudzik** [comment]
Same here pal, every time my pc boots I need to manually load my previous profile...:-(

**Comment by Rem0o** [comment]
Spotted the issue. 

In the mean time, you can edit your config file manually and remove the time average sensor with no temperature source.

**Comment by lvent** [comment]
V124 resolved this issue.
