### ISSUE TITLE
Unable to detect any fans on asus on latest version

### ISSUE THREAD

**Issue by Dariusz1989** [Rem0o/FanControl.Releases#1210]
I cant discover anything. I have asus plugin, but even with/without nothing runs.

Any ideas?

Some logs : 

26/10/2022 21:05:42: Unhandled exception in FanControl v1.0.0.0
26/10/2022 21:05:42: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.AsusWMI.AsusWMIPlugin.Close()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Close() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\ComputerAccessLayer.cs:line 229
   at FanControl.Domain.ComputerAccessLayer.Refresh() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\ComputerAccessLayer.cs:line 40
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()Q
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Commands.SaveAndRefreshCommand.<<Execute>b__5_0>d.MoveNext() in C:\Users\Remi\source\repos\FanControl\FanControl.App\ViewModels\Commands\SaveAndRefreshCommand.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass13_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

LibreHardwareMonitor Report

--------------------------------------------------------------------------------

Version: 0.9.1.0

--------------------------------------------------------------------------------

Common Language Runtime: 4.0.30319.42000
Operating System: Microsoft Windows NT 6.2.9200.0
Process Type: 64-Bit

--------------------------------------------------------------------------------

+- ASUS ProArt X670E-CREATOR WIFI (/motherboard)

**Comment by Rem0o** [comment]
The error occurs in the AsusWMIPlugin.

Please open the issue in the appropriate repo.
https://github.com/Mourdraug/FanControl.AsusWMI
