### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by TheOneTrueSpLiT** [Rem0o/FanControl.Releases#1238]
I have been using FanControl for many months and run it on login, but all of a sudden it won't run at...

Yesterday it was working fine and I had restarted the PC a number of times and it opened automatically as expected.

But today it did not start automatically and on trying to start it manually I immediately got an error message stating:

"An unexpected error occurred.  See log file for details."

At first I thought it was an issue with it accessing 'raw.githubusercontent.com' as indicated in the log but on further inspection of the log file it seems that happens all the time.

I am sure it updated to the latest version sometime yesterday (I can't remember as I've had 5 strokes!) but it worked fine after updating, using PE Explorer on the updated FanControl.exe shows the Modified date as Sunday 30 October 2022, 15.18.41.

I tried copying the whole FanControl folder to my desktop and running it from there, but I got the exact same error message.  I also tried running an older "backup" version from my OneDrive timestamped Thursday 06 October 2022, 17.50.29 but this too failed to launch, again with the exact same error message.

I've been a software engineer since 1987 and am completely flummoxed by this sudden error.

System is Windows 10 Pro 64Bit, CPU Ryzen 9 3900X, GPU RTX3060, 16GB RAM, MSI B550M PRO-VDH WIFI mobo.

Log is as follows:

22/09/2022 20:43:53: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__17.MoveNext()
22/09/2022 20:43:53: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
22/09/2022 22:35:30: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__17.MoveNext()
22/09/2022 22:35:30: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
28/09/2022 14:27:22: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__17.MoveNext()
28/09/2022 14:27:22: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
28/09/2022 14:31:28: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__17.MoveNext()
28/09/2022 14:31:28: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
05/10/2022 17:52:41: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__17.MoveNext()
05/10/2022 17:52:41: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
08/10/2022 16:54:56: System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
18/10/2022 20:51:19: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__17.MoveNext()
18/10/2022 20:51:19: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
29/10/2022 19:32:14: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__18.MoveNext()
29/10/2022 19:32:14: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
01/11/2022 13:46:39: Unhandled exception in FanControl v1.0.0.0
01/11/2022 13:46:39: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
01/11/2022 13:47:58: Unhandled exception in FanControl v1.0.0.0
01/11/2022 13:47:58: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
01/11/2022 14:22:19: Unhandled exception in FanControl v1.0.0.0
01/11/2022 14:22:19: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
01/11/2022 22:26:07: Unhandled exception in FanControl v1.0.0.0
01/11/2022 22:26:07: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
01/11/2022 22:26:26: Unhandled exception in FanControl v1.0.0.0
01/11/2022 22:26:26: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Hope this helps.

Regards,
Guy

**Comment by Rem0o** [comment]
Seems like it is being blocked from checking the server for an update.

Any firewall or anything new that might block network access?

**Comment by TheOneTrueSpLiT** [comment]
Hi there. It checked Windows Firewall and even added rules for FanControl to allow access but that didn’t make any difference. I think it is an issue with a driver update I installed just before shutting the PC and FanControl not starting the following morning, I completely forgot about that but that's what 5 strokes will do to your poor old brain! Rolling back the driver didn’t fix it, so I’m contemplating re-installing Win10 as doing that is not really an issue as it’s something I do every 6 months and my Win10 installation is on an SSD with nothing else on that SSD at all so it takes just a few mins to re-install and then 30 mins to setup Win10 as I like it. If there’s any issues after that I’ll e-mail you back but I’m 99.99% sure the problem is my Win10. Regards,Guy Sent from Mail for Windows From: Rem0oSent: 01 November 2022 23:08To: Rem0o/FanControl.ReleasesCc: GUY HALL; AuthorSubject: Re: [Rem0o/FanControl.Releases] An unexpected error occurred (Issue #1238) Seems like it is being blocked from checking the server for an update.Any firewall or anything new that might block network access?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by TheOneTrueSpLiT** [comment]
Hey there, It turned out this error was being generated as FanControl was unable to set any fan speeds due to “Smartfan” being enabled in my MSI B550M BIOS settings. The BIOS fan curve settings must have got set by an update to MSI Dragon Centre around the time FanControl stopped working, I just forgot all about the update. So it’s all working fine again after putting the BIOS settings back to NOT use ANY fan curves AT ALL and removing Dragon Centre completely!!! You may want to see if you can trap this error and put an indication in the Log that FanControl was unable to set a speed due to being “locked out” by the BIOS or any other fan speed app. Sent from Mail for Windows From: Rem0oSent: 01 November 2022 23:08To: Rem0o/FanControl.ReleasesCc: GUY HALL; AuthorSubject: Re: [Rem0o/FanControl.Releases] An unexpected error occurred (Issue #1238) Seems like it is being blocked from checking the server for an update.Any firewall or anything new that might block network access?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by IPinhalves** [comment]
I had the same problem, check the bios and nothing changed, than I saw a video to create a task to open SpeedFan in windows startup, change the name to FanControl and it worked, no the best way, but it worked... 

link to the tutorial

https://www.youtube.com/watch?v=S1CHC2n20Ng
