### ISSUE TITLE
NVidia Api Exception - NVAPI_API_NOT_INITIALIZED

### ISSUE THREAD

**Issue by anthony-langford** [Rem0o/FanControl.Releases#1265]
Attempting to open FanControl from the dock resulted in an exception that was logged to the log file. 

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-11-08 10:42:14 PM: Unhandled exception in FanControl v1.0.0.0
2022-11-08 10:42:14 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_API_NOT_INITIALIZED
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9967140/log.txt)

**Comment by Rem0o** [comment]
What's your GPU situation?

**Comment by anthony-langford** [comment]
It’s a RTX 3080 12GB. Btw this issue resolved after restarting FanControl. But I did notice temps were stuck at gaming levels (~45 degrees C) as were corresponding fan levels until the restart.On Nov 9, 2022, at 9:32 AM, Rem0o ***@***.***> wrote:﻿
What's your GPU situation?

**Comment by Rem0o** [comment]
Yeah, the NvAPI is the interaction layer between fan control and your GPU. It somehow got uninitialized and FanControl couldn't communicate sensor data with your GPU, hence the value freeze.
