### ISSUE TITLE
Fan Control in a running state repeatedly throws an error after a NVidia update. Killing Fan Control or a reboot is required to fix it

### ISSUE THREAD

**Issue by WesselKroos** [Rem0o/FanControl.Releases#1275]
**Describe the bug**
1. Run Fan Control
2. Update the NVidia driver from version 471.11-desktop-win10-64bit-international-whql to 526.86-desktop-win10-win11-64bit-international-dch-whql 
3. The following error is repeatedly thrown every few seconds.
(See the event log for the full history, it continued because I hibernated the Windows PC for the past 4 days. So Fan Control did not relaunch.)
```log
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
11 Nov 2022 00:00:20: Unhandled exception in FanControl v1.0.0.0
11 Nov 2022 00:00:20: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_API_NOT_INITIALIZED
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\NVApiWrapper\NVApiTempSensor.cs:line 47
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\NVApiWrapper\NVApiWrapperBackendProvider.cs:line 122
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\ComputerAccessLayer.cs:line 212
   at FanControl.Domain.ApplicationClock.DoActions() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\ApplicationClock.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
```
4. Open the Task Manager and kill the Fan Control executable
5. The error is resolved

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/9993378/log_1.txt)
t supported.]

**Relevant hardware specs and setup**
Windows 10 (64 bit)
Intel 6700K
NVidia 2070 Super

**Comment by Rem0o** [comment]
@0PandaDEV  probably not exactly the same problem, since the specific case in this issue with the log provided is handled by the software now.  Any logs?

**Comment by 0PandaDEV** [comment]
```
30/01/2024 13:07:29: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
30/01/2024 13:07:29: NvAPI failed. A complete refresh is required.
30/01/2024 13:07:34: Unhandled exception in FanControl v179.0.0.0
30/01/2024 13:07:34: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_API_NOT_INITIALIZED
   at NvAPIWrapper.Native.GPUApi.GetCoolerSettings(PhysicalGPUHandle gpuHandle, CoolerTarget coolerTarget)
   at NvAPIWrapper.GPU.GPUCoolerInformation.get_Coolers()+MoveNext()
   at System.Linq.Enumerable.TryGetElement[TSource](IEnumerable`1 source, Int32 index, TSource& element)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiControlSensor.Set(Single val)
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location ---
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
30/01/2024 13:07:34: Unhandled exception in FanControl v179.0.0.0
30/01/2024 13:07:34: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_API_NOT_INITIALIZED
   at NvAPIWrapper.Native.GPUApi.GetCoolerSettings(PhysicalGPUHandle gpuHandle, CoolerTarget coolerTarget)
   at NvAPIWrapper.GPU.GPUCoolerInformation.get_Coolers()+MoveNext()
   at System.Linq.Enumerable.TryGetElement[TSource](IEnumerable`1 source, Int32 index, TSource& element)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiControlSensor.Set(Single val)
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location ---
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Rem0o** [comment]
Thanks, I will take a look.

**Comment by Bdog11511** [comment]
Hey Team,
I am also having a similar problem with this log coming up all the time.

[V261] 3/4/2026 12:58:48 AM: Update - NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR
   at NvAPIWrapper.GPU.GPUCoolerInformation.get_Coolers()+MoveNext()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiFanSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()

here is the log.

please help, i have three log files full of this.

if you need anything else let me know.

**Comment by Andyden4483** [comment]
This is now happening for me on the latest driver update today. I only opened the logs looking to see why FC was freezing today when the monitor goes to sleep or is turned/off/on - ill log that separately
