### ISSUE TITLE
latest update, error on attempted boot up: "an unexpected error occured. see log for details". this after reinstalling fancontrol/update, several times

### ISSUE THREAD

**Issue by eitaniel** [Rem0o/FanControl.Releases#1303]
this seems to have been an issue for a few people. even as it sounds like it's been resolved, i'm not sure how to resolve my own problem. i open the program, and am immediately met with dialog box with phrasing described in title of this post. the contents of the log file (log.txt), are as below: 

**Is there a log.txt file next to FanControl.exe with recent date entries?**

20/11/2022 21:30:16: System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup.StorageSpaceDiskToPhysicalDiskMapping() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Storage\StorageGroup.cs:line 75
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Storage\StorageGroup.cs:line 22
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 525
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 494
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
20/11/2022 21:30:16: LibreHardwareMonitor could not initialize or has no sensors.
20/11/2022 21:30:16: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.SensorSettingsViewModel.Restore(SerializableStartupSettings state)
   at FanControl.App.OnInitializationFailed(IResult`1 result, SerializableStartupSettings startupSettings)
   at FanControl.App.<OnStartup>d__11.MoveNext()
   
   please help in identifying possible causes. 

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by nathanmayall** [comment]
I had windows defender quarantine my updater.exe, it thought it was Trojan:Script/Wacatac.H!ml

**Comment by Rem0o** [comment]
Seems like the storage sensor code is crashing.  Try and deactivate the storage sensors in the Sensor settings.

@nathanmayall  see https://github.com/Rem0o/FanControl.Releases/issues/1297

**Comment by eitaniel** [comment]
> Seems like the storage sensor code is crashing. Try and deactivate the storage sensors in the Sensor settings.
> 
> @nathanmayall see #1297

tbh i have no knowledge of how to perform what you've suggested. consider me a layman on these matters. 

the app won't open, except for the dialog error box popping up as indicated above. other than that, i'm unsure as to where to locate the 'storage sensors' in 'sensor settings', that you've suggested. please help me with a kind of step by step basic way of solving this issue, if possible. i appreciate you've got a lot on your plate elsewhere. thanks

**Comment by Rem0o** [comment]
Could you show me a screenshot of said error message?

**Comment by eitaniel** [comment]
![rem0o fancontrol error box 20221121](https://user-images.githubusercontent.com/24715620/203071955-4858a6f8-7a82-4577-a6ea-c6eef609eb47.png)

**Comment by Rem0o** [comment]
[userconfig.zip](https://github.com/Rem0o/FanControl.Releases/files/10057061/userconfig.zip)

Oh, you should have gotten a sensor setting window to pop-up, but there is a bug there and it doesn't show up. Will fix that.  in the meantime to get you going, unzip that file next to fancontrol.exe, and fire it up again, should get you further.

**Comment by eitaniel** [comment]
ah yes, i think i know what u mean now. yes, funnily, that sensor settings window has popped up at points yesterday when i first encountered this issue after the auto update initiated and thereafter crashed. i dont quite remember how i got the window to pop up at times. but now, all i get is this error message after double-clicking/booting up 'fan control'. thanks

**Comment by eitaniel** [comment]
> [userconfig.zip](https://github.com/Rem0o/FanControl.Releases/files/10057061/userconfig.zip)
> 
> Oh, you should have gotten a sensor setting window to pop-up, but there is a bug there and it doesn't show up. Will fix that. in the meantime to get you going, unzip that file next to fancontrol.exe, and fire it up again, should get you further.

this has worked to get me in the app. thanks for that. 

just to confirm, this userconfig, will it mean my own configs will remain unrecoverable, and i have to set them up again? just checking. thanks again.

**Comment by Rem0o** [comment]
If you already had config files, you can simply edit them in a text editor, and disable the storage manually in there.
![image](https://user-images.githubusercontent.com/14118956/203076419-9cd268a2-5276-494f-bddc-5b42ebab2836.png)
