### ISSUE TITLE
"LibreHardwareMonitor could not initialize or has no sensors."

### ISSUE THREAD

**Issue by Dajova** [Rem0o/FanControl.Releases#1327]
**Describe the bug**
![image](https://i.imgur.com/uf26Tga.png)

This has been a thing ever since the last update, was fine before that. It can **ONLY** find the GPU now, not any other metric.
And this error pops up everytime i either start up the program or waking up the PC from sleep.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
```
28/11/2022 12:46:33: System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup.StorageSpaceDiskToPhysicalDiskMapping() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Storage\StorageGroup.cs:line 75
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Storage\StorageGroup.cs:line 22
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 525
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 494
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
28/11/2022 12:46:33: LibreHardwareMonitor could not initialize or has no sensors.
```

**Relevant hardware specs and setup**
CPU: Intel 12600K
GPU: RTX 2070

**Comment by Rem0o** [comment]
> LibreHardwareMonitor.Hardware.Storage.StorageGroup.StorageSpaceDiskToPhysicalDiskMapping()

Seems like it is trying to access Storage space disk stuff and it fails. If you don't need storage sensors, I would recommend you untick the storage checkbox in sensor settings.
