### ISSUE TITLE
Getting Error after nVidia drivers apdate

### ISSUE THREAD

**Issue by TestDmitriy** [Rem0o/FanControl.Releases#1359]
**Describe the bug**
Rated like LOW priority issue:
Getting Error after nVidia drivers update like shown on Picture.
Both  2x120 fans on GPU Msi (Sea Hawk 3080) radiator stopped spinning  completely.
BUT, after manual REFRESH sensors, so far everything looks working again, Thank you!
Would be great to see message-recommendation to Restart program or update/re-read Sensors automatically.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
![err1](https://user-images.githubusercontent.com/86534431/206871000-e81ed066-f087-4687-a8a5-5a730a51e203.jpg)
Copy of Log when error starts show:
12/1/2022 10:40:47 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
12/1/2022 10:40:47 PM: NvAPI failed. A complete refresh is required.
12/3/2022 3:05:10 PM: Unhandled exception in FanControl v1.0.0.0
12/3/2022 3:05:10 PM: System.InvalidOperationException: Dialog session has ended.
   at MaterialDesignThemes.Wpf.DialogSession.Close(Object parameter)
   at FanControl.Domain.DialogService.<>c__DisplayClass13_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
12/10/2022 9:43:12 AM: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__18.MoveNext()
12/10/2022 9:43:12 AM: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
12/10/2022 12:37:14 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
12/10/2022 12:37:14 PM: NvAPI failed. A complete refresh is required.

**Relevant hardware specs and setup**
MSI MPG z390m/ i9-9900k/ RTX 3080 Sea Hawk/ RAM 64 Gb 3600 MHz/ NvMe M.2: 2x1 Tb Samsung/ HDD: 2x1Tb/ Win 11x64 Pro

**Comment by Hogman747** [comment]
I'm having this issue also when updating nvidia drivers for last 4-5 months. did you find a fix?

**Comment by Whitegrave** [comment]
I just got this exact same error today while installing newest drivers through GFE

**Comment by meloney0** [comment]
It's been creaping up on me, too. I'm on a new Ryzen processor. For me it started happening when I updated the motherboard bios (high voltage fix).

**Comment by chris-tietgen** [comment]
What's up with this topic having no official response?

What is a "full refresh"? Does it mean I need to uninstall FanControl and reinstall it? Or just re-run the auto configure? Or simply restart FanControl?

**Comment by Rem0o** [comment]
@chris-tietgen 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/4346b993-1128-4eae-ad8c-50e2fa1492d4)

This will reset everything and talk to the new driver.

**Comment by TestDmitriy** [comment]
Just Refresh sensors. No need to reinstall program. It's works for me.
Good luck...
