### ISSUE TITLE
Running FanControl causes Elgato Facecam to disconnect and reconnect sporadically when the camera is idle. 

### ISSUE THREAD

**Issue by notthatwillsmith** [Rem0o/FanControl.Releases#1360]
**Describe the bug**
Running FanControl causes my Elgato FaceCam to disconnect and reconnect sporadically when it's idle, causing Windows to make the "device disconnected/device reconnected chimes". I'm running Windows 11 Pro. 

When the camera is in use (OBS on, etc), it doesn't happen. I've confirmed that when FanControl is off, it doesn't happen. I'm using FanControl v.139, Elgato Cam Hub software is 1.5.0.801 and the camera firmware is v4.06. The only plugin I'm using with FanControl is the Liquidctl Plugin to pull liquid temps from my Kraken Z53. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
The recent date entries are due to me removing and reinstalling the Kraken drivers, because I thought it was the culprit. Here's a representative entry, just in case. 

`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
12/11/2022 5:00:24 PM: Unhandled exception in FanControl v1.0.0.0
12/11/2022 5:00:24 PM: System.Exception: liquidctl returned non-zero exit code 1. Last stderr output:
WARNING: python -m liquidctl.cli is deprecated, prefer python -m liquidctl
ERROR: unexpected OS error with NZXT Kraken Z (Z53, Z63 or Z73): OSError('read error')

   at FanControl.Liquidctl.LiquidctlCLIWrapper.LiquidctlCall(String arguments)
   at FanControl.Liquidctl.LiquidctlCLIWrapper.ReadStatus(String address)
   at FanControl.Liquidctl.LiquidctlDevice.LoadJSON()
   at FanControl.Liquidctl.LiquidctlPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Relevant hardware specs and setup**
Motherboard is a ROG Maximum Z790 Apex, there are Fractal RGB Aspect fans plugged into the motherboard headers, and the cooler/AIO is a NZXT Kraken Z53 with nothing else plugged into it.

**Comment by Rem0o** [comment]
Have you tried without the plugin? I do believe liquidctl uses usb stuff to communicate with various devices.

**Comment by notthatwillsmith** [comment]
That seems like the culprit. Running FanControl without the liquidctl plugin for the last half hour didn't disconnect the camera. I'll repost over at the repo for the plugin.

**Comment by notthatwillsmith** [comment]
FYI, I was able to fix this by using one of the USB 3.1 ports on the computer for the camera, vs the USB 3.2 ports. I believe the internal header the pump is connected to is on the USB 3.2 bus.

**Comment by alexluckett** [comment]
Can confirm this relates to the liquidctl plugin. It hasn't been updated since 2022, however a [recent fork of the liquidctl plugin](https://github.com/sp00n/FanControl.Liquidctl) using a more recent version of liquidctl resolves this issue.
