### ISSUE TITLE
GeForce RTX support

### ISSUE THREAD

**Issue by trowieuk** [Rem0o/FanControl.Releases#14]
Any chance you could look into adding support for RTX cards again? or is this 100% an issue with libre limitions?

**Comment by Rem0o** [comment]
it's on Libre, but even then it's more on Nvidia not releasing their API publicly to control newer cards.

**Comment by acme64** [comment]
man this the only thing keeping me from relying on this program 100% All i really need to do is set a minimum fan speed on my rtx to 1%. for some reason my mobo keeps jumping up and down from 0-200rpm, the sounds of the fans make a weird whiny noise when they do it.

**Comment by trowieuk** [comment]
> 
> 
> man this the only thing keeping me from relying on this program 100% All i really need to do is set a minimum fan speed on my rtx to 1%. for some reason my mobo keeps jumping up and down from 0-200rpm, the sounds of the fans make a weird whiny noise when they do it.

I take it you've got a gigabyte card? If so, that's a gigabyte issue. If you setup a fan curve thats starts at 40% you shouldn't hear whinning and that's probably as low as you'll get without a whine. 20% is factory lowest that's why it jumps when you set it to 1%. But yes, 100% would love to ditch gputweak and have this monitor and control all fans.

One feature i'd like to see is a temperature alarm... set alert temp for multiple specific hardware = pop up alert and custom mp3.

**Comment by acme64** [comment]
its an evga actually. im not talking about coil whine im talking about the fanstop feature. when the gpu is idle the fans don't spin. but for some reason, mine continually turn on and off jumping form 0 to somewhere in the 200's. that quick spin up makes an annoying noise.

**Comment by trowieuk** [comment]
> 
> 
> its an evga actually. im not talking about coil whine im talking about the fanstop feature. when the gpu is idle the fans don't spin. but for some reason, mine continually turn on and off jumping form 0 to somewhere in the 200's. that quick spin up makes an annoying noise.

I only mentioned gigabyte because that's what they usually do, start, stop. That's why I asked.
https://www.reddit.com/r/nvidia/comments/a5wr1e/anyone_else_having_fan_revving_issues_on_gigabyte/

Mobo is terrible for fan controls, I used that for my cpu & case fans before I found this and the ramp up noise fried me.
Have you tried setting 1% fan speed in a different software to see if it still ramps up/down?

**Comment by jordanneenan** [comment]
I'm not sure if this issue is linked, but my GTX1070 keeps ramping up to 50% fan speed after a certain amount of time, between 10s and 30s. If I turn the profile off and on again, it goes back to 50% again.

**Comment by romek71** [comment]
Or maybe the author would try to add RTX card support with this: https://github.com/falahati/NvAPIWrapper.In similar programs it works without any problem.

**Comment by jordanneenan** [comment]
I'm an idiot. I completely forgot that I already had MSI Afterburner installed...and for some reason it had its fan curve set to a minimum of 50%.

**Comment by Rem0o** [comment]
> Or maybe the author would try to add RTX card support with this: https://github.com/falahati/NvAPIWrapper.In similar programs it works without any problem.

Might look into it. If I can find a similar thing for AMD cards, will look into switching the backend for the GPUs.

**Comment by Rem0o** [comment]
Update:

Got an early integration of https://github.com/falahati/NvAPIWrapper.In working with FanControl. Will probably release a beta or something with it pretty soon.

**Comment by trowieuk** [comment]
> 
> 
> Update:
> 
> Got an early integration of https://github.com/falahati/NvAPIWrapper.In working with FanControl running alongside LHM. Will probably release a beta or something with it pretty soon. Works great so far with my 1060.

Nice!

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V39-beta

**Comment by trowieuk** [comment]
> 
> 
> https://github.com/Rem0o/FanControl.Releases/releases/tag/V39-beta

Unfortunately it's not showing my GPU https://i.gyazo.com/ae9b826ed1f193c6c742a66bea5a9a88.png

GPU fans set to 100% so shouldn't be 0rpm.

**Comment by romek71** [comment]
My v39 version doesn't want to start at all.
[Błąd 1.txt](https://github.com/Rem0o/FanControl.Releases/files/5028457/Blad.1.txt)
[Błąd 2.txt](https://github.com/Rem0o/FanControl.Releases/files/5028459/Blad.2.txt)

Version 38 runs without any problems.

**Comment by acme64** [comment]
same, won't launch 
`Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.Linq.Enumerable.ElementAt[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, Int32)
   at FanControl.Models.NVApiControlSensor.Update()
   at FanControl.Domain.ComputerAccessLayer.a()
   at FanControl.Domain.ComputerAccessLayer..ctor(FanControl.Domain.ILogger)
   at FanControl.App.a(Autofac.ContainerBuilder)
   at FanControl.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FanControl.App.Main()

`

**Comment by Rem0o** [comment]
Stupid mistake. Will fix.

**Comment by romek71** [comment]
Version 39 beta 2 starts up and runs ok .
![screenshot 7](https://user-images.githubusercontent.com/67829150/89534445-3edf4380-d7f5-11ea-91aa-93ad675f1cc0.jpg)

**Comment by Rem0o** [comment]
> Version 39 beta 2 starts up and runs ok .

How about the controls for your GPU?

**Comment by romek71** [comment]
There is no problem with fan control. Only the fan has to be 4 pin PWM.On my rtx 2060 there are two separate fan outputs so there are two fan control points.

**Comment by Rem0o** [comment]
What about the temperature sensors? Do you only get GPU core or you get others as well?

**Comment by romek71** [comment]
My card generally only provides GPU temperature. HWINFO also only reads GPU temperature.

**Comment by Rem0o** [comment]
@romek71  thanks for the input.

**Comment by trowieuk** [comment]
Tried latest beta two fans show up but neither allow me to change the middle fan speed and I need to enable both fans that do show with the same settings or the fans will ramp up and down... https://i.gyazo.com/24d4cc41a7db64abdb474eafa8a89721.png So I believe the two fans that are showing are 1 for left and 1 for right, they should both be one fan, they can't be different speeds or it starts being weird.

**Comment by Rem0o** [comment]
> Tried latest beta two fans show up but neither allow me to change the middle fan speed and I need to enable both fans that do show with the same settings or the fans will ramp up and down... https://i.gyazo.com/24d4cc41a7db64abdb474eafa8a89721.png So I believe the two fans that are showing are 1 for left and 1 for right, they should both be one fan, they can't be different speeds or it starts being weird.

If you enable only one of the two, does it do that weird behavior ? I suspect your "leftand right" are actually bound together, but mapped to two different controls that are actually the same. That's really odd.

**Comment by trowieuk** [comment]
> 
> 
> > Tried latest beta two fans show up but neither allow me to change the middle fan speed and I need to enable both fans that do show with the same settings or the fans will ramp up and down... https://i.gyazo.com/24d4cc41a7db64abdb474eafa8a89721.png So I believe the two fans that are showing are 1 for left and 1 for right, they should both be one fan, they can't be different speeds or it starts being weird.
> 
> If you enable only one of the two, does it do that weird behavior ? I suspect your "leftand right" are actually bound together, but mapped to two different controls that are actually the same. That's really odd.

Yeah it does because it thinks it's off, then on... this is still good though, idc about having middle @ 70% that fan makes little to no noise.

**Comment by acme64** [comment]
EVGA 2070 super, everything working perfectly. There's an error when trying to close the window however.


`
8/9/2020 2:01:11 AM: Unhandled exception in FanControl v1.0.0.0
8/9/2020 2:01:11 AM: Self referencing loop detected for property 'SelectedFanCurve' with type 'FanControl.ViewModels.SyncFanCurveViewModel'. Path 'FanCurves[2].SelectedControl'.
8/9/2020 2:01:11 AM:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at FanControl.Domain.ApplicationContext.b(KeyValuePair`2 A_0)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at FanControl.Domain.ApplicationContext.c()
   at FanControl.Domain.ApplicationContext.ApplicationStateChanged()
   at FanControl.ViewModels.MainWindowViewModel.d.e()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.d.d()
8/9/2020 2:01:20 AM: Self referencing loop detected for property 'SelectedFanCurve' with type 'FanControl.ViewModels.SyncFanCurveViewModel'. Path 'FanCurves[2].SelectedControl'.
8/9/2020 2:01:20 AM:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at FanControl.Domain.ApplicationContext.b(KeyValuePair`2 A_0)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at FanControl.Domain.ApplicationContext.c()
   at FanControl.Domain.ApplicationContext.SaveApplicationState(String fileName)
8/9/2020 2:01:26 AM: Unhandled exception in FanControl v1.0.0.0
8/9/2020 2:01:26 AM: Self referencing loop detected for property 'SelectedFanCurve' with type 'FanControl.ViewModels.SyncFanCurveViewModel'. Path 'FanCurves[2].SelectedControl'.
8/9/2020 2:01:26 AM:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at FanControl.Domain.ApplicationContext.b(KeyValuePair`2 A_0)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at FanControl.Domain.ApplicationContext.c()
   at FanControl.Domain.ApplicationContext.ApplicationStateChanged()
   at FanControl.ViewModels.MainWindowViewModel.d.e()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.d.d()
8/9/2020 2:03:11 AM: Unhandled exception in FanControl v1.0.0.0
8/9/2020 2:03:11 AM: Self referencing loop detected for property 'SelectedFanCurve' with type 'FanControl.ViewModels.SyncFanCurveViewModel'. Path 'FanCurves[2].SelectedControl'.
8/9/2020 2:03:11 AM:    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at FanControl.Domain.ApplicationContext.b(KeyValuePair`2 A_0)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at FanControl.Domain.ApplicationContext.c()
   at FanControl.Domain.ApplicationContext.ApplicationStateChanged()
   at FanControl.ViewModels.MainWindowViewModel.d.e()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.d.d()`
