### ISSUE TITLE
GUI broken after update to V65

### ISSUE THREAD

**Issue by bkenez** [Rem0o/FanControl.Releases#141]
**What is happening:**
After updating to V65, after opening the program and okaying the UAC prompt, there is just fancontrol.exe running as a background service, no tray icon, or anything on the taskbar either, cannot be interacted with in any way. Deleting the configuration JSONs did not fix the issue.

**What is expected to happen:**
Program GUI opens up normally or minimised to tray.

**Workaround:**
Rolling back to V64 completely fixes this issue.

Using windows 10 LTSC

Feel free to ask for any additional details that might help.

**Comment by Rem0o** [comment]
Look for log.txt in the app folder.

**Comment by jyanes83** [comment]
Could this be related to the false virus warning I get when attempting to update?.  This similar thing you describe is what happened to me, but I noticed that it was because the updater attempts to download and then unarchive but throws a potential virus warning message.  I did not see anything captured in the logs.  I had to run the updater through command line so I could see the error

**Comment by bkenez** [comment]
> 
> 
> Look for log.txt in the app folder.

Thanks, there does seem to be something useful there.

`2021/01/29 19:46:10: Unhandled exception in FanControl v1.0.0.0
2021/01/29 19:46:10: Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:FanControl.Views.TrayIconView. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Views.IconFactory..ctor()
   at FanControl.Views.TrayIconView..ctor(Action show, IApplicationContext applicationContext)
   at FanControl.App.<>c__DisplayClass16_0.<RegisterTypes>b__15(IComponentContext _)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021/01/29 19:46:10: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Views.IconFactory..ctor()
   at FanControl.Views.TrayIconView..ctor(Action show, IApplicationContext applicationContext)
   at FanControl.App.<>c__DisplayClass16_0.<RegisterTypes>b__15(IComponentContext _)
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)`

**Comment by Rem0o** [comment]
At that spot I'm reading the registry key: CurrentUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize.

It is probably missing from your PC.  Will have to add additional fall back mechanism.

**Comment by bkenez** [comment]
Great, thanks for looking into it! Will continue to use V64 in the meantime. These are the registry keys that live under there currently if it helps.
![image](https://user-images.githubusercontent.com/1926510/106323256-68929800-6277-11eb-80f3-24becf1c2c4f.png)

Win10 LTSC 1809, Version 10.0.17763 Build 17763

**Comment by Rem0o** [comment]
Hummm, clearly you got everything, I then have no idea where that null exception comes from.... Will add logs arround that area I guess, thanks for the stacktrace.

**Comment by theAeon** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5904501/log.txt)
same issue here.

**Comment by Rem0o** [comment]
@bkenez added logs in V66

**Comment by bkenez** [comment]
Updated to V66, now the UI actually launches. Seems like the changes worked then, thanks!

Here are the contents of log.txt:

```
2021/02/01 19:46:12: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Views.IconFactory.GetUseLightTheme(ILogger logger)
```
