### ISSUE TITLE
Case fans plugged into MOBO no longer spin while Fancontrol is running.

### ISSUE THREAD

**Issue by LUCKYXIII** [Rem0o/FanControl.Releases#1446]
Today after I restarted the PC my case fans would spin up normally, but as soon as _FanControl_ launched (auto launch with windows) the case fans would then wind down to 0rpm, all with exception of the D5 pump. As soon as I exit the program, the fans spin back up. I tried refreshing the sensor detection and the fans spin up very slightly then go back to 0 RPM. I installed a fresh copy of the program in another folder and tried running that, but unfortunately it gave me the same result: Only the D5 is recognized and controllable.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
2023-01-09 12:05:54 AM: Unhandled exception in FanControl v1.0.0.0
2023-01-09 12:05:54 AM: System.IO.IOException: Illegal operation attempted on a registry key that has been marked for deletion.

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalValueCount()
   at FanControl.HWInfo.HWInfoRegistry.UpdateValues(HWInfoPluginSensor[] sensors)
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2023-01-09 12:05:55 AM: Unhandled exception in FanControl v1.0.0.0
2023-01-09 12:05:55 AM: System.IO.IOException: Illegal operation attempted on a registry key that has been marked for deletion.

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalValueCount()
   at FanControl.HWInfo.HWInfoRegistry.UpdateValues(HWInfoPluginSensor[] sensors)
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2023-01-09 12:07:32 AM: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
2023-01-09 12:12:18 AM: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
2023-01-09 12:31:50 AM: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
2023-01-09 12:40:51 AM: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
2023-01-09 12:47:59 AM: Unhandled exception in FanControl v1.0.0.0
2023-01-09 12:47:59 AM: System.IO.IOException: Illegal operation attempted on a registry key that has been marked for deletion.

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalValueCount()
   at FanControl.HWInfo.HWInfoRegistry.UpdateValues(HWInfoPluginSensor[] sensors)
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2023-01-09 12:52:51 AM: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
2023-01-09 12:52:54 AM: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()

ASUS ROG Hero XII
i9-10850k
Phanteks T30 (3)
Arctic P12 (12)

**Comment by LUCKYXIII** [comment]
So I opened and ran ASUS AiSuite and ran the fan setup utility. After it completed I tried running FanControl again and low and behold it works as usual now.
