### ISSUE TITLE
crashes at startup

### ISSUE THREAD

**Issue by peterf81** [Rem0o/FanControl.Releases#1475]
Logs from event viewer :

Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFA247621A6

--

Faulting application name: FanControl.exe, version: 1.0.0.0, time stamp: 0xf63fefc2
Faulting module name: d3d9.dll, version: 10.0.19041.1865, time stamp: 0x4ddae39c
Exception code: 0xc0000005
Fault offset: 0x00000000000521a6
Faulting process ID: 0x2f60
Faulting application start time: 0x01d92bdef49569b8
Faulting application path: D:\Incoming\FanControl\FanControl.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report ID: e884f606-5942-4401-ad44-6d58350bec3e
Faulting package full name: 
Faulting package-relative application ID: 

--

Faulting application name: FanControl.exe, version: 1.0.0.0, time stamp: 0xf63fefc2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1865, time stamp: 0xdd841229
Exception code: 0xe0434352
Fault offset: 0x0000000000034fd9
Faulting process ID: 0x2ed4
Faulting application start time: 0x01d92bdfdcd4b741
Faulting application path: D:\Incoming\FanControl\FanControl.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 22174758-b52d-460c-94dc-77bf3d28b3c4
Faulting package full name: 
Faulting package-relative application ID: 

--

Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean)
   at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding)
   at System.IO.File.InternalAppendAllText(System.String, System.String, System.Text.Encoding)
   at FanControl.Domain.Logger.Log(System.String, Boolean)
   at FanControl.App.LogUnhandledException(FanControl.Domain.ILogger, FanControl.Domain.IDialogService, System.Exception, System.String)
   at FanControl.App.<SetupExceptionHandling>b__15_1(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FanControl.App.Main()

**Comment by Rem0o** [comment]
Hard to say from that log what's happening. It couldn't even log the exception itself, hence the event viewer crash.  Does it happen everytime? How is your start with windows setup? Do you have a delay applied?
