### ISSUE TITLE
FanControl fails to start (System.NullReferenceException)

### ISSUE THREAD

**Issue by ddenev** [Rem0o/FanControl.Releases#150]
Hi,

I had FanControl running for quite some time and today I just restarted my PC (Windows 10 64-bit) and after the restart FanControl would not start. There are these errors in Event Viewer

```
Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at FanControl.Domain.ComputerAccessLayer.HasNvidia()
   at FanControl.Domain.ComputerAccessLayer.Close()
   at FanControl.Domain.ComputerAccessLayer.Dispose()
   at Autofac.Core.Activators.ProvidedInstance.ProvidedInstanceActivator.Dispose(Boolean)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Registration.ComponentRegistration.Dispose(Boolean)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.Dispose(Boolean)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Registration.ComponentRegistry.Dispose(Boolean)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean)
   at Autofac.Util.Disposable.Dispose()
   at FanControl.App.OnExit(System.Windows.ExitEventArgs)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FanControl.App.Main()
```
and 
```
Faulting application name: FanControl.exe, version: 1.0.0.0, time stamp: 0x93a0318e
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffb814f3d8a
Faulting process id: 0x22d4
Faulting application start time: 0x01d6f94e7dcc0bbc
Faulting application path: D:\Applications\FanControl\FanControl.exe
Faulting module path: unknown
Report Id: fb075f00-0a8e-4dce-add2-104a3488ee29
Faulting package full name: 
Faulting package-relative application ID: 
```
I haven't installed/uninstalled anything lately. I have the latest version of FanControl.

Thank you in advance!

**Comment by ddenev** [comment]
Sorry about that but it wasn't working the whole morning and now it suddenly started on its own, I didn't even start it manually... illuminati?! :)

My suspicion is the Task Scheduler task was running long time (I saw it in a Running state after the restart and it stayed so for quite some time) and that is why it didn't want to start when I tried to start it manually... go figure...
