### ISSUE TITLE
All fans missing except for one graphics card.

### ISSUE THREAD

**Issue by Deejay85** [Rem0o/FanControl.Releases#1520]
Recently all the fans except for one (the graphics card) went missing. I deleted everything, put in the latest copy, and it didn't fix the problem. Also I haven't recently changed anything so that rules that out. Additionally, when I look at the fans, their all spinning, so it's not like their unplugged somehow, which make sense since I haven't opened my PC recently either. Restarting didn't fix it...I do have Avast!, and yes, I already added it as an exception to both the firewall and the allowed apps list, did a fresh install of the program, and it's still doing the same thing.

**Comment by mad-ady** [comment]
I too have encountered the same issue (though I don't have Avast).
I was running v144 and had no issues with it. Today it offered to upgrade to v145 and I accepted. After reboot I got the message that is is missing control sensors in the configuration. I downgraded to v144 (unzipped the v144 files on top of v145), restarted, but I get the same error.

When searching for sensors I get the same error.

Here's a screenshot: https://imgur.com/OH1zBf8.png

**Comment by Rem0o** [comment]
Make sure it runs as admin.

**Comment by Deejay85** [comment]
> Make sure it runs as admin.

Waaaaay ahead of you on that one.

**Comment by Rem0o** [comment]
Any log.txt?

**Comment by Deejay85** [comment]
2/10/2023 3:50:42 AM: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__18.MoveNext()
2/10/2023 3:50:42 AM: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by Matumbo** [comment]
Have the same issue.
One morning Avast One detected FanControl driver as a threat and I could unblock it anymore. Avast One is weird.
After reinstalling FanControl just my GPU Fan got detected.
Hope FanControl didn´t got hacked. 
Now i'll wait for and see if an FanControl or Avast update is gonna solve the issue.

**Comment by mad-ady** [comment]
For me it started working again after a reinstall + reboot + running as
admin. Though I can't say what "fixed" it...

**Comment by Wyhutt** [comment]
Bump. This exact thing just happen to me. After starting Overwatch, my pc crashed and my fans went missing (except gpu fan).
Tried uninstalling using RevoUninstaller and reinstall, same problem. Tried uninstalling with windows and reinstalling, same problem. I am also running as admin.
