### ISSUE TITLE
Fan Control exits with exception with Right-click on system tray icon

### ISSUE THREAD

**Issue by g4wnc** [Rem0o/FanControl.Releases#1562]
**Describe the bug**
Fan Control appears to start ok and controls the fans as expected, but when I right-click the system tray icon I get "An unexpected error occurred, see log file"

I've attached the log file but here's the relevant extract:
 End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<OnStartup>d__11.MoveNext()

The PC is running Windows 11 Pro, with i7 1300kf processor, 64GB DDR5 RAM, MSI GTX 1660 Super GPU, 

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/10823415/log.txt)

Thanks for your help and for producing an excellent program.

Mike

**Comment by Zaphodisback** [comment]
+1 same problem

**Comment by RheologyOrbit** [comment]
Switching to the .net 7 version on the releases page seemed to resolve this issue for now on Win 11 Home.

**Comment by BeefRendang** [comment]
I got the same error above when right clicking, so I followed the suggestion to use dot net 7, it still does not work for Win 10 Pro. FanControl works, I tested by running benchmark, it controls fans but any right click on the tray icon gives me this error on dot net 7

   at FanControl.Domain.ApplicationContext.InvokeAsync(Func`1 action)
   at FanControl.Domain.DialogService.ShowDialog[TView](INotifyPropertyChanged viewModel, Nullable`1 cancellationToken)
   at FanControl.Domain.DialogService.LogDialogException[TView](Exception exception)
   at FanControl.Domain.DialogService.ShowDialog[TView](INotifyPropertyChanged viewModel, Nullable`1 cancellationToken)
   at FanControl.ViewModels.Utilities.HelpDialogs.PaypalDialog(Boolean hasFanCurves, Action`1 editViewModel)
   at FanControl.App.PaypalDialog()
   at FanControl.App.OnStartup(StartupEventArgs eventArgs)

**Comment by Rem0o** [comment]
I was able to reproduce the issue. Will be fixed.

**Comment by g4wnc** [comment]
That's great news. Thank you.  Mike

**Comment by Rem0o** [comment]
V148 has the fix.

**Comment by BeefRendang** [comment]
Thank you, I tested and confirmed this works. Win 10 Pro using v148, I can now right click and open FanControl without issue.
