### ISSUE TITLE
System.IO.IOException: Illegal operation attempted on a registry key that has been marked for deletion.

### ISSUE THREAD

**Issue by digitalfrost84** [Rem0o/FanControl.Releases#1642]
**Describe the bug**

My log is full of this:

```20.03.2023 17:48:18: Unhandled exception in FanControl v1.0.0.0
20.03.2023 17:48:18: System.IO.IOException: Illegal operation attempted on a registry key that has been marked for deletion.

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalValueCount()
   at FanControl.HWInfo.HWInfoRegistry.UpdateValues(HWInfoPluginSensor[] sensors)
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

It's constantly logged, so the logs fills up really fast.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log_3.txt](https://github.com/Rem0o/FanControl.Releases/files/11044827/log_3.txt)

**Relevant hardware specs and setup**

**Comment by Rem0o** [comment]
That's the HWInfo plugin.   Mind transferring to the proper repository?  (Closing here)

Also, detail maybe the state of HWInfo while this happen?
