### ISSUE TITLE
LibreHardwareMonitor could not initialize or has no sensors

### ISSUE THREAD

**Issue by QuelRoch** [Rem0o/FanControl.Releases#1666]
Doesn't recognize any fans other than gpu, all my fans are 4pin pwm. I've tried to disable storage sensors but gives out the same error.

https://we.tl/t-1Qtqud6hWf

motherboard supermicro x9drd-if
fans NK12BK4-3 and XPF80.R.PWM

**Comment by Rem0o** [comment]
AFAIK SuperMicro boards are not supported by LHM.

**Comment by 0jit0** [comment]
Same here, I changed some of my fans and now I get this message even if I roll everything back to how it was setup before.

**Comment by LiamKarlMitchell** [comment]
Hey just an update, updated to latest version released 7.0.5 with new dot net runtimes.
Still same issue Fan Control wont start.

CPU getting pretty hot over 80%... it was working many versions ago.

```
3/05/2023 11:32:42 pm: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.LpcIO.<FindGigabyteEC>g__DetectVendor|11_0(<>c__DisplayClass11_0&) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\LpcIO.cs:line 674
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.LpcIO.FindGigabyteEC(LpcPort port, Chip chip, Motherboard motherboard) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\LpcIO.cs:line 668
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.LpcIO.DetectIT87(LpcPort port, Motherboard motherboard) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\LpcIO.cs:line 607
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.LpcIO.Detect(Motherboard motherboard) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\LpcIO.cs:line 72
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.LpcIO..ctor(Motherboard motherboard) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\LpcIO.cs:line 26
   at LibreHardwareMonitor.Hardware.Motherboard.Motherboard..ctor(SMBios smBios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Motherboard.cs:line 70
   at LibreHardwareMonitor.Hardware.Motherboard.MotherboardGroup..ctor(SMBios smbios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\MotherboardGroup.cs:line 18
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 500
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 492
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
3/05/2023 11:32:42 pm: LibreHardwareMonitor could not initialize or has no sensors.
```

**Comment by Rem0o** [comment]
Disable the InpOut section in sensor settings.

**Comment by LiamKarlMitchell** [comment]
No difference it seems to not start up after clicking Ok on the sensor settings dialog.
