### ISSUE TITLE
No Sensors Detected After Installation of GeForce Card

### ISSUE THREAD

**Issue by tscislowski** [Rem0o/FanControl.Releases#1723]
I had everything running just fine until GeForce GT 710 was installed.

4/17/2023 7:10:05 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Ipmi.Update(StringBuilder stringBuilder) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Ipmi.cs:line 190
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Ipmi..ctor(Manufacturer manufacturer) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Ipmi.cs:line 68
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.LpcIO..ctor(Motherboard motherboard) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\LpcIO.cs:line 31
   at LibreHardwareMonitor.Hardware.Motherboard.Motherboard..ctor(SMBios smBios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Motherboard.cs:line 70
   at LibreHardwareMonitor.Hardware.Motherboard.MotherboardGroup..ctor(SMBios smbios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\MotherboardGroup.cs:line 18
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 500
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 492
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()

![image](https://user-images.githubusercontent.com/68571381/232629466-00d44168-0764-4e85-943e-4a4371ea238c.png)

![image](https://user-images.githubusercontent.com/68571381/232629542-6d014ed4-0a47-4457-8915-8c28814ba8ac.png)

**Comment by Rem0o** [comment]
This was fixed/merged in LHM.
