### ISSUE TITLE
request to add support for External Coolant Temperature Sensor on Asus mb

### ISSUE THREAD

**Issue by ahodges-git** [Rem0o/FanControl.Releases#179]
Love the software - just made a donation.

I have a coolant temperature sensor that plugs into a 2 pin header (T_Sensor) on my Asus Crosshair VIII Impact motherboard.

I'm keen to see if that can be added as an option in the sensor selection list.

Motherboard manual:
![image](https://user-images.githubusercontent.com/80186464/110228504-6645ec80-7f4d-11eb-94a9-5c986e363c06.png)

Appears in HWiNFO64:
![image](https://user-images.githubusercontent.com/80186464/110228524-7eb60700-7f4d-11eb-85dd-b9086fb00b17.png)

**Comment by Rem0o** [comment]
HWInfo SDK is closed and paid license. 

Any hardware support matter is handled by:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.HWInfo

**Comment by Rem0o** [comment]
Tell me if that plugins lets you read that sensor.

**Comment by ahodges-git** [comment]
The sensor now shows up under the list but just reads 0c continuously.

I get the error shown below on startup and then continuously whilst running Fan Control.

Running FanControl v72 with HWInfo plugin, HWInfo64 v7 with shared memory on.

24/03/2021 3:57:27 PM: Unhandled exception in FanControl v1.0.0.0
24/03/2021 3:57:27 PM: System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add) at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer`1 comparer)
at FanControl.Domain.ComputerAccessLayer.Update()
at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
