### ISSUE TITLE
No longer detecting my motherboard sensors

### ISSUE THREAD

**Issue by Seann1911** [Rem0o/FanControl.Releases#1832]
6/15/2023 2:56:54 PM: LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.EmbeddedController+MultipleBoardRecordsFoundException: Multiple board records refer to the same model 'ROG_CROSSHAIR_X670E_EXTREME'
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.EmbeddedController.Create(Model model, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\EC\EmbeddedController.cs:line 337
   at LibreHardwareMonitor.Hardware.Motherboard.Motherboard..ctor(SMBios smBios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Motherboard.cs:line 71
   at LibreHardwareMonitor.Hardware.Motherboard.MotherboardGroup..ctor(SMBios smbios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\MotherboardGroup.cs:line 18
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 501
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 495
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()

Motherboard Asus Crosshair X670E Extreeme
![Screenshot 2023-06-15 155053](https://github.com/Rem0o/FanControl.Releases/assets/136761805/5f4d6d0d-18e0-4e9a-91ce-084669209c59)

**Comment by Rem0o** [comment]
> at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.EmbeddedController.Create(Model model, ISettings settings) in

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/715e87cd-5e33-40ff-8961-f7bd9b6ee853)

**Comment by Seann1911** [comment]
> 

I've tried detecting with that option selected and deselected with no change.

**Comment by Seann1911** [comment]
V159 works so I will stick with that for now.

**Comment by scostigan1** [comment]
Having same issue. How do I load an older version?

**Comment by Seann1911** [comment]
https://github.com/Rem0o/FanControl.Releases/releases

Make sure you Backup your config first.
