### ISSUE TITLE
LibreHardwareMonitor coult not initialize or has no sensors.

### ISSUE THREAD

**Issue by jiangtianh** [Rem0o/FanControl.Releases#1850]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]
Somehow all the motherboard sensors can't be detected... It can only detect my GPU fans. 
It was working fine before the update. 
![image](https://github.com/Rem0o/FanControl.Releases/assets/112032591/8847acc6-383d-49f9-9014-f093b5e0ba28)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
6/23/2023 11:41:53 AM: LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.EmbeddedController+MultipleBoardRecordsFoundException: Multiple board records refer to the same model 'ROG_CROSSHAIR_X670E_EXTREME'
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.EmbeddedController.Create(Model model, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\EC\EmbeddedController.cs:line 337
   at LibreHardwareMonitor.Hardware.Motherboard.Motherboard..ctor(SMBios smBios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Motherboard.cs:line 71
   at LibreHardwareMonitor.Hardware.Motherboard.MotherboardGroup..ctor(SMBios smbios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\MotherboardGroup.cs:line 18
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 501
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 495
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]
7950X
Rog Strix rtx 4090 
Rog Crosshair x670E Exterme

**Comment by Rem0o** [comment]
Known issue. LHM had a bug with duplicate board detection. It has been fixed since, will be in the next release.
