### ISSUE TITLE
Can't change theme or color of tray icon in V161 

### ISSUE THREAD

**Issue by ivulfson** [Rem0o/FanControl.Releases#1861]
Windows 10, V161 defaults tray icon to Black, and I can't change the theme or color.  

Default tray icon color is Dark, and selection is grayed out.  I can add sensors, but can't change their colors - only black. 

Are we in the "Ford mode" - you can have any color as long as it's black? :)

<img width="347" alt="Capture" src="https://github.com/Rem0o/FanControl.Releases/assets/9122139/b72237aa-c33f-4282-9b38-52c32444f3ca">

Relevant section from config:

```
    "TrayIconColor": "#FF000000",
    "TrayIcons": []
```

I tried changing the Color value by hand to `#FFFFFF00` but then I get error popups for some reason.

Log:

```
6/27/2023 6:06:54 PM: System.NotSupportedException: Specified method is not supported.
   at FanControl.Views.Converters.ThemeToColorConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
6/27/2023 6:07:28 PM: Unhandled exception in FanControl v161.0.0.0
```

**Comment by ivulfson** [comment]
<img width="347" alt="Capture" src="https://github.com/Rem0o/FanControl.Releases/assets/9122139/b72237aa-c33f-4282-9b38-52c32444f3ca">

**Comment by Rem0o** [comment]
Add a tray icon temp, then select it in the list, then change its color?

**Comment by Rem0o** [comment]
@ivulfson  Yeah that's actually by (bad) design.   When sync is on, it will try to figure out the best color both for the app theme and the tray icon.   Not obvious.  Could put the checkbox maybe in both spot.

**Comment by ivulfson** [comment]
No big deal, actually, but I doubt I'm the only person who was confused by it.

You could separate the checkboxes - checkbox on Theme only affects the window theme.  Then add a checkbox on Tray Icons screen, with label "Sync tray theme with Windows", and have that checkbox only affect the Tray icon setting.

More fiddly (adding config key for another checkbox, separating one checkbox to two, adding another checkbox on a second screen), but perhaps a bit more clear.

Thank you very much in any case, this app is fantastic, no pun intended.

**Comment by schmittyd** [comment]
Don't know if this is related or not but when setting sensor colours it prepends FF to the hex code.

**Comment by Rem0o** [comment]
@schmittyd  the first FF is the alpha channel.

**Comment by ivulfson** [comment]
I see Sync checkbox is now on both screens in V164.  I think this resolved this.

Also preview, a very nice touch.

**Comment by b1k3rdude** [comment]
I was also caught by this, but a quick internet search brought me here :-)
