### ISSUE TITLE
[ERROR] Error occurs while restoring the configuration

### ISSUE THREAD

**Issue by Scanda85** [Rem0o/FanControl.Releases#187]
Fan Control V71 is loaded at system startup (Win10).
Sometimes i got following error message:

![Screenshot 2021-03-19 165457](https://user-images.githubusercontent.com/20796795/111808386-3f37d500-88d4-11eb-8890-bd0d8f43a6d3.png)

After clicking "OK" and "Refresh" the error is gone, all controls, speeds and curves are loaded.

**Comment by Rem0o** [comment]
Some systems have a delay for some reasons at boot for the sensors to be readable. If FanControl starts before that delay, it won't be able to load your config, that's the error you got, with all the missing sensors. I put the refresh in there to catch those cases and be able to recover.

**Comment by Rem0o** [comment]
I guess it could have an auto-refresh after 30 secs if the user didn't interact with it?

**Comment by Scanda85** [comment]
yeah an automatic 30sec refresh in the background sounds good.

**Comment by Scanda85** [comment]
Still open with V73

**Comment by dataslug1** [comment]
Hi I am having the same issue, an automatic "OK" and "refresh" (sometimes needed 2-3 times) after 30 seconds (or less) would be highly appreciated.  Log comments below.  Thank you

06/05/2021 17:33:09: Unhandled exception in FanControl v1.0.0.0
06/05/2021 17:33:09: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Nct677X.SetControl(Int32 index, Nullable`1 value)
   at LibreHardwareMonitor.Hardware.Motherboard.SuperIOHardware.<>c__DisplayClass16_1.<CreateControlSensors>b__0(Control cc)
   at LibreHardwareMonitor.Hardware.Control.set_ControlMode(ControlMode value)
   at LibreHardwareMonitor.Hardware.Control.SetSoftware(Single value)
   at FanControl.ViewModels.ControlViewModel.PeriodicUpdate()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Scanda85** [comment]
yes problem is still open with V77
