### ISSUE TITLE
Cannot start FanControl 4.8 in Wondows 8.1 x64 Professional

### ISSUE THREAD

**Issue by viviancels** [Rem0o/FanControl.Releases#1882]
**Describe the bug**
I have all updates for Windows, include Update KB4486105 (NetFramework 4.8). In Windows 10 x64 Enterprise all worked fine

**Is there a log.txt file next to FanControl.exe with recent date entries?**
LOG:

2023-07-04 9:13:29 AM: Autofac.Core.DependencyResolutionException: An exception was thrown while activating FanControl.ViewModels.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken Windows.UI.ViewManagement.UISettings.add_ColorValuesChanged(Windows.Foundation.TypedEventHandler`2<Windows.UI.ViewManagement.UISettings,System.Object>)'.
   at FanControl.ViewModels.WindowSettingsViewModel..ctor(IApplicationState state, IDialogService dialogService, IApplicationContext applicationContext, IWindowsSettings windowsSettings, IUpdaterService updaterService, ILogger logger, ObservableCollection`1 tempSources)
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.App.<OnStartup>d__12.MoveNext()
2023-07-04 9:13:29 AM: Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken Windows.UI.ViewManagement.UISettings.add_ColorValuesChanged(Windows.Foundation.TypedEventHandler`2<Windows.UI.ViewManagement.UISettings,System.Object>)'.
   at FanControl.ViewModels.WindowSettingsViewModel..ctor(IApplicationState state, IDialogService dialogService, IApplicationContext applicationContext, IWindowsSettings windowsSettings, IUpdaterService updaterService, ILogger logger, ObservableCollection`1 tempSources)
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
2023-07-04 9:13:29 AM: System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken Windows.UI.ViewManagement.UISettings.add_ColorValuesChanged(Windows.Foundation.TypedEventHandler`2<Windows.UI.ViewManagement.UISettings,System.Object>)'.
   at FanControl.ViewModels.WindowSettingsViewModel..ctor(IApplicationState state, IDialogService dialogService, IApplicationContext applicationContext, IWindowsSettings windowsSettings, IUpdaterService updaterService, ILogger logger, ObservableCollection`1 tempSources)
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()

**Comment by EvanMulawski** [comment]
Windows 10+ is required. See https://github.com/Rem0o/FanControl.Releases#faq

> Q: Does it run on my OS?
> A: If your OS is Windows 10 Or 11, yes.
