### ISSUE TITLE
Fan sensors cn not be found after a restart.

### ISSUE THREAD

**Issue by HoruakutiX** [Rem0o/FanControl.Releases#1937]
Thanks for your work, I use this tool since v0.98.

But in v1.63(as well as v1.64, v1.59, v1.38, v1.08), after a system restart, my fancontrol can not find all of the fan sensors, both of the speed sensors and the control sensors. 
the table is empty like this:
![Screenshot (104)](https://github.com/Rem0o/FanControl.Releases/assets/65207518/d97939bc-44e5-4b07-a1ce-b4cac7051b45)

only the carve remain and it show some errors such as "xxx sensor failed to initialize".
the log is as the following:

7/21/2023 21:47:24: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   at NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__19`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
7/21/2023 21:47:27: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   at NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__19`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
7/21/2023 21:47:27: NVApi could not initialize or has no sensors.
7/21/2023 21:47:45: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   at NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__19`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
7/21/2023 22:33:31: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   at NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__19`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
7/21/2023 22:33:34: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   at NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__19`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
7/21/2023 22:33:34: NVApi could not initialize or has no sensors.
7/21/2023 23:43:48: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__23.MoveNext()
7/21/2023 23:43:48: System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
7/21/2023 23:43:48: System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

my gpu sensor is work correctly, so the question is only about the fan sensors.
I have tried old versions to fix this problem, but it seems like using old version can not help, so I report this bug to seek for help.
By the way, the hardware is definitely working correctly, because I can use MSI center to control all the fans. 
CPU: Ryzen r5 5600x
Mather board: MSI B550M Mortar wifi

**Comment by DemonSeedxp** [comment]
I'm having similar issues. Restarted after a week of windows nagging me to install updates and once back on the desktop fan control opened as always and I saw all my fans were gone except for my gpu fans. But once I started trying to see what happened I realized nothing in the UI was working. I could expand the dropdowns but that was it, nothing I clicked would open, or close for that matter because exit wouldnt even work. had to use task manager to close it. 

Checked for an update and there was one, from 162 to 164 but the unresponsive UI persists. So I'm taking a stab in the dark and assuming windows update is to blame, but I'm not sure what they pushed that broke everything. Hopefully me dragging my feet and waiting a week to let windows update has allowed time for this issue to already be known about and someone can instruct what I should remove?

**Comment by pistonfish** [comment]
> I'm having similar issues. Restarted after a week of windows nagging me to install updates and once back on the desktop fan control opened as always and I saw all my fans were gone except for my gpu fans. But once I started trying to see what happened I realized nothing in the UI was working. I could expand the dropdowns but that was it, nothing I clicked would open, or close for that matter because exit wouldnt even work. had to use task manager to close it.
> 
> Checked for an update and there was one, from 162 to 164 but the unresponsive UI persists. So I'm taking a stab in the dark and assuming windows update is to blame, but I'm not sure what they pushed that broke everything. Hopefully me dragging my feet and waiting a week to let windows update has allowed time for this issue to already be known about and someone can instruct what I should remove?

Same here. I don't know what caused this, but from one day to another, every sensor, except for my GPU, is missing. The GPU controls were also unresponsive, but after making another config, they are now working again.

**Comment by pistonfish** [comment]
This seems to have resolved itself (at least for me) after installing the last Windows Update
