### ISSUE TITLE
CPU & GPU Sensors Not Working After Update (v164)

### ISSUE THREAD

**Issue by CrimsnShadow** [Rem0o/FanControl.Releases#1942]
**Bug**
GPU (and sometimes CPU) Sensor(s) not detected after latest update (v164)

**Log**

3/31/2023 10:07:57 PM: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__17.MoveNext()
3/31/2023 10:07:57 PM: System.Net.WebException: The remote name could not be resolved: 'raw.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Hardware Specs**
Board: MSI B450 Gaming Plus Max
CPU: AMD Ryzen 5 3600
GPU: XFX Radeon RX 580

**Config Screenshot**
https://imgur.com/a/PApqdOJ

**Comment by CrimsnShadow** [comment]
Also not sure why the log is dated so far back..

**Comment by CrimsnShadow** [comment]
Nevermind.. Found the issue, Radeon Software was tying to overwrite it. Issue fixed for me.
