### ISSUE TITLE
Sensors & Fans are not recognized as they should since today

### ISSUE THREAD

**Issue by scripteduser** [Rem0o/FanControl.Releases#2039]
![image](https://github.com/Rem0o/FanControl.Releases/assets/144164705/809661b2-1725-4a15-b1b9-499b87c249b4)

![image](https://github.com/Rem0o/FanControl.Releases/assets/144164705/da517b1b-a829-487c-96bf-403f46495d6b)

Fan Control worked for the past few weeks perfectly fine without any issues when shutting down / booting computer.
(It had only sensor issues when putting to sleep mode, so I just went to shutting down computer)

Since today sensors / fans couldn't be found or are linked not as they should be as seen in the picture.
When running the Assisted Setup it will only find 3 "Fans" which are "Back / Tower Fan" "Front Radiator / Fans" and "GPU Pump".
The Top Radiator Fans are missing.

AND

The sensors/fans are linked to wrong devices.

- Now the Fan which actually is the GPU Pump is recognized as Top / CPU Fan.
- The Fan that actually is the GPU Pump is somewhere at 20RPM and I can't tell what it recognizes there
- The Front / GPU Radiator Fan & Sensor are linked correctly and work perfectly fine
- The Back / Tower Fan & Mainboard Sensor couldn't be found. (Even though the Fan is just running at 100% speed)

The pattern of the confusion of sensors & fans usually happened when not shutting down computer.
Now it also happens when shutting down and refreshing 100x or restarting the software didn't help at all.

- I have tried setting startup time to 120s
- I have tried running Assisted Setup
- I have tried restarting computer multiple times with plugging out PSU

The only thing I had changed from yesterday to today was making Discord to start with windows and I have reversed that now.

- no log file in the directory C:\Users\alexn\Desktop\Fan Control

Sensors:
B450-PLUS Gaming Mainboard
3600X CPU
RTX 3080 TI GPU

Fans:
2x Watercooler Radiators
1x Tower Fan

**Comment by xopethx** [comment]
I'm having a very similar (if not identical) issue today after the installation of Win10 KB5030211 . 
Nothing else was changed between yesterday and today other than the automatic updates in the middle of the night.  

9/20/2023 4:50:59 PM: HidSharp.Exceptions.DeviceIOException: Failed to get info.
   at HidSharp.Platform.Windows.WinHidDevice.RequiresGetInfo(GetInfoFlags flags)
   at HidSharp.Platform.Windows.WinHidDevice.GetProductName()
   at LibreHardwareMonitor.Hardware.Controller.Razer.RazerGroup..ctor(ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Controller\Razer\RazerGroup.cs:line 24
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 526
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 498
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
9/20/2023 4:50:59 PM: LibreHardwareMonitor could not initialize or has no sensors.

**Comment by Nini81** [comment]
Hi, 

I had what seems to be the same problem 2 or 3 times this week. Each time, uninstalling KB5029919 [(and](https://support.microsoft.com/en-us/topic/september-12-2023-kb5029919-cumulative-update-for-net-framework-3-5-and-4-8-1-for-windows-10-version-21h2-and-windows-10-version-22h2-c483a458-3d08-47b4-b8ed-a01f7861d978) then reboot resolved the issue :

`wusa /uninstall /kb:5029919`

I guess this update block, in some way, reading sensors from LibreHardwareMonitor dll

**Comment by scripteduser** [comment]
> Hi,
> 
> I had what seems to be the same problem 2 or 3 times this week. Each time, uninstalling [KB5029919](https://support.microsoft.com/en-us/topic/september-12-2023-kb5029919-cumulative-update-for-net-framework-3-5-and-4-8-1-for-windows-10-version-21h2-and-windows-10-version-22h2-c483a458-3d08-47b4-b8ed-a01f7861d978), then reboot resolved the issue (until the update install again, of course):
> 
> `wusa /uninstall /kb:5029919`
> 
> I guess this update block, in some way, reading sensors from LibreHardwareMonitor dll
> 
> Edit (if it can help): Win 10 22h2 on :
> 
> * ASUS Z 690-A Prime DDR5
> * i9-12900k
> * 32Go ddr5

Thanks, seems like that has fixed my problem!

**Comment by Nini81** [comment]
Hello,

It seems that there's a new update, [KB5030180](https://support.microsoft.com/fr-fr/topic/september-12-2023-kb5030180-cumulative-update-for-net-framework-3-5-4-8-and-4-8-1-for-windows-10-version-22h2-bf5a4de5-ca36-448f-80cf-4e1ceacd6d32), correcting problems with previous one mentionned here ([KB5029919](https://support.microsoft.com/en-us/topic/september-12-2023-kb5029919-cumulative-update-for-net-framework-3-5-and-4-8-1-for-windows-10-version-21h2-and-windows-10-version-22h2-c483a458-3d08-47b4-b8ed-a01f7861d978)).

After installing this one and reboot, everything works fine. Hope the problem was on microsoft side!

**Comment by marcelog09** [comment]
I have a similar problem, everything worked fine until I restarted the computer. Now nothing I do in the program has any effect and the processor FAN is shown as 20.7 RPM.

![image](https://github.com/Rem0o/FanControl.Releases/assets/55034630/6053dc3e-3ef2-46e3-a3f6-234a9cc5e770)
