### ISSUE TITLE
An Unexpected Error occurred with Syst em.TimeoutException on Resume from standby on Windows 11 w/ NZXT Kraken Z53

### ISSUE THREAD

**Issue by notthatwillsmith** [Rem0o/FanControl.Releases#2049]
**Describe the bug**
On resume from suspend on Windows 11, I'm getting the following error in the log along with a popup that says "an unexpected error has occurred".
`9/25/2023 12:13:40 PM: System.TimeoutException: Operation timed out.
   at HidSharp.Platform.Windows.NativeMethods.OverlappedOperation(IntPtr ioHandle, IntPtr eventHandle, Int32 eventTimeout, IntPtr closeEventHandle, Boolean overlapResult, NativeOverlapped* overlapped, UInt32& bytesTransferred)
   at HidSharp.Platform.Windows.WinHidStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenV3.Update() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Controller\Nzxt\KrakenV3.cs:line 203
   at FanControl.Domain.BackendProviders.LHM.UpdateVisitor.VisitHardware(IHardware hardware)
   at LibreHardwareMonitor.Hardware.Computer.Traverse(IVisitor visitor) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 397
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Log.txt](https://www.dropbox.com/scl/fi/ogkw0n8slp8ggfgzxbh3t/log_4.txt?rlkey=9tt2wlpt10jntdbw7lu2qmze4&dl=0)

**Relevant hardware specs and setup**
This is an ASUS ROG Apex Maximus Z790 board with a 13900k in it. It's running FanControl V170 on 64-bit Windows 11 22H2 22621.2283. The device that seems to be affected is a Kraken Z53 using the built-in support. Using the liquidctrl plugin doesn't throw this error. It's worth mentioning that the sensor remains active after the error.

**Comment by Rem0o** [comment]
Spotted the issue.  Timeoutexception should be ignored.  Will fix next version.

**Comment by notthatwillsmith** [comment]
Thanks!

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V171
