### ISSUE TITLE
Fan Control Wont Start

### ISSUE THREAD

**Issue by bella0512** [Rem0o/FanControl.Releases#2088]
Fan control works the first time i open it but once I close it it no longer wants to start when I click on it, I’ve tried reinstalling the program and windows but it still refuses to launch more than once

**Comment by munkien** [comment]
Same issue.
Went back to 171, did not work.
On 170, I got the following log output - hope it helps?

2023-10-16 00:31:35: System.IO.FileLoadException: The file or assembly 'GrpcDotNetNamedPipes, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a01056665c7647b7' or one of its dependencies could not be loaded. A specific file could not be found or loaded. (Exception from HRESULT: 0x80131621)
Filename: 'GrpcDotNetNamedPipes, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a01056665c7647b7'
    at FanControl.IPC.IPCFactory.StartServer(FanControlRPCBase service, SensorsRPCBase sensorsService)
    at FanControl.App.<OnStartup>d__12.MoveNext()
