### ISSUE TITLE
Persistent Logging

### ISSUE THREAD

**Issue by BrendanMan3** [Rem0o/FanControl.Releases#2093]
Is there a way to disable logging so I don't always get the popup saying that the files have grown to over 3 copies? Thanks

**Comment by Rem0o** [comment]
What's being logged continuously?

**Comment by BrendanMan3** [comment]
I constantly receive messages at startup telling me that files have grown to over 3,4,5,etc and they should be removed. Is there a way to turn logging on and off so that I am not constantly clearing the logs?

**Comment by Rem0o** [comment]
@BrendanMan3 the program logs stuff for a reason. In your case it logs a lot, so there is most likely a problem. We should address that problem instead. Can you send one (latest) of the log file here?

**Comment by BrendanMan3** [comment]
[log_3.txt](https://github.com/Rem0o/FanControl.Releases/files/13120077/log_3.txt)
[log_7.txt](https://github.com/Rem0o/FanControl.Releases/files/13120079/log_7.txt)
[log_8.txt](https://github.com/Rem0o/FanControl.Releases/files/13120080/log_8.txt)
[log_7.txt](https://github.com/Rem0o/FanControl.Releases/files/13120085/log_7.txt)
Here are some of the larger logs, and most recent.

**Comment by Rem0o** [comment]
You got the CorsairLink plugin and it seems like it has a reccuring problem with a H115i device, it times out seemingly every update call.  Are you actually trying to control your H115i from Fancontrol?  If not, disable it in the Sensor source dialog in sensor settings page.

**Comment by BrendanMan3** [comment]
I am trying to control it. Its the corsair H115 CPU water cooler and radiator.

**Comment by Rem0o** [comment]
Are you running ICUE at the same time?

**Comment by BrendanMan3** [comment]
I am not, instead I use signal RGB for the lights.

**Comment by Rem0o** [comment]
It doesn't seem to be able to control it properly. You should probably ask for help on the CorsairLink plugin page and maybe disable it in the meantime.

**Comment by GF-Huang** [comment]
So, where is the logs?

<img width="1609" height="996" alt="Image" src="https://github.com/user-attachments/assets/4f8b0fa9-823f-4853-bdd9-74d693b512d0" />

**Comment by Rem0o** [comment]
<img width="300" height="537" alt="Image" src="https://github.com/user-attachments/assets/5adea09d-c005-4a98-a8ee-be4e248c003f" />

**Comment by Waghead** [comment]
!!!!
Also got this message - good. Wont tell me where to find logs but I found it out.
One of my logs is at 7,6 GiB!!!! One at 21MiB and one 34MiB. WHY?!
Please sett a limit for logs at 1MiB and make user notice that logs are BIG!

<img width="610" height="88" alt="Image" src="https://github.com/user-attachments/assets/b90ad448-5bbd-400d-8952-50346bcefd15" />

<img width="523" height="129" alt="Image" src="https://github.com/user-attachments/assets/be7a83c2-cb29-4d2d-9e96-16a9bb525bda" />

<img width="859" height="209" alt="Image" src="https://github.com/user-attachments/assets/d3a6e56d-78f1-47ad-9052-b6c74335a1a3" />


FYI my log is this message 8656848745 million times - actually two every second,
[V264] 2026-03-29 21:09:12 and
[V264] 2026-03-29 21:09:13,
[V264] 2026-03-29 21:09:14,
[V264] 2026-03-29 21:09:15 and so on..

**[V264] 2026-03-29 21:09:16: NVAPIWrapper is in failed state, requesting refresh - NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR**
-    at NvAPIWrapper.GPU.GPUCoolerInformation.get_Coolers()+MoveNext()
-    at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
-    at System.Linq.Enumerable.SelectManyIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
-    at System.Linq.Enumerable.<ToArray>g__EnumerableToArray|324_0[TSource](IEnumerable`1 source)
-    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
-    at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()

I see now that 264 fixed a logging bugg. Maybe thats why its so big?

<img width="498" height="245" alt="Image" src="https://github.com/user-attachments/assets/1ba6778c-31b9-4982-b45c-41664a0a011b" />

**Comment by Rem0o** [comment]
No your problem is that you have a constant NvAPI exception.   Disable NvAPIWrapper in your sensor sources.
