### ISSUE TITLE
Gigabyte B150M ： Computer shuts down unexpectedly.

### ISSUE THREAD

**Issue by yszza557** [Rem0o/FanControl.Releases#2122]
When using the "Pair controls and speeds automatically" feature in the client, the computer shuts down unexpectedly.

Hardware information:
System : Windows 10 Professional 64Bit Version 19045.3570 (22H2)
CPU : Intel Core i5-6500 Core Number 4Threads 4technology 14 nm
GPU : NVIDIA GeForce GTX 960 NVIDIAShaders  1024 GPU Memory  2G (GDDR5 Samsung)
Board : B150M-EVO-CF Gigabyte  Co., Ltd.Chipset Intel B150 
HardDisk : GLOWAYFER120GS3-S7Capacity112GB TypesSSDColorfulSL500256GB Capacity238GB TypesSSDSeagateST1000DM010-2EP102Capacity932GB TypesHDD
Monitor : MCVKC02HKC X3 DP  Resolution ratio 1280*800 Refresh Rate60HzSize 9.7inch Resolution ratio 1920*1080 Refresh Rate144HzSize 24inch
Memory : Team Group  DDR4-2400   (1200 MHz) 8GBTeam Group  DDR4-2400   (1200 MHz) 8GBTotal Size 16 GBChannels 2Current Frequency 2132 MHz Timing 16-16-16-392TSlot1Team Group  DDR4-2400   (1200 MHz) 8GBSlot3Team Group  DDR4-2400   (1200 MHz) 8GB

**Comment by yszza557** [comment]
I have found the log file in the directory.

2023/11/7 18:04:26: Updater service - Get latest release error:
2023/11/7 18:04:26: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at FanControl.Domain.UpdaterService.GetLatestRelease()

**Comment by Rem0o** [comment]
Some motherboard don't like when the % gets too low or stops on the CPU header, and will shutdown on the spot. I would avoid the assisted setup in your case all together, and match your fans manually.  FanControl should work just fine otherwise.

**Comment by yszza1997** [comment]
I tried changing the fan speed of the CPU, but it didn't work, the CPU controller didn't change. Can you give me a test version to test whether the CPU fan can set the speed normally?

**Comment by Rem0o** [comment]
> Can you give me a test version to test whether the CPU fan can set the speed normally?

A test version? 


If the CPU controller doesn't work, your computer might not be 100% compatible with the software.

**Comment by yszza1997** [comment]
How can I check if my computer has compatibility issues with the software?

**Comment by yszza1997** [comment]
> > Can you give me a test version to test whether the CPU fan can set the speed normally?
> 
> A test version?
> 
> If the CPU controller doesn't work, your computer might not be 100% compatible with the software.

The software is easier to operate than the BIOS, and I hope that the fan can be controlled through the software，But as soon as I use the feature, the computer loses power, and I can't find what might be causing the problem right now
