### ISSUE TITLE
FanControl shows error (System.ObjectDisposedException)

### ISSUE THREAD

**Issue by E14** [Rem0o/FanControl.Releases#2125]
**Describe the bug**

FanControl shows generic error message.

This may be connected to sleep/hibernate but I'm not completely certain, please tell me if you need additional information.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
```
12.11.2023 17:13:56: Unhandled exception in FanControl v173.0.0.0
12.11.2023 17:13:56: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ReleaseMutex(SafeWaitHandle handle)
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Nct677X.SetControl(Int32 index, Nullable`1 value)
   at LibreHardwareMonitor.Hardware.Motherboard.SuperIOHardware.<>c__DisplayClass17_1.<CreateControlSensors>b__0(Control cc)
   at LibreHardwareMonitor.Hardware.Control.set_ControlMode(ControlMode value)
   at LibreHardwareMonitor.Hardware.Control.SetSoftware(Single value)
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Relevant hardware specs and setup**
* Ryzen 5700X on MSI B550M mag mortar
* Sapphire 7800XT GPU

**Comment by Rem0o** [comment]
Is it a one time thing or it happened multiple times?

**Comment by E14** [comment]
This happened multiple times, but not regularly
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13342865/log.txt)

**Comment by IDispatcher** [comment]
Hi Rem0o, I have the same exception too, it appears after waking the PC from sleep.
My configuration is:

- R9 7900
- MSI MPG B650I EDGE WIFI
- 7900GRE

**Comment by RheologyOrbit** [comment]
I'm also experiencing this issue.  I get this error every time I resume from sleep. 

Specs:

i7-12700k
Radeon 6950xt
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/14204340/log.txt)

**Comment by E14** [comment]
FWIW, it doesn't seem to actually affect anything for me, it's just an annoying popup.

**Comment by typpos** [comment]
Same issue here when resuming from sleep.
Win 11 Pro 
MSI Z790-A wifi mobo
FanControl v186 and v188


<details title="log">
<summary>Log</summary>

```
1/05/2024 10:23:35 AM: Unhandled exception in FanControl v186.0.0.0
1/05/2024 10:23:35 AM: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ReleaseMutex(SafeWaitHandle handle)
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Nct677X.SetControl(Int32 index, Nullable`1 value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Nct677X.cs:line 411
   at LibreHardwareMonitor.Hardware.Motherboard.SuperIOHardware.<>c__DisplayClass16_1.<CreateControlSensors>b__0(Control cc) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\SuperIOHardware.cs:line 86
   at LibreHardwareMonitor.Hardware.Control.set_ControlMode(ControlMode value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Control.cs:line 60
   at LibreHardwareMonitor.Hardware.Control.SetSoftware(Single value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Control.cs:line 95
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
1/05/2024 6:36:16 PM: Unhandled exception in FanControl v186.0.0.0
1/05/2024 6:36:16 PM: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ReleaseMutex(SafeWaitHandle handle)
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Nct677X.SetControl(Int32 index, Nullable`1 value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Nct677X.cs:line 411
   at LibreHardwareMonitor.Hardware.Motherboard.SuperIOHardware.<>c__DisplayClass16_1.<CreateControlSensors>b__0(Control cc) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\SuperIOHardware.cs:line 86
   at LibreHardwareMonitor.Hardware.Control.set_ControlMode(ControlMode value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Control.cs:line 60
   at LibreHardwareMonitor.Hardware.Control.SetSoftware(Single value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Control.cs:line 95
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5/05/2024 11:16:25 AM: Unhandled exception in FanControl v188.0.0.0
5/05/2024 11:16:25 AM: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ReleaseMutex(SafeWaitHandle handle)
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Nct677X.SetControl(Int32 index, Nullable`1 value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Nct677X.cs:line 411
   at LibreHardwareMonitor.Hardware.Motherboard.SuperIOHardware.<>c__DisplayClass16_1.<CreateControlSensors>b__1(Control cc) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\SuperIOHardware.cs:line 96
   at LibreHardwareMonitor.Hardware.Control.set_SoftwareValue(Single value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Control.cs:line 82
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

</details>
