### ISSUE TITLE
No Funs detected on Asus ProArt Studiobook laptop

### ISSUE THREAD

**Issue by okarpov** [Rem0o/FanControl.Releases#2141]
No Funs detected on Asus ProArt Studiobook laptop

11/22/2023 2:17:52 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   at NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__19`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\NVApiWrapper\NVApiWrapperBackendProvider.cs:line 49

**Comment by Rem0o** [comment]
Laptops are not supported.
