### ISSUE TITLE
Fancontrol crashed after update

### ISSUE THREAD

**Issue by wonderbug2020** [Rem0o/FanControl.Releases#2217]
**Describe the bug**
This morning I started up my computer and was asked if I'd like to update fancontroller, which I did, and then it said an unexpected error occurred and to check the logs. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[1/1/2024 9:15:16 AM: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
1/1/2024 9:15:19 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
1/1/2024 10:48:05 AM: IPC Error: 
1/1/2024 10:48:05 AM: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrpcDotNetNamedPipes.Internal.MessageReader`1.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrpcDotNetNamedPipes.Internal.MessageReader`1.<>c__DisplayClass9_0.<<ReadNextMessage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<CheckForOtherInstance>d__14.MoveNext()
1/1/2024 10:48:07 AM: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
1/1/2024 10:48:10 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
1/1/2024 10:52:01 AM: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
1/1/2024 10:52:06 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
1/1/2024 11:00:42 AM: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
1/1/2024 11:00:51 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)]

**Relevant hardware specs and setup**
Custom built (though I haven't had an issue before today) 3080 GPU, 13700k CPU

**Comment by Rem0o** [comment]
Send your json configuration file.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V177
