### ISSUE TITLE
An unexpected error occured. 

### ISSUE THREAD

**Issue by JoPed** [Rem0o/FanControl.Releases#2222]
**Describe the bug**
For the last couple of days, I have had problems starting FanControl as an error message pops up on start and then forces the program to close. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
30/12/2023 10.18.46: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
30/12/2023 13.40.00: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
30/12/2023 18.06.48: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
30/12/2023 18.06.56: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
31/12/2023 10.22.22: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
31/12/2023 10.22.38: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
01/01/2024 12.33.06: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
01/01/2024 12.35.13: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
02/01/2024 19.04.11: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
02/01/2024 19.51.25: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
02/01/2024 19.55.21: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
02/01/2024 19.57.54: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
02/01/2024 20.02.30: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
02/01/2024 20.06.20: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)

**Relevant hardware specs and setup**
Windows 10  version 22H2 - desktop
AMD Ryzen 9 5900X CPU 
NVIDIA GeForce RTX 2080 driver 546.23
16 GB ram

**Comment by Rem0o** [comment]
Mind sharing your json config file?

**Comment by JoPed** [comment]
Not at all. 
[userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/13829825/userConfig.json)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V177

**Comment by JoPed** [comment]
Thank you for your help. I can now use FanControl again.
