### ISSUE TITLE
An Unexpected Error Occurred after update to V176

### ISSUE THREAD

**Issue by cmknrb** [Rem0o/FanControl.Releases#2225]
**Describe the bug**
I just updated Fan Control to V176 and am now getting errors I haven't had before.  First I see this error:
![image](https://github.com/Rem0o/FanControl.Releases/assets/155580556/a59747f5-bac4-4d5b-b759-d16459a93ec4)

And after about 20 seconds or so I get this message:
![image](https://github.com/Rem0o/FanControl.Releases/assets/155580556/ac9280d9-94f3-4e0b-b55e-2a628d020e03)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13822823/log.txt)

**Relevant hardware specs and setup**
Windows 10 Pro 22H2
AMD Ryzen 9 5900X 12-Core Processor 3.7 GHz
AMD Radeon RX 6700 XT
32 GB Ram

**Comment by stormbeta** [comment]
Just updated to v176 and ran into this same issue, never had a problem before.

Log output:

```
1/3/2024 21:01:19: System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at FanControl.Domain.ApplicationState.<>c__DisplayClass32_0`1.<SubscribeToCurrentConfig>g__subscription|0(Dictionary`2 state)
   at FanControl.Domain.ApplicationState.SubscribeToCurrentConfig[T](String key, Action`1 action)
   at FanControl.Domain.ApplicationStateMigrationService..ctor(IApplicationState state, IUpdaterService updaterService, ILogger logger)
   at FanControl.App.<OnStartup>d__13.MoveNext()
1/3/2024 21:01:20: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
```

Windows 11 22H2

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V177
