### ISSUE TITLE
AIO Cooler Fans stuck at max speeds unintentionally

### ISSUE THREAD

**Issue by nigiriemoji** [Rem0o/FanControl.Releases#2255]
**Describe the bug**
I have an Arctic Liquid Freezer II 360 AIO CPU Cooler and the 3 fans are connected to my mobo via 1 4 pin PWM fan connector, so appears as 1 fan in the FanControl app. For some reason the fans keep running at its max 1800RPM speed even tho the CPU fan curve is saying 20-30% usually. 1800RPM is definitely 100% and 20% is prob a few hundred RPM. I tried manual control, didn't work. I tried force apply, also didn't work. Fans still run at max speed. My other fans are running perfectly, it's just my AIO cooler fans maxing out for no reason
![image](https://github.com/Rem0o/FanControl.Releases/assets/53108354/e2a76b70-da78-402d-a72d-0f0726237fe8)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Everything since November:
```
11/14/2023 10:49:04 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
11/14/2023 10:49:04 AM: NvAPI failed. A complete refresh is required.
11/19/2023 10:52:59 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
11/19/2023 10:52:59 AM: NvAPI failed. A complete refresh is required.
12/4/2023 10:44:38 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\NVApiWrapper\NVApiTempSensor.cs:line 48
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\NVApiWrapper\NVApiWrapperBackendProvider.cs:line 125
12/4/2023 10:44:38 AM: NvAPI failed. A complete refresh is required.
12/12/2023 10:45:44 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\NVApiWrapper\NVApiTempSensor.cs:line 48
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update() in C:\Users\Remi\source\repos\FanControl\FanControl.Library\Domain\BackendProviders\NVApiWrapper\NVApiWrapperBackendProvider.cs:line 125
12/12/2023 10:45:44 AM: NvAPI failed. A complete refresh is required.
1/17/2024 11:58:55 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
1/17/2024 11:58:55 AM: NvAPI failed. A complete refresh is required.
```
**Relevant hardware specs and setup**
Arctic Liquid Freezer II 360 AIO CPU Cooler
Mobo = MSI PRO Z690-A WIFI DDR4
FanControl V177
![image](https://github.com/Rem0o/FanControl.Releases/assets/53108354/649b1e6d-a536-41b3-bba8-99faf9cd2bdd)
Additional data when I pressed the copy button from that screenshot right above:
```
Sensors

|
+- MSI PRO Z690-A WIFI DDR4(MS-7D25) (/motherboard)
|  |
|  +- Nuvoton NCT6687D (/lpc/nct6687d/0)
|  |  +- +12V           :   12.096   12.048    12.12 (/lpc/nct6687d/0/voltage/0)
|  |  +- +5V            :     5.02        5     5.02 (/lpc/nct6687d/0/voltage/1)
|  |  +- Vcore          :    1.188    1.164    1.246 (/lpc/nct6687d/0/voltage/2)
|  |  +- Voltage #1     :      1.2    1.184    1.254 (/lpc/nct6687d/0/voltage/3)
|  |  +- DIMM           :    1.356    1.352     1.36 (/lpc/nct6687d/0/voltage/4)
|  |  +- CPU I/O        :    0.822     0.82    0.822 (/lpc/nct6687d/0/voltage/5)
|  |  +- CPU SA         :    0.908    0.906     0.91 (/lpc/nct6687d/0/voltage/6)
|  |  +- Voltage #2     :    1.514    1.512    1.516 (/lpc/nct6687d/0/voltage/7)
|  |  +- AVCC3          :    3.304    3.296    3.308 (/lpc/nct6687d/0/voltage/8)
|  |  +- VTT            :    1.062     1.06    1.064 (/lpc/nct6687d/0/voltage/9)
|  |  +- VRef           :    1.844    1.844    1.848 (/lpc/nct6687d/0/voltage/10)
|  |  +- VSB            :    3.332    3.324    3.332 (/lpc/nct6687d/0/voltage/11)
|  |  +- AVSB           :    3.328    3.324    3.332 (/lpc/nct6687d/0/voltage/12)
|  |  +- VBat           :    3.152    3.148    3.156 (/lpc/nct6687d/0/voltage/13)
|  |  +- CPU            :     35.5     23.5     45.5 (/lpc/nct6687d/0/temperature/0)
|  |  +- System         :       34       25     34.5 (/lpc/nct6687d/0/temperature/1)
|  |  +- VRM MOS        :     34.5       22     34.5 (/lpc/nct6687d/0/temperature/2)
|  |  +- PCH            :       42       28       43 (/lpc/nct6687d/0/temperature/3)
|  |  +- CPU Socket     :       30     22.5       30 (/lpc/nct6687d/0/temperature/4)
|  |  +- PCIe x1        :       36       36       36 (/lpc/nct6687d/0/temperature/5)
|  |  +- M2_1           :       31       31     31.5 (/lpc/nct6687d/0/temperature/6)
|  |  +- CPU Fan        :        0        0        0 (/lpc/nct6687d/0/fan/0)
|  |  +- Pump Fan       :     1785     1754     1818 (/lpc/nct6687d/0/fan/1)
|  |  +- System Fan #1  :        0        0        0 (/lpc/nct6687d/0/fan/2)
|  |  +- System Fan #2  :      827      642     1086 (/lpc/nct6687d/0/fan/3)
|  |  +- System Fan #3  :      834      661     1122 (/lpc/nct6687d/0/fan/4)
|  |  +- System Fan #4  :        0        0        0 (/lpc/nct6687d/0/fan/5)
|  |  +- System Fan #5  :        0        0        0 (/lpc/nct6687d/0/fan/6)
|  |  +- System Fan #6  :      827      622     1088 (/lpc/nct6687d/0/fan/7)
|  |  +- CPU Fan        :       31       25       48 (/lpc/nct6687d/0/control/0)
|  |  +- Pump Fan       :       20       20       95 (/lpc/nct6687d/0/control/1)
|  |  +- System Fan #1  :       31       25       48 (/lpc/nct6687d/0/control/2)
|  |  +- System Fan #2  :       36       30       53 (/lpc/nct6687d/0/control/3)
|  |  +- System Fan #3  :       36       30       53 (/lpc/nct6687d/0/control/4)
|  |  +- System Fan #4  :       60       60       60 (/lpc/nct6687d/0/control/5)
|  |  +- System Fan #5  :       60       60       60 (/lpc/nct6687d/0/control/6)
|  |  +- System Fan #6  :       36       30       53 (/lpc/nct6687d/0/control/7)
```

**Comment by Rem0o** [comment]
It's the PUMP header right?  Sometimes those headers are trickier and have various restrictions that disallow them to be controlled properly.  I would try and split the fans and the pump onto 2 different headers if possible.

**Comment by nigiriemoji** [comment]
I will try this when I have a chance on the weekend, appreciate the suggestion! I got at least 3 other open normal system fan 4pin slots on the mobo :D

**Comment by nigiriemoji** [comment]
I moved to System Fan #1 and no issue! Thank you again
