### ISSUE TITLE
Unable to load old configurations after v178 update

### ISSUE THREAD

**Issue by Bront20** [Rem0o/FanControl.Releases#2256]
**Describe the bug**
When loading any of my old configurations, the load screen just continues on with no end till I cancel it, and then I get an error.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
1/18/2024 6:43:02 PM: Unhandled exception in FanControl v178.0.0.0
1/18/2024 6:43:02 PM: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at FanControl.MainWindow.WindowSettings_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at FanControl.MVVM.ViewModel.SetProperty[T](T& property, T value, String memberName)
   at FanControl.ViewModels.MainWindowViewModel.SetWindowTitle(String fileName)
   at FanControl.ViewModels.MainWindowViewModel.ApplicationContext_CurrentApplicationStateFileNameChanged(String newFileName)
   at System.Action`1.Invoke(T obj)
   at FanControl.Domain.ApplicationState.LoadApplicationState(String fileName)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Commands.LoadCommand.<>c__DisplayClass4_0.<<Execute>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass13_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

This happens with all my configurations from previous versions.  It loaded an old one using the userConf.json to start, and if I shut it down and start it back up, it says it's on the last one I tried to load, but it is not accurate., but I can't even load that after.  

The only one I can load is the one I saved since moving to v178, and it looks like I lost several tweaks because it overwrote it by saying I had made changes and it needed to save the changes and I clicked save on accident.

**Comment by Rem0o** [comment]
Fixed as soon as I could. Your configs are not broken.  Update to v179 it contains only the fix for the bug mentioned here.  

Sorry for the inconvenience, it somehow slipped by.

**Comment by Bront20** [comment]
Awesome, thanks for the quick fix! Working now.

**Comment by ATECoder** [comment]
1.79 fails reading configuration from 1.76.  1.53 works.

**Comment by Rem0o** [comment]
@ATECoder  fail how? Any logs?

**Comment by ATECoder** [comment]
> @ATECoder fail how? Any logs?

After seeing the failure, I copied 176_userConfig.json (attached) to the configuration folder and started the program. FanControl opens with some unknown (default?) configuration and the json file gets overiden (see attached). 

Where can I find the logs?

[userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/14017163/userConfig.json)
[V176_userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/14017164/V176_userConfig.json)

**Comment by Rem0o** [comment]
Logs would be "log.txt" next to the fancontrol exe.

If your config got migrated, there will be a backup in a "backups" folder in the configuration folder.

**Comment by ATECoder** [comment]
indeed, I used the config from the 1.79 backup with the 1.53 version.  

I attached the log. 

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/14026867/log.txt)

**Comment by ATECoder** [comment]
rev 180 fixes this issue. thank you.
