### ISSUE TITLE
After v179 update lost all motherboard & cpu sensors / controls

### ISSUE THREAD

**Issue by Gl4nza** [Rem0o/FanControl.Releases#2260]
Hi, after allowing fan control to update to v179 today it no longer detects any of my motherboard sensors and is missing around 8 fans that I had setup.

My motherboard is Asrock X670e Taichi and CPU is AMD 7950X3D, worked perfectly for the last 2 months across various version updates,

Screenshot of the main screen and sensors.

![Screenshot 2024-01-19 174557](https://github.com/Rem0o/FanControl.Releases/assets/43491414/afa691a6-5e02-4d78-842f-9746cd4eaf0b)
![Screenshot 2024-01-19 174608](https://github.com/Rem0o/FanControl.Releases/assets/43491414/3c56197b-dd7e-4680-bf5f-52ea2c747915)

Checking error log gives:

> 19/01/2024 17:41:32: Unhandled exception in FanControl v179.0.0.0
> 19/01/2024 17:41:32: System.Runtime.InteropServices.COMException (0x80070006): The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
>    at FanControl.ViewModels.Utilities.DwmApi.DwmSetWindowAttribute(IntPtr hwnd, DWMWINDOWATTRIBUTE dwAttribute, UInt32& pvAttribute, UInt32 cbAttribute)
>    at FanControl.ViewModels.Utilities.DwmApi.SetTitleBarForegroundColor(Window window, UInt32 colorHex)
>    at FanControl.MainWindow.<SetTitleBarColor>b__9_0()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Gl4nza** [comment]
Librehardwaremonitor report from inside fancontrol v179:

[librehardwaremonitor report.txt](https://github.com/Rem0o/FanControl.Releases/files/13992847/librehardwaremonitor.report.txt)

**Comment by Rem0o** [comment]
The LibreHardwareMonitor report doesn't list any fans, so the problem lies somewhere with LHM. 

Mind sharing your json config?

**Comment by Gl4nza** [comment]
[userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/13994636/userConfig.json)

This should be the one I was using (if it's missing data I did reinstall) I've tried setting up a new config (test) and still get the same error.

[test.json](https://github.com/Rem0o/FanControl.Releases/files/13994647/test.json)

**Comment by Rem0o** [comment]
if you downgrade to V178, do you get your fans back?

**Comment by Gl4nza** [comment]
> if you downgrade to V178, do you get your fans back?

Sadly not, tried V177 and V176 too.

**Comment by Rem0o** [comment]
Well what version did you use last which worked at all?

**Comment by Gl4nza** [comment]
> Well what version did you use last which worked at all? Or no version work now?
> 
> Did you upgrade your BIOS/drivers or anything similar? Windows update?

V178, it was fine yesterday, turned PC on today and updated as the popup appeared, after that it stopped. Nothing has been updated or changed from yesterday software wise. 

I've just put V177 again and this is what happens when I open it with my config

![Uploading Screenshot 2024-01-19 214227.png…]()

**Comment by Rem0o** [comment]
If the old version (V177) of the software also stopped working ,  *something* must have changed for it so stop working.

As you started/rebooted, maybe a Windows update was processed?

Check your update history if something matches the time it stopped working.

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/ae8b5543-0531-49ae-836d-747b6ca77aac)

**Comment by Gl4nza** [comment]
No updates in the last few days

![Screenshot 2024-01-19 215021](https://github.com/Rem0o/FanControl.Releases/assets/43491414/6f7f11e1-a7e3-4dd6-b204-6d09eed03660)

I've tried a 'clean setup' running fancontrol in a different folder with a no imported config and it doesn't detect all the fans when running the setup wizard

**Comment by Rem0o** [comment]
I'm running out of ideas.   The same version of the software you used before stopped working out of the blue.  
Stupid idea but, have you rebooted since?

**Comment by Rem0o** [comment]
Also, if you run https://github.com/LibreHardwareMonitor/LibreHardwareMonitor by itself, do you get fan sensors at all?

**Comment by Gl4nza** [comment]
> I'm running out of ideas. The same version of the software you used before stopped working out of the blue. Stupid idea but, have you rebooted since?

It stopped working after updating to v179, does the software only run in the fancontrol folder or has it possibly got any files in %appdata% that I might need to delete?

Rebooted several times and a bios update came out today that I've installed to see if that would get the sensors back

> Also, if you run https://github.com/LibreHardwareMonitor/LibreHardwareMonitor by itself, do you get fan sensors at all?

Yes it lists all my devices: and shows fans however I've just noticed it isn't reporting the RPM for some fans, as that is currently only showing my AIO PUMP (fan #3) and CPU header (fan#2) the other fans are plugged into fan #4 & 5.

![Screenshot 2024-01-19 215924](https://github.com/Rem0o/FanControl.Releases/assets/43491414/6c342cc1-6868-4f5b-be6b-96cf95a96a33)

**Comment by Rem0o** [comment]
Take LibrehardwareMonitorLib.dll from the LHM build you downloaded, drop that into fancontrol to replace the one it used.

Are you running FanControl as admin?

**Comment by Gl4nza** [comment]
Copied the .dll in and still the same, I've just tried running as admin too and still the same, when I quit fancontrol it comes up with an error has been added to the log which is the same as in my OP.

```
19/01/2024 22:05:39: Unhandled exception in FanControl v179.0.0.0
19/01/2024 22:05:39: System.Runtime.InteropServices.COMException (0x80070006): The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
   at FanControl.ViewModels.Utilities.DwmApi.DwmSetWindowAttribute(IntPtr hwnd, DWMWINDOWATTRIBUTE dwAttribute, UInt32& pvAttribute, UInt32 cbAttribute)
   at FanControl.ViewModels.Utilities.DwmApi.SetTitleBarForegroundColor(Window window, UInt32 colorHex)
   at FanControl.MainWindow.<SetTitleBarColor>b__9_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Rem0o** [comment]
That specific error in your logs doesn't not correlate with your lack of fans.

**Comment by Rem0o** [comment]
Another thing to try, untick NvAPIWrapper and only keep the LHM options checked.  Does a message come up?

**Comment by Gl4nza** [comment]
Unticking NvAPIWrapper gives this following error

![Screenshot 2024-01-19 222346](https://github.com/Rem0o/FanControl.Releases/assets/43491414/13042f8a-6262-4937-a7bb-6bd9909d24a9)

**Comment by Rem0o** [comment]
And does it give you a message in the log?

**Comment by Gl4nza** [comment]
> And does it give you a message in the log?

Nothing new, last error in my log is the one above https://github.com/Rem0o/FanControl.Releases/issues/2260#issuecomment-1901186533

**Comment by Gl4nza** [comment]
Fan speeds show fine in HWINFO and HWMonitor if that helps

**Comment by Rem0o** [comment]
The only time I saw something like this was because the process wasn't being run as admin.
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/3434371b-d35f-4075-a1e7-c0c51a46d604)

Added some log at LHM initialization, use that dll in the folder run FC to see what logs come up.


[FanControl.Library LHM with logs.zip](https://github.com/Rem0o/FanControl.Releases/files/13995398/FanControl.Library.LHM.with.logs.zip)

**Comment by Gl4nza** [comment]
When I first ran it after doing above this is what it was doing, then it loaded in and still not working:

Log file:
![Screenshot 2024-01-19 230724](https://github.com/Rem0o/FanControl.Releases/assets/43491414/515e18a7-5bfa-43fe-9336-0f03984b4b02)


19/01/2024 23:07:02: The process does have administrator privilege.
19/01/2024 23:07:04: Total number of sensors 233
19/01/2024 23:07:04: Total number of fan sensors 15
```
19/01/2024 23:07:05: The process does have administrator privilege.
19/01/2024 23:07:07: Total number of sensors 233
19/01/2024 23:07:07: Total number of fan sensors 15
19/01/2024 23:07:12: The process does have administrator privilege.
19/01/2024 23:07:14: Total number of sensors 233
19/01/2024 23:07:14: Total number of fan sensors 15
19/01/2024 23:07:19: The process does have administrator privilege.
19/01/2024 23:07:21: Total number of sensors 233
19/01/2024 23:07:21: Total number of fan sensors 15
19/01/2024 23:07:26: The process does have administrator privilege.
19/01/2024 23:07:28: Total number of sensors 233
19/01/2024 23:07:28: Total number of fan sensors 15
19/01/2024 23:07:33: The process does have administrator privilege.
19/01/2024 23:07:34: Total number of sensors 233
19/01/2024 23:07:34: Total number of fan sensors 15
19/01/2024 23:07:40: The process does have administrator privilege.
19/01/2024 23:07:41: Total number of sensors 233
19/01/2024 23:07:41: Total number of fan sensors 15
```

**Comment by Rem0o** [comment]
[FanControl.zip](https://github.com/Rem0o/FanControl.Releases/files/13995466/FanControl.zip)

Trying something else, use that exe.

**Comment by Gl4nza** [comment]
Getting same thing on launch with that .exe and log file:
```

19/01/2024 23:18:06: The process does have administrator privilege.
19/01/2024 23:18:08: Total number of sensors 233
19/01/2024 23:18:08: Total number of fan sensors 15
19/01/2024 23:18:09: The process does have administrator privilege.
19/01/2024 23:18:11: Total number of sensors 233
19/01/2024 23:18:11: Total number of fan sensors 15
19/01/2024 23:18:16: The process does have administrator privilege.
19/01/2024 23:18:18: Total number of sensors 233
19/01/2024 23:18:18: Total number of fan sensors 15
19/01/2024 23:18:23: The process does have administrator privilege.
19/01/2024 23:18:24: Total number of sensors 233
19/01/2024 23:18:24: Total number of fan sensors 15
19/01/2024 23:18:29: The process does have administrator privilege.
19/01/2024 23:18:31: Total number of sensors 233
19/01/2024 23:18:31: Total number of fan sensors 15
19/01/2024 23:18:36: The process does have administrator privilege.
19/01/2024 23:18:38: Total number of sensors 233
19/01/2024 23:18:38: Total number of fan sensors 15
19/01/2024 23:18:43: The process does have administrator privilege.
19/01/2024 23:18:45: Total number of sensors 233
19/01/2024 23:18:45: Total number of fan sensors 15
```

**Comment by Rem0o** [comment]
[FanControl with init logs.zip](https://github.com/Rem0o/FanControl.Releases/files/13995502/FanControl.with.init.logs.zip)

Added numbered logs, should see all 10 in a sequence.

**Comment by Gl4nza** [comment]
Got a error on launch and won't open program

```
19/01/2024 23:29:59: The process does have administrator privilege.
19/01/2024 23:30:00: Total number of sensors 233
19/01/2024 23:30:00: Total number of fan sensors 15
19/01/2024 23:30:01: Autofac.Core.DependencyResolutionException: An exception was thrown while activating FanControl.ViewModels.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.Bootstrap.<Startup>d__15.MoveNext()
19/01/2024 23:30:01: Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
19/01/2024 23:30:01: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
19/01/2024 23:30:08: The process does have administrator privilege.
19/01/2024 23:30:09: Total number of sensors 233
19/01/2024 23:30:09: Total number of fan sensors 15
19/01/2024 23:30:10: Autofac.Core.DependencyResolutionException: An exception was thrown while activating FanControl.ViewModels.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.Bootstrap.<Startup>d__15.MoveNext()
19/01/2024 23:30:10: Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
19/01/2024 23:30:10: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
```

**Comment by Rem0o** [comment]
[FanControl with init logs.zip](https://github.com/Rem0o/FanControl.Releases/files/13995525/FanControl.with.init.logs.zip)
Trying again.... Doing my best live debugging ain't easy.

**Comment by Gl4nza** [comment]
Appreciate it, going above and beyond with the help. That one launches, still no fans, log:

```
19/01/2024 23:37:58: The process does have administrator privilege.
19/01/2024 23:38:00: Total number of sensors 233
19/01/2024 23:38:00: Total number of fan sensors 15
19/01/2024 23:38:00: Init logs 0/10: Initializing view model...
19/01/2024 23:38:00: Init logs 1/10: Commands created
19/01/2024 23:38:00: Init logs 2/10: Available fan curves created
19/01/2024 23:38:00: Init logs 3/10: Window settings set
19/01/2024 23:38:00: Init logs 4/10: App title set
19/01/2024 23:38:00: Init logs 5/10: Loading sensors into view...
19/01/2024 23:38:00: Init logs 6/10: Sensors available: 238 sensors.
19/01/2024 23:38:00: Init logs 7/10: Sensors loaded
19/01/2024 23:38:00: Init logs 8/10: Number of controls loaded onto the UI: 17
19/01/2024 23:38:00: Init logs 9/10: Restoring from user config...
19/01/2024 23:38:00: Init logs 10/10: User config restored
19/01/2024 23:38:01: The process does have administrator privilege.
19/01/2024 23:38:03: Total number of sensors 233
19/01/2024 23:38:03: Total number of fan sensors 15
19/01/2024 23:38:08: The process does have administrator privilege.
19/01/2024 23:38:10: Total number of sensors 233
19/01/2024 23:38:10: Total number of fan sensors 15
19/01/2024 23:38:15: The process does have administrator privilege.
19/01/2024 23:38:16: Total number of sensors 233
19/01/2024 23:38:16: Total number of fan sensors 15
19/01/2024 23:38:22: The process does have administrator privilege.
19/01/2024 23:38:23: Total number of sensors 233
19/01/2024 23:38:23: Total number of fan sensors 15
19/01/2024 23:38:28: The process does have administrator privilege.
19/01/2024 23:38:30: Total number of sensors 233
19/01/2024 23:38:30: Total number of fan sensors 15
19/01/2024 23:38:35: The process does have administrator privilege.
19/01/2024 23:38:37: Total number of sensors 233
19/01/2024 23:38:37: Total number of fan sensors 15
```

**Comment by Rem0o** [comment]
Wait... click the top right eye, and unhide everything.

**Comment by Gl4nza** [comment]
![Screenshot 2024-01-19 234409](https://github.com/Rem0o/FanControl.Releases/assets/43491414/9a7d951d-d67d-4545-beb2-34c5458184ba)

**Comment by Rem0o** [comment]
Well well well, what do we got here 
![FacepalmReallyGIF](https://github.com/Rem0o/FanControl.Releases/assets/14118956/5cae366f-e449-44a5-9851-94b2ee243d33)

**Comment by Gl4nza** [comment]
I can guess what your thinking with that gif, Before your test versions the RPM for some of the fans was at 0, only 2 were showing rpm.

**Comment by Rem0o** [comment]
> I can guess what your thinking with that gif

No hard feelings or anything by the way, just blaming myself for not check that first.   Can you confirm that with "original V179", with everything unhidden, you don't get any sensors?

**Comment by Gl4nza** [comment]
No hard feelings, I appreciate your help, not often you'd get the dev this involved for 1 persons problem.

This is a fresh download of v179 with my config, opened up without error and is showing all but 1 of my fans RPM is showing 0 rpm and not spinning up currently, all others are spinning up and down as I adjust them in fancontrol

![Screenshot 2024-01-19 235620](https://github.com/Rem0o/FanControl.Releases/assets/43491414/256b0923-3ebc-41e3-b3b8-fbc2ee88028f)

**Comment by Rem0o** [comment]
So that matches exactly what you got with LHM?

**Comment by Gl4nza** [comment]
Libre is missing more fan RPM than fancontrol is, it's missing any fans that are plugged into my chassis headers (3 fans) HWINFO is showing all the fans correctly on the chassis headers

![Screenshot 2024-01-20 000832](https://github.com/Rem0o/FanControl.Releases/assets/43491414/8b75a1a3-0608-4ea5-828e-fd5b1d0cfa9b)

**Comment by Gl4nza** [comment]
Changed nothing and turned PC back on this morning and it's working again, detecting all fan RPM and controlling as it used too.

Sorry for wasting your time trying to get this fixed
