### ISSUE TITLE
Unexpected error dialog prevents access to UI Illegal operation attempted on a registry key that has been marked for deletion.

### ISSUE THREAD

**Issue by dj69** [Rem0o/FanControl.Releases#2278]
**Describe the bug**
I'm getting the "An unexpected error has occured[sic] and has been added to the log file.  Spamming the enter key or escape key just keeps popping up the dialog.  The message is not helpful, nor does it tell me where to find the log gile.  The message that log files are too big is also not helpful if it doesn't tell me where they are.  Also (see [sic] above, there's a typo in this recurring dialog box.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]
Last repeating entry in the log file:
1/29/2024 5:08:49 PM: Unhandled exception in FanControl v179.0.0.0
1/29/2024 5:08:49 PM: System.IO.IOException: Illegal operation attempted on a registry key that has been marked for deletion.

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalValueCount()
   at FanControl.HWInfo.HWInfoRegistry.UpdateValues(HWInfoPluginSensor[] sensors)
   at FanControl.HWInfo.HWInfoPlugin.Update()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[log_4.txt](https://github.com/Rem0o/FanControl.Releases/files/14090682/log_4.txt)

**Relevant hardware specs and setup**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DAVID-PC3
System Manufacturer	System manufacturer
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	AMD Ryzen 9 3900XT 12-Core Processor, 4000 Mhz, 12 Core(s), 24 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 3603, 3/20/2021
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	TUF GAMING X570-PLUS (WI-FI)
BaseBoard Version	Rev X.0x
Platform Role	Desktop

**Comment by dj69** [comment]
The repeating dialog prevents me from even closing fan control without using task manager and fan control just fails to initialize or repeats this error dialog every time.  Sometimes it comes up and tells me sensors are missing from HWInfo for the ASUS TUF components but they're visible and reporting in HWInfo but then the contents of that dialog are NOT logged and I can't copy them.  Really frustrating.

**Comment by Rem0o** [comment]
Hi,

Thanks for the "occured" => "occurred" typo, fixed it.   

Now as for your problem, it seems like your config relies on a HWInfo sensor that is constantly missing from being reported into the registry.   I can't find back the reference, but I remember that a newly released version of HwInfo, might be the current beta version, changed the way it handles the DIMM reporting, basically leaving no "hole" in the registry if it doesn't update the temperature.

**Comment by Fr0stX76** [comment]
Correct on the beta of HWinfo, just install the latest.

Now as of why this is happening... Either a temp sensor fluke on the memory modules or an SMBus communication failure. Most memory modules use the SMBus to transmit data (temp reading in this case). Hwinfo, FanControl and other softwares use an SMBus mutex to share this communication "channel". If you have a software that uses that bus without a the mutex, then you will loose communication randomly with any software trying to access it. Biggest offenders are manufacturer RGB softwares like Icue, NZXT CAM, etc... 3rd party RGB sofware like OpenRGB and SignalRGB have an option for this. Some monitoring tools might also be offenders.

**Comment by dj69** [comment]
HWiNFO64 v7.68-5300.  Clicking Check for Updates doesn't seem to do anything but I'm downloading 7.72 now.  My bigger issue is that the "Unexpected error" modal dialog, when it gets into a loop, prevents me from just closing fan control so I can fix the sensor tools it's relying on.

**Comment by dj69** [comment]
Maybe you could add a third option "Exit Fan Control"?
