### ISSUE TITLE
unexpected error has occured from hwinfo ram temp sensor

### ISSUE THREAD

**Issue by TMavica** [Rem0o/FanControl.Releases#2293]
LOG:

5/2/2024 10:13:12: Unhandled exception in FanControl v180.0.0.0
5/2/2024 10:13:12: System.Exception: HWInfo was closed during operation.
   at FanControl.HWInfo.HWInfoPlugin.Update() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 83
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location ---
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Rem0o** [comment]
Are you running the latest BETA version of HwInfo?  RAM were fixed in the latest version.

**Comment by TMavica** [comment]
> Are you running the latest BETA version of HwInfo? RAM were fixed in the latest version.

no. I using HWINFO 7.68-5300, thats not beta
so beta is fixed??

**Comment by Rem0o** [comment]
Seen report of 2-3 different people with the same issue of disappearing RAM temp in the registry, fixed with the latest beta.

**Comment by TMavica** [comment]
> Seen report of 2-3 different people with the same issue of disappearing RAM temp in the registry, fixed with the latest beta.

Seem update latest hwinfo fixed. Thanks
