### ISSUE TITLE
Please allow interaction with the app even when there is an "unexpected error"

### ISSUE THREAD

**Issue by DKogut17** [Rem0o/FanControl.Releases#2357]
**Describe the bug**
Please allow me to select literally anything around this window or supress it. It is constantly looping since I updated and I can't even open the log because of it.

![image](https://github.com/Rem0o/FanControl.Releases/assets/47827904/4e93556b-cef8-4668-9e03-14f6f8e1a8d3)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Yes. This is looping on v182, trying to revert because v181 was fine:

`3/14/2024 9:20:27 AM: Unhandled exception in FanControl v182.0.0.0
3/14/2024 9:20:27 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.FlatFanCurveViewModel.GetCommand()
   at FanControl.Domain.Control.TryGetFanCurveCommand(Single& command)
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
3/14/2024 9:20:28 AM: Unhandled exception in FanControl v182.0.0.0
3/14/2024 9:20:28 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ViewModels.FlatFanCurveViewModel.GetCommand()
   at FanControl.Domain.Control.TryGetFanCurveCommand(Single& command)
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Relevant hardware specs and setup**
Not relevant

**Comment by Rem0o** [comment]
Pushed V183
