### ISSUE TITLE
Fan Control update v183 unable to detect sensors

### ISSUE THREAD

**Issue by Etrinque** [Rem0o/FanControl.Releases#2361]
**Describe the bug**
updated fan control portable to v183. prior version was working fine.
update flagged error failure to load sensors 29 found /30 expected
no sensors matched with fans that were matched prior.
reload config. same result. no matched fans.
automatic paring option fails with a no sensors detected error. 

reload also fails in the same fashion.

**Comment by Etrinque** [comment]
logs mention nothing.
3/1/2024 8:06:39 AM: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.UpdaterService.<GetUpdateVersionInfo>d__24.MoveNext()
3/1/2024 8:06:39 AM: System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
3/1/2024 8:06:39 AM: System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

removed and installed prior version. unfortunately lost my config in the process. reinstalled new version.   was able to auto assign and auto config but setings did not persist through pc sleep cycle.

will update further

**Comment by Etrinque** [comment]
![Screenshot 2024-03-14 145808](https://github.com/Rem0o/FanControl.Releases/assets/143452184/35fc56dc-c5c1-4765-98ee-b9fb6627f5bf)
![Screenshot 2024-03-14 150036](https://github.com/Rem0o/FanControl.Releases/assets/143452184/5bd00a7c-ec04-4854-bcc5-789a794137e9)

**Comment by ECHOSUD** [comment]
With v183 this is my error log (I exited and reopened multiple times)
<details><summary>Log</summary>
<pre>
15/03/2024 10:17:53 AM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.Refresh()
   at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.MainWindowViewModel.<>c__DisplayClass140_0.<<RestoreApplicationState>b__10>d.MoveNext()
15/03/2024 10:19:32 AM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
15/03/2024 10:19:32 AM: Initialization failed.
15/03/2024 10:22:05 AM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
15/03/2024 10:22:05 AM: Initialization failed.
</pre>
</details>

**Comment by Rem0o** [comment]
@Etrinque  can you send the json file of your prior config? Might be in the backup folder within the configuration folder.

**Comment by RoyaIFlush** [comment]
I'm having the same issue, "no speed sensors". Reinstalling and reloading old configs and older versions (181 etc) do not fix the issue. 
Now it won't even recognize my fans at all. I'm attaching my old userconfig file.
[userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/14623598/userConfig.json)

**Comment by WantStuff** [comment]
Same issue for me (see #2366, not fixed)

**Comment by AndyNewy** [comment]
Same problem for me....On a windows 11 based machine. But on a windows 10 machine the V183 update worked just fine..... There was another update yesterday (I think) but didn't cure the issue. Should I delete and reinstall Fan Control????
