### ISSUE TITLE
Exception during assisted setup

### ISSUE THREAD

**Issue by hanchiang** [Rem0o/FanControl.Releases#2395]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]
Exception occurred during assisted setup

**Is there a log.txt file next to FanControl.exe with recent date entries?**
`
22/3/2024 3:41:16 pm: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at FanControl.ViewModels.Utilities.FanCalibrationUtility.<GetMaxValue>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanCalibrationUtility.<Run>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtility`1.<Run>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.AssistedSetup.<FanCalibrationUtility>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.AssistedSetup.<RunAutomaticTests>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass13_0`1.<<ProgressDialog>b__0>d.MoveNext()`

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]
Windows 10, AMD ryzen 7700, NVIDIA RTX 4070 Ti super

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2380.

Will be fixed next release.

**Comment by Unwrapped3** [comment]
> Duplicate of #2380.
> 
> Will be fixed next release.

Thank you for the quick reply! My case fans (corsair pwm connected via hub to fam_1 on mobo) are also not getting identified. Is it the same issue or something else? Mobo is Gigabyte Aorus b650 elite ax. Thanks!
