### ISSUE TITLE
Initialization started to fail

### ISSUE THREAD

**Issue by vlado48** [Rem0o/FanControl.Releases#2450]
**Describe the bug**
Init started to fail. With both 186 and 185 while working for about 2 weeks without problems. No changes to system except win update afaik. Tried reinstall and system restarts - not helping.

**log**
4/9/2024 9:21:21 PM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/9/2024 9:21:21 PM: Initialization failed.
4/9/2024 9:25:41 PM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/9/2024 9:25:41 PM: Initialization failed.
4/10/2024 8:05:21 AM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/10/2024 8:05:21 AM: Initialization failed.
4/10/2024 8:44:16 PM: System.Exception: Initialization was called twice.
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
4/10/2024 8:44:16 PM: Initialization failed.

**Relevant hardware specs and setup**
Win 10 - had update approximately of time this started to show up

**Comment by Rem0o** [comment]
What plugins do you got.

**Comment by vlado48** [comment]
> What plugins do you got.

Thanks for coming back to me. I only had ADLX for detecting my AMD GPU. I also tried to disabling the plugin - still fails to initialize.

**Comment by vlado48** [comment]
update: I went ahead and deleted entire /Plugins folder. Initialization now shows different error pop-up 
![image](https://github.com/Rem0o/FanControl.Releases/assets/34378363/cbbf04d2-1427-4972-8f47-2e7920014800)

Eventually it succeeds and initiates. However automatching does not yield any results and creating new config crashes the program.

I plan to reinstall and ensure I delete all files in the folder. Let me know if you want me to perhaps share some artifacts from old, bugged installation.

**Comment by Rem0o** [comment]
That initialization is normal, you got plugins sensor in your config, and you deleted said plugin.   The ADLX plugin doesn't work properly and I believe a recent driver update from AMD broke it even more.  I don't have a ADLX compatible card myself so I can't work on the driver integration right now.  This issue though is with the ADLX plugin, not the main Fancontrol program itself.
