### ISSUE TITLE
Fan Control Won't boot

### ISSUE THREAD

**Issue by C00LT00L** [Rem0o/FanControl.Releases#2500]
![image](https://github.com/Rem0o/FanControl.Releases/assets/130194224/5417e882-f3f9-40c2-8e32-14342bca73b7)

It was working a day or two ago and then I updated it and it didn't reopen after and it gave me this warning. I reinstalled it a few times already and deleted all the old files etc. and its still giving the same error every time I try to us it. Please advise.

Thanks,
C00LT00L

**Comment by Rem0o** [comment]
Logs?

**Comment by C00LT00L** [comment]
5/7/2024 8:05:53 PM: Autofac.Core.DependencyResolutionException: An exception was thrown while activating FanControl.ViewModels.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.Bootstrap.<Startup>d__15.MoveNext()
5/7/2024 8:05:53 PM: Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
5/7/2024 8:05:53 PM: System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
5/7/2024 8:06:03 PM: Autofac.Core.DependencyResolutionException: An exception was thrown while activating FanControl.ViewModels.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.Bootstrap.<Startup>d__15.MoveNext()
5/7/2024 8:06:03 PM: Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
5/7/2024 8:06:03 PM: System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()

**Comment by C00LT00L** [comment]
It also decided to boot after it errored one time but it didn't function properly and didn't show any of the fans.

**Comment by Rem0o** [comment]
See V189

**Comment by C00LT00L** [comment]
What dos See V189 mean? How should I proceed?

**Comment by Rem0o** [comment]
Sorry should have put the link in my comments. I meant the new update, version 189 of Fan Control, should address your issue.

**Comment by C00LT00L** [comment]
Perfect thank you. It worked. I appreciate your time and assistance very much.
