### ISSUE TITLE
FanControl INDICATOR Not Working AFTER Sleep Mode

### ISSUE THREAD

**Issue by Jaferestacruz** [Rem0o/FanControl.Releases#2506]
The fan monitoring or the application stops working after the sleep mode can you fix this issue?

**Comment by Rem0o** [comment]
How exactly? This issue may be specific to you, you need to provide some details.  Does the app crashes? Does it keeps open but fails to detect sensors? etc etc....

**Comment by Jaferestacruz** [comment]
When I turn my PC to sleep mode the app is not showing on the taskbar indicator. I think the app taskbar indicator is not working I do a search in the task manager and the app is running but the indicator is not showing. People on already discussed this here. "FanControl shuts off when computer goes to sleep #1717". Thanks @Rem0o I love your work here. I am a big fan of this.

**Comment by Rem0o** [comment]
Under which user is it running? Is it a different user from your usual one?

**Comment by Jaferestacruz** [comment]
> Under which user is it running? Is it a different user from your usual one?

I use my main windows 11 account on this. let me know if there a logs to look at Im happy to help to fix this.

**Comment by ngod88** [comment]
I have this same issue. Since day 1. 

Windows 10, X570 Steel Legend, and basically every version of FanControl until V190. 

![image](https://github.com/Rem0o/FanControl.Releases/assets/36052920/622f6028-70ed-49a8-80e5-45c7b44e9d0f)

e.g. of the last bit of logs.

```
5/15/2024 3:01:35 PM: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.ReleaseMutex(SafeWaitHandle handle)
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.Nct677X.SetControl(Int32 index, Nullable`1 value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\Nct677X.cs:line 411
   at LibreHardwareMonitor.Hardware.Motherboard.SuperIOHardware.<>c__DisplayClass16_1.<CreateControlSensors>b__1(Control cc) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\SuperIOHardware.cs:line 96
   at LibreHardwareMonitor.Hardware.Control.set_SoftwareValue(Single value) in C:\Users\remme\Documents\Github\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Control.cs:line 82
   at FanControl.Domain.Control.Update()
   at FanControl.ViewModels.ControlViewModel.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by Jaferestacruz** [comment]
@Rem0o This is fixed. Thank you.
