### ISSUE TITLE
FanControl doesn't work after driver downgrade

### ISSUE THREAD

**Issue by NiteOwl-OvO** [Rem0o/FanControl.Releases#2539]
I have a new video card XFX RX6750 XT. It started green screening during long sessions in Hunt: Showdown and 7 Days to Die. I upgraded the Adrenalin software to the latest and the problem only got worse. A friend recommended FanControl. I installed it and the ADLX plugin. Configured it and it worked fine. However, after a couple of hours in Hunt I got another green screen. Temps should have been fine. They were holding around 60c measured from the hotspot. It was recommended to downgrade the Adrenalin software to a 23.x version instead of 24.5.1. I tried 23.9.3 and FanControl threw exceptions and "Initialization failed" messages. I upgraded adrenalin to 23.11.1 and got the same. ADLX reports no temp sensors found. I tried refreshing and FanControl crashes. This is what I found in the error log. I'm a c# developer, so this looks all too familiar. If I can help debug in any way let me know. 

5/30/2024 7:35:21 AM: ADLXWrapper.ADLXEception: Result: ADLX_ORPHAN_OBJECTS 
Couldn't terminate ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper.Dispose()
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Close()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Close()
   at FanControl.Domain.ComputerAccessLayer.Close()
5/30/2024 7:35:21 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Domain.FileLogger.Log(Exception exception)
   at FanControl.Domain.ComputerAccessLayer.<>c__DisplayClass11_0.<<TryRefresh>b__0>d.MoveNext()
5/30/2024 7:35:21 AM: Initialization failed.

**Comment by NiteOwl-OvO** [comment]
Update: I exited FanControl, deleted everything in the Configurations folder and the Plugins folder, then started FanControl. It did the initial setup. I went to Settings and imported the ADLX plugin. No temp sensor are detected by ADLX. I refreshed temp sensors and received a double error message: ADLX could not initialize or has no temp sensors.

![image](https://github.com/Rem0o/FanControl.Releases/assets/101232484/74b35566-8594-4764-b236-9081872c1d26)

**Comment by elminister83** [comment]
same problem
