### ISSUE TITLE
v81 crash: NVIDIAApiException: NVAPI_API_NOT_INITIALIZED

### ISSUE THREAD

**Issue by roim** [Rem0o/FanControl.Releases#258]
Hi! Thanks for FanControl, I really needed it.

Since v81 I'm getting the following crash every couple seconds. v79 works fine (and older versions too). I haven't tested v80.

```
11/10/2020 10:30:55 PM: Unhandled exception in FanControl v1.0.0.0
11/10/2020 10:30:55 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_API_NOT_INITIALIZED
   at FanControl.Models.NVApiControlSensor.a(NVIDIAApiException A_0)
   at FanControl.Models.NVApiControlSensor.Update()
   at FanControl.Domain.ComputerAccessLayer.d()
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.a(Object A_0, ElapsedEventArgs A_1)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by roim** [comment]
Actually these are older logs.
