### ISSUE TITLE
v80+ crash: Asus motherboard embedded Controller

### ISSUE THREAD

**Issue by roim** [Rem0o/FanControl.Releases#259]
Hi! Thanks for FanControl, it really helps me.

Since v81 the app is crashing every couple seconds in my machine with the following logs. v79 and older worked fine. I haven't tested v80.

```
6/12/2021 10:47:57 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Domain.ComputerAccessLayer.DeactivateNvidiaML()
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
6/12/2021 10:48:11 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Domain.ComputerAccessLayer.DeactivateNvidiaML()
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
6/12/2021 11:00:12 PM: Unhandled exception in FanControl v1.0.0.0
6/12/2021 11:00:12 PM: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Dispose(Boolean disposing)
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Finalize()
6/12/2021 11:00:18 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Domain.ComputerAccessLayer.DeactivateNvidiaML()
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
6/12/2021 11:03:15 PM: Unhandled exception in FanControl v1.0.0.0
6/12/2021 11:03:15 PM: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Dispose(Boolean disposing)
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Finalize()
6/12/2021 11:03:29 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Domain.ComputerAccessLayer.DeactivateNvidiaML()
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
6/12/2021 11:03:45 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Domain.ComputerAccessLayer.DeactivateNvidiaML()
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
6/12/2021 11:11:15 PM: Unhandled exception in FanControl v1.0.0.0
6/12/2021 11:11:15 PM: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Dispose(Boolean disposing)
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Finalize()
```

**Comment by roim** [comment]
I wouldn't mind sending a PR to fix this, but if I got it right there's no source code available?

**Comment by LioZuto** [comment]
Before updating to v81 : 

I had this exact issue (v80) and for an unknown reason; my fans weren't working at all.
I decided to update to v81 and it didn't changed anything.

Weirdly, I upgraded my CPU (Ryzen 7 3800x to Ryzen 9 5950X  on the same Motherboard (Asus Rog Strix X570-E Gaming)) last week and it was working until today.

I reverted back to V79; 
- Fans are controllable again
- The program didn't crashed at all.

Exact same error :

6/13/2021 7:49:11 PM: Unhandled exception in FanControl v1.0.0.0
6/13/2021 7:49:11 PM: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Dispose(Boolean disposing)
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Finalize()

**Comment by Rem0o** [comment]
@roim judging from the log and https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/37e917a4f848941cea429b900cd2c962d873cf99/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/EC/WindowsEmbeddedControllerIO.cs , it seems like the finalizer somehow gets called while the dispose was not. However, I can only see that object being constructed with a "using" statement, so I have no real idea how it can get into that dispose from the finalizer with "_disposedValue" == false without the dispose being called first by the "using" statement.

**Comment by BitterpantsIII** [comment]
I am having the exact same issue, here is my hardware info and log text; hopefully it can help with debugging. Love Fan Control by the way, literally the best fan control software available.
CPU: Ryzen 9 5900x
Motherboard: ROG Crossfire VIII Hero
Log.txt:
6/14/2021 10:38:00 AM: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.Domain.ComputerAccessLayer.DeactivateNvidiaML()
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
6/14/2021 10:38:03 AM: Unhandled exception in FanControl v1.0.0.0
6/14/2021 10:38:03 AM: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
   at System.Threading.Mutex.ReleaseMutex()
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Dispose(Boolean disposing)
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Finalize()

**Comment by Rem0o** [comment]
The "DeactivateNvidiaML" doesn't make the software crashes btw, it's the "Release Mutex" part of the EmbeddedController, which is the newly developed support for Asus proprietary embedded control chips on their motherboards.

**Comment by 8PercentAndroid** [comment]
Excellent product agreed. I occasionally get a crash with the same error. Specs: AMD 5900X, ASUS x570-i, msi 3090 Ventus oc

**Comment by rbernardi73** [comment]
I am experiencing the same issue, however v80 is stable for me. Upgrading to higher version throws the error and crashes.

CPU: Ryzen 5800x
Motherboard: ASUS ROG Crosshair VIII Hero

6/16/2021 8:45:36 AM: Unhandled exception in FanControl v1.0.0.0
6/16/2021 8:45:36 AM: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
at System.Threading.Mutex.ReleaseMutex()
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Dispose(Boolean disposing)
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Finalize()

**Comment by PhyxionNL** [comment]
> 
> 
> @roim judging from the log and https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/37e917a4f848941cea429b900cd2c962d873cf99/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/EC/WindowsEmbeddedControllerIO.cs , it seems like the finalizer somehow gets called while the dispose was not. However, I can only see that object being constructed with a "using" statement, so I have no real idea how it can get into that dispose from the finalizer with "_disposedValue" == false without the dispose being called first by the "using" statement.

I don't think the code here is correct: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/57140e219ba6f2e5091b20839235b9dac51847d7/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/EC/WindowsEmbeddedControllerIO.cs#L72
It should check disposing as well, otherwise it might try to release it twice. See https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/471

A DLL is built soon https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/943604201 
You can try to replace existing LHM DLL with this new one. I don't have EC sensor here (no ASUS).

**Comment by Rem0o** [comment]
can any of you Asus motherboard guys try @PhyxionNL's build of LibreHardwareMonitorLib?

@roim @rbernardi73 @8PercentAndroid @BitterpantsIII

**Comment by 8PercentAndroid** [comment]
Sure. Will give it a go and report back

**Comment by rbernardi73** [comment]
Seems to be pretty stable so far running v82 with the updated LHM DLL. Will let it run for a few hours and report back.

**Comment by PhyxionNL** [comment]
Any update @rbernardi73 @8PercentAndroid?

**Comment by 8PercentAndroid** [comment]
Haven't been home will throw it on tonight and get back to you asap. Sorry for the delay

**Comment by rbernardi73** [comment]
@PhyxionNL @Rem0o LHM DLL (net452) on v82 is still running stable. I have not gotten a crash or any logged exceptions since implementation. Monitored the fan speeds while gaming last night, and it appears to be working as intended. Let me know if you would like me to perform a specific test.

Great job figuring this out! This is the best fan controller out there!

FYI, the fan is still not being detected when set to PWM in BIOS, but I think this is an unrelated issue to the crashing.

**Comment by 8PercentAndroid** [comment]
seems stable for me too, no crashes to report thus far. will post any that i get in here (fingers crossed not)
i saw v.83 just dropped. is it worth trying that one too?

**Comment by 8PercentAndroid** [comment]
Still good this am after loads of settings changes and 100% testing. Great work
