### ISSUE TITLE
AMD Adrenaline GPU overclock settings revert when FanControl is running (with CorsairLink plugin activated)

### ISSUE THREAD

**Issue by JonBetts** [Rem0o/FanControl.Releases#2623]
I've been attempting to undervolt my GPU, and I noticed that the settings kept reverting. I narrowed it down to FanControl running, and then even further to having the CorsairLink plugin active. Has anyone seen this happen before? It's the only plugin I was using as all my case fans, my AIO pump and fans are all connected via the Commander Core XT so this plugin is pretty important!

There is a log file in the FanControl folder and I can see quite a few errors related to the plugin, most of which are similar to this:

`Type: CorsairLink.CorsairLinkDeviceException
Message: Operation canceled: The expected data type was not read within the specified time.
Source: FanControl.CorsairLink
HResult: -2146233088
Stack Trace:
   at CorsairLink.Devices.CommanderCoreDevice.SendCommand(ReadOnlySpan`1 command, ReadOnlySpan`1 data, ReadOnlySpan`1 waitForDataType)
   at CorsairLink.Devices.CommanderCoreDevice.ReadFromEndpoint(ReadOnlySpan`1 endpoint, ReadOnlySpan`1 dataType)
   at CorsairLink.Devices.CommanderCoreDevice.RefreshImpl(Boolean initialize)
   at FanControl.CorsairLink.CorsairLinkPlugin.<>c__DisplayClass41_0.<RefreshAsync>b__0()
Data:
    command: 08FC
    data: 
    waitForDataType: 1000`

Happy to send the log file if there's definitely nothing in it that identifies me, etc. I'm running the latest version on Fan Control (V196). I love the software, and cannot wait to be able to use it fully alongside AMD Adrenaline!

Thanks in advance.

**Comment by Rem0o** [comment]
Known issue: https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/16
Essentially setting anything with manualFanTuning in ADLX resets all the other tuning stuff, including Power and VRAM.

**Comment by JonBetts** [comment]
> Known issue: [GPUOpen-LibrariesAndSDKs/ADLX#16](https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/16) Essentially setting anything with manualFanTuning in ADLX resets all the other tuning stuff, including Power and VRAM.

Ah ok, thank you very much for the quick response. Not hopeful that will get fixed then, seeing as you created the issue back in April! Happy for you to close this issue if the problem lies with the ADLX plugin. Still strange that it seems ok when my GPU is controlled by FanControl and the CorsairLink plugin is disabled.

Do you know what I can do in the meantime? Just not use FanControl for my GPU, and instead use Adrenaline?c

**Comment by Rem0o** [comment]
> Do you know what I can do in the meantime? Just not use FanControl for my GPU, and instead use Adrenaline?c

Yes that works.
