### ISSUE TITLE
Error with Corsair Link H150i AIO

### ISSUE THREAD

**Issue by MimZz33** [Rem0o/FanControl.Releases#2642]
I'm currently experiencing a frustrating issue with Fan Control that occurs during system startup or when the computer wakes up. Specifically, my ICUE Link H150i AIO cooler triggers an error upon startup, causing an error window to appear. This window indicates that multiple errors have been detected and advises me to review the CorsairLink.log for more details. Additionally, I use Signal RGB in tandem with Fan Control, and I’ve noticed that my RGB settings do not function correctly on the AIO cooler until I acknowledge the error by clicking 'OK.' Once I hit 'OK' on startup, Signal RGB and Fan Control work as intended. However, when the computer wakes up from sleep mode, the AIO error reappears, disrupting the sync with Signal RGB. Unlike startup, simply clicking 'OK' doesn’t resolve the issue, as the error keeps recurring. Despite this, there seems to be no effect on the actual control of the fans; although I noticed an error message related to one of the fans, it appears to be functioning just fine. Once I restart FanControl the error does not appear and everything works fine. I will provide a log.txt below 

2024-08-02T01:08:05.4178859Z [ERR] iCUE LINK System Hub (1D294C29B847895CA3538BD68AA5AEC4): An error occurred refreshing device 'iCUE LINK System Hub (1D294C29B847895CA3538BD68AA5AEC4)' (\\?\hid#vid_1b1c&pid_0c3f&mi_00#a&c9b2c1a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})

Type: CorsairLink.CorsairLinkDeviceException
Message: Command error: An error code was returned after sending the command.
Source: FanControl.CorsairLink
HResult: -2146233088
Stack Trace:
   at CorsairLink.Devices.ICueLink.ICueLinkHubDevice.SendCommand(ReadOnlySpan`1 command, ReadOnlySpan`1 data, ReadOnlySpan`1 waitForDataType)
   at CorsairLink.Devices.ICueLink.ICueLinkHubDevice.ReadFromEndpoint(ReadOnlySpan`1 endpoint, ReadOnlySpan`1 dataType)
   at CorsairLink.Devices.ICueLink.ICueLinkHubDevice.RefreshImpl(Boolean initialize)
   at FanControl.CorsairLink.CorsairLinkPlugin.<>c__DisplayClass41_0.<RefreshAsync>b__0()
Data:
    command: 0D01
    data: 17
    waitForDataType: 

**Relevant hardware specs and setup**
- ICUE Link H150i AIO controlled by Signal RGB and FanControl

**Comment by Fr0stX76** [comment]
This is a Corsairlink issue. You should post in it's repo.

See [Here](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/178)
