### ISSUE TITLE
LibreHardware monitor could not initialize or has no sensors

### ISSUE THREAD

**Issue by xdist** [Rem0o/FanControl.Releases#2653]
**Describe the bug**
Gives me this message everytime fancontrol starts
![image](https://github.com/user-attachments/assets/2685f9cd-5ae6-46e7-8cc4-1a1403922bcf)
also, only my gpu fan is showing and my other fans are not showing anymore

it used to work fine on my pc until i reset my windows and now it just keeps giving me this error

**Is there a log.txt file next to FanControl.exe with recent date entries?**
```
8/7/2024 12:24:29 AM: Open - System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at LibreHardwareMonitor.Hardware.BiosInformation.GetDate(String date)
   at LibreHardwareMonitor.Hardware.BiosInformation..ctor(Byte[] data, IList`1 strings)
   at LibreHardwareMonitor.Hardware.SMBios..ctor()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
8/7/2024 12:24:30 AM: Open - System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at LibreHardwareMonitor.Hardware.BiosInformation.GetDate(String date)
   at LibreHardwareMonitor.Hardware.BiosInformation..ctor(Byte[] data, IList`1 strings)
   at LibreHardwareMonitor.Hardware.SMBios..ctor()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
8/7/2024 12:24:31 AM: Open - System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at LibreHardwareMonitor.Hardware.BiosInformation.GetDate(String date)
   at LibreHardwareMonitor.Hardware.BiosInformation..ctor(Byte[] data, IList`1 strings)
   at LibreHardwareMonitor.Hardware.SMBios..ctor()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
8/7/2024 12:24:31 AM: LibreHardwareMonitor could not initialize or has no sensors.
```

**Relevant hardware specs and setup**
RTX 2060
Ryzen 5 5500
Biostar B450MHP
Windows 11 Pro Build 22631

**Comment by Rem0o** [comment]
There seems to be some recent changes in LHM related to your log:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/68b4620042af7c7dfa2ee36e9ba80ad669616332

**Comment by xdist** [comment]
what should i do to fix it then

**Comment by Rem0o** [comment]
Best would be to figure out what string it is trying to parse as a date, either through live debugging or with added logs. In any case it must be fixed in LHM.
