### ISSUE TITLE
LH Failure to Initialise with Razer Tartarus USB controller connected.

### ISSUE THREAD

**Issue by displaced** [Rem0o/FanControl.Releases#2671]
**Describe the bug**

I'm not sure if this is a LibreHardware issue, or rather how FanControl uses it, but LH fails to initialise if I have my Razer Tartarus game controller connected to my machine.  FanControl then (unsurprisingly, since LH isn't working) has lost most of my sensors/fans.

If I unplug the controller and restart FanControl, all is fine.

**Log Entries**
```
18/08/2024 19:31:34: Open - HidSharp.Exceptions.DeviceIOException: Failed to get info.
   at HidSharp.Platform.Windows.WinHidDevice.RequiresGetInfo(GetInfoFlags flags)
   at HidSharp.Platform.Windows.WinHidDevice.GetProductName()
   at LibreHardwareMonitor.Hardware.Controller.Razer.RazerGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
18/08/2024 19:31:37: Open - HidSharp.Exceptions.DeviceIOException: Failed to get info.
   at HidSharp.Platform.Windows.WinHidDevice.RequiresGetInfo(GetInfoFlags flags)
   at HidSharp.Platform.Windows.WinHidDevice.GetProductName()
   at LibreHardwareMonitor.Hardware.Controller.Razer.RazerGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
18/08/2024 19:31:43: Open - HidSharp.Exceptions.DeviceIOException: Failed to get info.
   at HidSharp.Platform.Windows.WinHidDevice.RequiresGetInfo(GetInfoFlags flags)
   at HidSharp.Platform.Windows.WinHidDevice.GetProductName()
   at LibreHardwareMonitor.Hardware.Controller.Razer.RazerGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
```

**Relevant hardware specs and setup**
Ryzen something-or-other on an MSI Mortar Max B450M.  Razer Tartarus V1 controller.

**Comment by Rem0o** [comment]
That's a LibreHardwareMonitor issue.   In the meantime, you can disable the "Controller" section in sensor settings.
