### ISSUE TITLE
FanControl crash on start

### ISSUE THREAD

**Issue by Canas** [Rem0o/FanControl.Releases#271]
Hi, after the latest Windows Update and restart, the latest version is crashing for me. Some things I tried:

- Roll back versions up to v80.
- Update LHM to latest build.

Initially I was using the LHM that comes with FanControl but it was crashing and it showed in the logfile (something about Time Out and Nullable disableStorage). After lurking the threads here, I saw a recommendation to update LHW dll. I did that and the program still crashes but now the logfile shows nothing.

FanControl Logfile before updating LHM (using default DLL)
```
24-Jun-21 9:21:04 AM: System.Management.ManagementException: Timed out 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
24-Jun-21 9:21:04 AM: Could not initialize.
```

Windows Event Viewer Error **after updating to latest LHM build** (FanControl log is empty)
```
Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at FanControl.Domain.ComputerAccessLayer.Initialize(System.Nullable`1<Boolean>)
   at FanControl.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FanControl.App.Main()
```

My specs:
- M/B: Asus ROG Strig B550-I Gaming (BIOS version 2007)
- CPU: Ryzen 5900x
- GPU: RTX 3080

Any tips appreciated!

**Comment by Rem0o** [comment]
LHM has a lots of updates these times around, some of which are breaking changes, so you can't just swap the dll like that, as there is code modifications to do. Will update when the version seems stable enough.

**Comment by Rem0o** [comment]
Is this still happening ? @Canas

**Comment by Canas** [comment]
It opens the program now, but couldn't load my config
![IfydNrxplW](https://user-images.githubusercontent.com/2435560/123885356-e89a5800-d912-11eb-8be1-c54e767e7604.png)

It doesn't register CPU fans neither
![FanControl_qcSZIbJnQF](https://user-images.githubusercontent.com/2435560/123885364-ecc67580-d912-11eb-9461-f8ee90518423.png)

**Comment by BrainSlayer** [comment]
fancontrol crashes too for me in LHM . but i did not replace LHM so far

**Comment by Canas** [comment]
Latest version working correctly. Closing the issue.
