### ISSUE TITLE
Failed to initialize ADLXwrapper

### ISSUE THREAD

**Issue by ramz-1629** [Rem0o/FanControl.Releases#2737]
when launching the software (V202 net4.8) I keep running into this issue which says

"Fan Control failed to initialize.
The following sensor provider(s) failed initially: ADLXWrapper..."

I tried to find someone online with a similar issue but I cant find anything. I saw another issue on here (an old one) where someone solved it by opening the Fancontrol settings and unchecking the ALDXWrapper box but I have no idea how to do that since I cant get into the software

Im pretty sure ADLXwrapper is something to do with amd gpu's but I have an nvidia gpu so im not sure ADLXWrapper is even on.

_I attached a pic but dunno if its actually in here_
![image](https://github.com/user-attachments/assets/35338ff8-1fe4-4de5-8193-c03547e148f8)

**Comment by ramz-1629** [comment]
Update: I decided to download V201 net4.8 and I was allowed in despite it still giving the same issue and I've now unchecked ADLXWrapper. I'm going to just stay on V201 for now until a newer release comes.

**Comment by Zaxoosh** [comment]
I'm getting the same error!

**Comment by valantur** [comment]
reverting to 201 as a workaround works. 202 broke ADLX

**Comment by Rem0o** [comment]
ADLX should only be enabled if you have a dedicated AMD GPU in your PC.  Otherwise you should turn it off.

**Comment by SkyDiver7199** [comment]
> ADLX should only be enabled if you have a dedicated AMD GPU in your PC. Otherwise you should turn it off.

I have RX6800, turned off ADLX, it detects my sensor and control my fans now. 
ADLX is broken in V202...

**Comment by Rem0o** [comment]
See V203

**Comment by valantur** [comment]
203 didn't fix it for me:

>9/19/2024 9:34:27 PM: ADLX plugin: ADLXWrapper.ADLXEception: ADLX was not initialized before getting system services
   at ADLXWrapper.ADLXWrapper.GetSystemServices()
   at FanControl.ADLX.ADLXPlugin.Initialize()
9/19/2024 9:34:27 PM: Open - System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()

**Comment by Rem0o** [comment]
@valantur do not use the plugin anymore.  Use the built in adlx.
