### ISSUE TITLE
Initialization failed. Retry count (2) exceeded.

### ISSUE THREAD

**Issue by majornukke** [Rem0o/FanControl.Releases#2738]
Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at ADLXWrapper.Bindings.ADLXPINVOKE.delete_ADLXHelper(System.Runtime.InteropServices.HandleRef)
   at ADLXWrapper.Bindings.ADLXHelper.Dispose(Boolean)
   at ADLXWrapper.Bindings.ADLXHelper.Finalize()

Log.txt = Initialization failed. Retry count (2) exceeded.

**Comment by YakudzaKY** [comment]
same for me 202 doesnt work.  rollback to 201 works well.
btw 201 have error on start but at least it works
![изображение](https://github.com/user-attachments/assets/c354bc22-f71f-4eff-a07d-f49e7b417419)

**Comment by godzinilla** [comment]
I am forcing the same issue.

**Comment by SkyDiver7199** [comment]
same issue here. 
Used to have it and fixed. 
But now it's back.

**Comment by Rem0o** [comment]
V203 should not throw an error if no sensor were found with ADLX.

**Comment by YakudzaKY** [comment]
> V203 should not throw an error if no sensor were found with ADLX.

thanks very much!! <3

**Comment by 789cn** [comment]
lnitialization retry failed (lnitialization failed. Retry count （ 6 ） exceeded.)

**Comment by mufflon101** [comment]
same 
lnitialization retry failed (lnitialization failed. Retry count （ 6 ） exceeded.)
![Screenshot 2024-09-22 112920](https://github.com/user-attachments/assets/c41c5473-e01e-4b36-9e5d-05fa45c2ca50)

**Comment by rknauber** [comment]
Getting the same error every day now. The only thing that has changed aside from Fan Control updates is I update my video drivers on the 15th which is shown with the Nv errors in the log. Let me know if there is anything else I can provide to assist.

5900X
MSI MPG Edge Max Wifi - MSI-7D53
EVGA RTX 3080 FTW3 Ultra Gaming - 10G-P5-3897

`9/9/2024 10:24:49 AM: Initialization failed. Retry count (6) exceeded.
9/12/2024 10:10:09 AM: Initialization failed. Retry count (6) exceeded.
9/15/2024 4:15:23 PM: Update - NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
9/15/2024 4:15:23 PM: NvAPI failed. A complete refresh is required.
9/15/2024 4:17:24 PM: Initialization failed. Retry count (6) exceeded.
9/18/2024 9:30:55 AM: Initialization failed. Retry count (6) exceeded.
9/19/2024 6:41:49 AM: Initialization failed. Retry count (6) exceeded.
9/20/2024 11:43:09 AM: Initialization failed. Retry count (6) exceeded.
9/21/2024 10:17:39 AM: Initialization failed. Retry count (6) exceeded.
9/22/2024 9:59:05 AM: Initialization failed. Retry count (6) exceeded.`

**Comment by Rem0o** [comment]
These errors means one of the sensor sources failed to initialize. 
Either LHM, NVApiWrapper, ADLXWrapper, or a plugin. 

This information is missing from the current error log, will be adding more details in the next release.

Post what sensor sources you got checked and your hardware (GPU, fan controllers...), so we can identify which one is problematic.

**Comment by JKizaru** [comment]
Getting the same error randomly on startup.

![imagen](https://github.com/user-attachments/assets/ebd1373f-da43-4ae3-af27-27c2837cd2a9)

Corsair Plugin is installed and all sensors detected. I've checked all sensors and they are detected and controllable.

5800X3D
RTX4090FE
Asus ROG Crosshair VIII HERO WIFI
Corsair H150i ELITE LCD (Commander Core)
Corsair Commander Core with 6 fans

**Comment by faiezyacob** [comment]
I also have this issue and im on the latest version.

```
24/9/2024 12:02:28 AM: Open - System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.ADLX.ADLXPlugin.DisposeAll()
   at FanControl.ADLX.ADLXPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
24/9/2024 12:02:29 AM: Initialization failed. Retry count (2) exceeded.
```

Ryzen 5 4500
Rx6600
Asus Tuf b550m wifi ii

![image](https://github.com/user-attachments/assets/9fc15b6d-be45-4600-8b4d-842caa9bc8a1)

**Comment by phdzor** [comment]
![{F5984437-9140-4D1D-B6C9-F4FCDD0AC49F}](https://github.com/user-attachments/assets/48d05ada-e3d2-4883-9637-0187b5abd615)
Please add option to hide/ignote this warning.

**Comment by ShadowSingularity** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/be59bdb0-94db-4d6d-97b7-c157c8e40617)

AMD 7800X3D
RTX 4090
Asrock X670E Steel Legend

**Comment by abcdehc** [comment]
same problem at V204
log.txt file is attached
[log.txt](https://github.com/user-attachments/files/17158125/log.txt)

**Comment by doreori** [comment]
![image](https://github.com/user-attachments/assets/f16f9526-5c4f-412e-b0a4-ac048d8ccf29)
ADLXWrapper enabled

![image](https://github.com/user-attachments/assets/e044d923-4577-4538-a06d-7686be1f9d08)
ADLXWrapper disabled

Here are the logs :
[log.txt](https://github.com/user-attachments/files/17276432/log.txt)

**Comment by rknauber** [comment]
> Getting the same error every day now. The only thing that has changed aside from Fan Control updates is I update my video drivers on the 15th which is shown with the Nv errors in the log. Let me know if there is anything else I can provide to assist.
> 
> 5900X MSI MPG Edge Max Wifi - MSI-7D53 EVGA RTX 3080 FTW3 Ultra Gaming - 10G-P5-3897
> 
> `9/9/2024 10:24:49 AM: Initialization failed. Retry count (6) exceeded. 9/12/2024 10:10:09 AM: Initialization failed. Retry count (6) exceeded. 9/15/2024 4:15:23 PM: Update - NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget) at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors() at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update() at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update() 9/15/2024 4:15:23 PM: NvAPI failed. A complete refresh is required. 9/15/2024 4:17:24 PM: Initialization failed. Retry count (6) exceeded. 9/18/2024 9:30:55 AM: Initialization failed. Retry count (6) exceeded. 9/19/2024 6:41:49 AM: Initialization failed. Retry count (6) exceeded. 9/20/2024 11:43:09 AM: Initialization failed. Retry count (6) exceeded. 9/21/2024 10:17:39 AM: Initialization failed. Retry count (6) exceeded. 9/22/2024 9:59:05 AM: Initialization failed. Retry count (6) exceeded.`

This is no longer causing an error message every day on my computer. Resolved for my case.

**Comment by Rem0o** [comment]
@doreori   if you swapped from the plugin which you disabled to the built-in ADLX, there isn't any "conversion" between the two.   You need to setup the ADLX sensors again in your config with the "new" sensors from the new source..

**Comment by phantum29** [comment]
I have the same issue with Initialization failed. Retry count exceeded seemingly due to NvAPIWrapper. I have not changed sensors for at least a year now. Noticed this since I believe v205 - this is a recent occurrence. No plugins installed. [log](https://pastebin.com/FPav6X8V)
![Screenshot 2024-10-14 085327](https://github.com/user-attachments/assets/33ce7831-49c3-4770-842c-5bd45de4baf4)

**Comment by tidybug** [comment]
For anyone still struggling with this, this is what solved it for me:

![Image](https://github.com/user-attachments/assets/b36e013d-bbfd-4776-abdf-eff8cb337a28)

Since I only use FanControl for my GPU fans, I disabled the rest. Apart from that, you might want to consider disabling the LibreHardwareMonitor functionality entirely, since it's using a vulnerable driver.

One last thing, although I know this isn't the place to write the following: 

BIG THANKS to the devs for creating such a nice piece of software. I appreciate it :))
