### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by mananong** [Rem0o/FanControl.Releases#277]
hi updated to v85 and restarted, still missing GPU temp/fans. app still crashes when i click on refresh sensors detection

attached log

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6722100/log.txt)

**Comment by mananong** [comment]
btw GPU fans, voltages, temps etc are detected by HWinfo, radeon software, every other monitoring app (AMD 6700 xt reference)

**Comment by Rem0o** [comment]
From your log:

Overdrive5 Temperature

 Status: ADL_ERR_NOT_SUPPORTED
 Value: 0

Overdrive5 FanSpeed

 Status RPM: ADL_ERR_NOT_SUPPORTED
 Value RPM: 0
 Status Percent: ADL_ERR_NOT_SUPPORTED
 Value Percent: 0

**Comment by shewless** [comment]
Hi. I noticed that V80 and earlier detects my AMD 6700XT fan and temperatures but V81 and above does not.  Seems similar to what @mananong posted about.
I imagine it has to do with the LibreHardwareMonitorLib being updated in V81.

**Comment by shewless** [comment]
@Rem0o should I open a separate issue for the above? I noticed that V80 and lower detects my AMD 6700XT fan and temps but V81 and after no longer detects any AMD 6700XT sensors.
I figure it's related to LibreHardwareMonitorLib but I'm not sure how to isolate that or how to check which version is being used. I'm willing to help narrow the issue down if you can give me some hints.

**Comment by shewless** [comment]
> 
> 
> @shewless every hardware detection/compatibility issue is linked to LibreHardwareMonitorLib since it is the library used to detect and control everything. FanControl is only a UI layer on top.

Hi. Yes I understand that.  Is there a easy way for me to take the latest version of Fancontrol and change the version of LibreHardwareMonitorLib?

**Comment by Rem0o** [comment]
Switch the LibreHardwareMonitorLib dll.

**Comment by shewless** [comment]
> 
> 
> Switch the LibreHardwareMonitorLib dll.

If I take LibreHardwareMonitorLib.dll from V80 and add it to V86, FanControl doesn't even start.

> 
2021-07-13 12:27:04 PM: System.MissingMethodException: Method not found: 'Void LibreHardwareMonitor.Hardware.Computer.set_IsPsuEnabled(Boolean)'.
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Initialize()
2021-07-13 12:27:04 PM: Could not initialize.
2021-07-13 12:27:21 PM: System.MissingMethodException: Method not found: 'Void LibreHardwareMonitor.Hardware.Computer.set_IsPsuEnabled(Boolean)'.
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Initialize()
2021-07-13 12:27:21 PM: Could not initialize.
2021-07-13 12:28:34 PM: System.MissingMethodException: Method not found: 'Void LibreHardwareMonitor.Hardware.Computer.set_IsPsuEnabled(Boolean)'.
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Initialize()
2021-07-13 12:28:34 PM: Could not initialize.

I will try to get the latest version of the dll from the LHM git repo I suppose....

**Comment by shewless** [comment]
@Rem0o I downloaded version 0.8.7 of LHM.  If I run the executable that comes with that package, I can see that the Temperature and Fan sensors for my 6700XT are detected just fine.
If I try and place that .dll into the FanControl directory, FanControl won't start:

> 
2021-07-13 12:33:19 PM: System.MissingMethodException: Method not found: 'Void LibreHardwareMonitor.Hardware.Computer.set_IsPsuEnabled(Boolean)'.
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Initialize()
2021-07-13 12:33:19 PM: Could not initialize.

At any rate it looks like LHM version 0.8.7 does detect the sensors but maybe they aren't exposed to FanControl the same way they used to be?

I'm happy to dig further if it would help you.

**Comment by Rem0o** [comment]
Right, some new signatures were added, so backward beyond some point is not possible.

**Comment by shewless** [comment]
> 
> 
> Right, some new signatures were added, so backward beyond some point is not possible.

Taking the latest version of fancontrol and placing the LHM version 0.8.7 .dll downloaded from git provides the error above.  I guess I cannot help you further.  I will live with V80 working I guess.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V91

**Comment by shewless** [comment]
> 
> 
> See https://github.com/Rem0o/FanControl.Releases/releases/tag/V91

Works much better for me. Thanks
