### ISSUE TITLE
Errors + crash on reload of sensors + crash on resume

### ISSUE THREAD

**Issue by biustech** [Rem0o/FanControl.Releases#279]
I'm really happy with this project. thank you for your hard work. just i few problems
I don't remember which exact version this issue started but If I had to guess was 78 or around that.
the main issues are:
when i resume from sleep FC shows the errors in the screenshot attached and when i click refresh FC crashes
when restart i also have to manually refresh the sensors
![screenshot 4](https://user-images.githubusercontent.com/40319261/123865029-b77a5180-d92b-11eb-98de-712043c8d358.jpg)
my system and FC version;
FC version 85
MSI B550i Gaming ITX motherboard
Ryzen 3600
video card MSI 5500XT
32GB memory
windows 10 21h1 x64

error log from eventvwr

> Application: FanControl.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.AccessViolationException
>    at LibreHardwareMonitor.Hardware.InpOut.ReadMemory(IntPtr, UInt32)
>    at LibreHardwareMonitor.Hardware.RyzenSMU.ReadDramToArray()
>    at LibreHardwareMonitor.Hardware.RyzenSMU.GetPmTable()
>    at LibreHardwareMonitor.Hardware.CPU.Amd17Cpu+Processor.UpdateSensors()
>    at LibreHardwareMonitor.Hardware.CPU.Amd17Cpu.Update()
>    at LibreHardwareMonitor.Hardware.CPU.CpuGroup..ctor(LibreHardwareMonitor.Hardware.ISettings)
>    at LibreHardwareMonitor.Hardware.Computer.AddGroups()
>    at LibreHardwareMonitor.Hardware.Computer.Open()
>    at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
>    at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1<System.__Canon>)
>    at FanControl.Domain.ComputerAccessLayer.Initialize()
>    at FanControl.Domain.ComputerAccessLayer.Refresh()
>    at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    at System.Windows.Application.RunDispatcher(System.Object)
>    at System.Windows.Application.RunInternal(System.Windows.Window)
>    at FanControl.App.Main()
>

**Comment by Rem0o** [comment]
When going to sleep, your BIOS resets every setting that FanControl applied. To resume operation, I thus catch the resume from sleep event, then effectively "close" the app and "reopen" it from a backend perspective. It works in *most* cases with most motherboards.  

However....

I suspect that keeping the driver alive in sleep mode cause some weird bug when resuming from sleep in your specific case.   But that's just a theory.    What I could try is catching the " before sleep" event, close the driver there, and reopening it when resuming from sleep. 

So going from

0) "Driver is alive"
1) Sleep
2) Resume from sleep
3) Close Driver
4) Open Driver

To....

0) "Driver is alive"
1) Close Driver
2) Sleep
3) Resume from sleep
4) Open Driver

It shouldn't change anything for those that have no issues already, and might be more robust.

**Comment by biustech** [comment]
thanks for the reply man, do your magic there. it will be really appreciated

**Comment by Rem0o** [comment]
V86 implement the exact behavior I described above.

**Comment by DustRaider8** [comment]
FanControl still crashes for me after a wake up from either sleep or hibernate even on V86. It started happening a few versions ago like biustech said but my crash is different from his. When my computer resumes from sleep/hibernate, the fans aren't controlled by FanControl and when I hover over FanControl's tray icon, it disappears so I just have to start the program again. It might have started happening on V84 or V85 because I don't think it was happening on V83 and earlier. I might try V83 tomorrow. I'm getting 3 errors related to this in Event Viewer. The first one is a .NET Runtime error which looks similar to biustech's log and the other 2 are application errors.

Motherboard: MSI B450 Tomahawk MAX
CPU: Ryzen 3600

### 1st error
> Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at LibreHardwareMonitor.Hardware.InpOut.ReadMemory(IntPtr, UInt32)
   at LibreHardwareMonitor.Hardware.RyzenSMU.ReadDramToArray()
   at LibreHardwareMonitor.Hardware.RyzenSMU.GetPmTable()
   at LibreHardwareMonitor.Hardware.CPU.Amd17Cpu+Processor.UpdateSensors()
   at LibreHardwareMonitor.Hardware.CPU.Amd17Cpu.Update()
   at FanControl.Domain.UpdateVisitor.VisitHardware(LibreHardwareMonitor.Hardware.IHardware)
   at LibreHardwareMonitor.Hardware.Computer.Traverse(LibreHardwareMonitor.Hardware.IVisitor)
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Update()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1<System.__Canon>)
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.SystemEvents_PowerModeChanged(System.Object, Microsoft.Win32.PowerModeChangedEventArgs)
   
   
> Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at Microsoft.Win32.SystemEvents+SystemEventInvokeInfo.InvokeCallback(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at System.Windows.Threading.DispatcherSynchronizationContext.Send(System.Threading.SendOrPostCallback, System.Object)
   at Microsoft.Win32.SystemEvents+SystemEventInvokeInfo.Invoke(Boolean, System.Object[])
   at Microsoft.Win32.SystemEvents.RaiseEvent(Boolean, System.Object, System.Object[])
   at Microsoft.Win32.SystemEvents.OnPowerModeChanged(IntPtr)
   at Microsoft.Win32.SystemEvents.WindowProc(IntPtr, Int32, IntPtr, IntPtr)
   
   ### 2nd

> Faulting application name: FanControl.exe, version: 1.0.0.0, time stamp: 0xaa5e93f3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1081, time stamp: 0xde3fc775
Exception code: 0xe0434352
Fault offset: 0x0000000000034ed9
Faulting process id: 0x5444
Faulting application start time: 0x01d77428aa896cf7
Faulting application path: C:\FanControl\FanControl.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8b3a9990-a7e6-4e74-a8cc-4e350a773f9d
Faulting package full name: 
Faulting package-relative application ID: 

### 3rd

> Faulting application name: FanControl.exe, version: 1.0.0.0, time stamp: 0xaa5e93f3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1081, time stamp: 0xde3fc775
Exception code: 0xc000041d
Fault offset: 0x0000000000034ed9
Faulting process id: 0x5444
Faulting application start time: 0x01d77428aa896cf7
Faulting application path: C:\FanControl\FanControl.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5c4ece57-7408-452c-8d00-1ba94ceeb67d
Faulting package full name: 
Faulting package-relative application ID:

**Comment by DustRaider8** [comment]
I just tested V84 and V83 and confirmed that the problem (at least for me) starts happening on V84. V83 continues working fine after the PC wakes up from sleep.

**Comment by Rem0o** [comment]
@DustRaider8  I have seriously no idea why you are getting an AccessViolationException in the LHM update routine :/

**Comment by biustech** [comment]
thank you man! appreciate your effort in fixing the bugs so fast
unfortunately I still have problems after this update.
after resume my FC still crashes, and when I run it again i get detections errors and when asked to refresh the app crashes again... i have to keep doing this till somehow it works
Another problem now is the donatation pop up is constantly showing everytime i open the app

eventvwr log
```
Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at LibreHardwareMonitor.Hardware.InpOut.ReadMemory(IntPtr, UInt32)
   at LibreHardwareMonitor.Hardware.RyzenSMU.ReadDramToArray()
   at LibreHardwareMonitor.Hardware.RyzenSMU.GetPmTable()
   at LibreHardwareMonitor.Hardware.CPU.Amd17Cpu+Processor.UpdateSensors()
   at LibreHardwareMonitor.Hardware.CPU.Amd17Cpu.Update()
   at LibreHardwareMonitor.Hardware.CPU.CpuGroup..ctor(LibreHardwareMonitor.Hardware.ISettings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1<System.__Canon>)
   at FanControl.Domain.ComputerAccessLayer.Initialize()
   at FanControl.Domain.ComputerAccessLayer.Refresh()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at FanControl.App.Main()
```
FC log [https://pastebin.com/7GHJBk7N](https://pastebin.com/7GHJBk7N)

![screenshot 3](https://user-images.githubusercontent.com/40319261/125030605-a8ae4000-e08b-11eb-95af-80ac9b2f45ac.jpg)

**Comment by biustech** [comment]
i've downgraded to v83, so far everything working flawlessly! hope you can figure out what caused this new behavior after v83

**Comment by Rem0o** [comment]
@biustech  It's a LHM issue with the new Ryzen SMU sensors implementation. Might just kill those for now as it is buggy it seems like.

**Comment by Rem0o** [comment]
[FanControl_With_SMU_Disabled.zip](https://github.com/Rem0o/FanControl.Releases/files/6804286/FanControl_With_SMU_Disabled.zip)

Just did a quick build where I disable the SMU stuff by reflection. Can anyone test it?

**Comment by DustRaider8** [comment]
This one is also crashing for me.

**Comment by biustech** [comment]
> [FanControl_With_SMU_Disabled.zip](https://github.com/Rem0o/FanControl.Releases/files/6804286/FanControl_With_SMU_Disabled.zip)
> 
> Just did a quick build where I disable the SMU stuff by reflection. Can anyone test it?

crashing with me too, after resume, but so far no sensor errors

**Comment by Rem0o** [comment]
@DustRaider8  & @biustech, any logs with that build?

**Comment by biustech** [comment]
> @DustRaider8 & @biustech, any logs with that build?

https://pastebin.com/sSnbAT3x

**Comment by biustech** [comment]
just a heads up, i had a zip file with all the files from v86 when it was crashing, and i removed the v83 and starting using again the v86 files with the .exe replaced.

**Comment by Rem0o** [comment]
I meant error logs, either from log.txt or from the eventviewer.

**Comment by biustech** [comment]
> I meant error logs, either from log.txt or from the eventviewer. Still looking to catch what's causing the crash.

https://pastebin.com/jyzMt034

https://pastebin.com/JW2htCDT

https://pastebin.com/rp98FUw9

**Comment by Rem0o** [comment]
[FanControl_WIth_InpOut_Disabled.zip](https://github.com/Rem0o/FanControl.Releases/files/6810424/FanControl_WIth_InpOut_Disabled.zip)

Tried to disable it further up the root.

**Comment by biustech** [comment]
> [FanControl_WIth_InpOut_Disabled.zip](https://github.com/Rem0o/FanControl.Releases/files/6810424/FanControl_WIth_InpOut_Disabled.zip)
> 
> Tried to disable it further up the root.

IT WORKED!!! no crash from resume, I'll test more and get back here if anything happens

**Comment by atakiya** [comment]
> [FanControl_WIth_InpOut_Disabled.zip](https://github.com/Rem0o/FanControl.Releases/files/6810424/FanControl_WIth_InpOut_Disabled.zip)
> 
> Tried to disable it further up the root.

Fixes the sleep-crash here as well! Thank you for looking into this.

FC version that was running before: V85
CPU: AMD Ryzen 7 3800XT
GPU: AMD Radeon RX 5700 XT
Motherboard: Gigabyte X570 AORUS Master (ITE IT8688E, ITE IT8792E)
OS: Windows 10 version 21H1 / `19043.1110`

**Comment by Rem0o** [comment]
Will try to make sense of all of this and integrate that into the next version.

**Comment by DustRaider8** [comment]
Sorry, I was busy yesterday. Anyway just to confirm, this new one fixed everything. No crashes on resume and no errors in event viewer. Also no log.txt but even the other ones that were crashing didn't produce a log.txt most of the time.
