### ISSUE TITLE
UI not responsive - Infinite error loop

### ISSUE THREAD

**Issue by ochompsky** [Rem0o/FanControl.Releases#2796]
This isn't so much a bug as much as enhancement I think.  If there is an unexpected error like this, the error loops infinitely:

> 10/20/2024 7:14:23 PM: LogUnhandledException - System.Exception: Get fan RPM speed Error: CTL_RESULT_ERROR_DEVICE_LOST
>    at Extensions.ThrowIfError(ctl_result_t result, String context)
>    at FanControl.IntelCtlLibraryPlugin.DeviceFan.GetSpeedRpm() in C:\projects\fancontrol-intelctllibrary\DeviceFan.cs:line 50
>    at FanControl.IntelCtlLibraryPlugin.DeviceFanPluginSensor.Update() in C:\projects\fancontrol-intelctllibrary\DeviceFanPluginSensor.cs:line 24
>    at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
>    at FanControl.Domain.ComputerAccessLayer.Update()
>    at FanControl.Domain.ApplicationClock.DoActions()
> --- End of stack trace from previous location ---
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate 

I know this particular error is because of the unreliable arc plugin but in general, is it possible to make the UI not become completely unstable?  The error just infinitely loops and you can't click or do anything.

**Comment by Rem0o** [comment]
I guess I could shutdown the whole provider/plugin when this happens.
