### ISSUE TITLE
Unable to start FanControl 

### ISSUE THREAD

**Issue by thesaintone** [Rem0o/FanControl.Releases#2815]
Hello, 
I have a small issue while trying to open FanControll. It doesnt start at all (using normal method). 
Only time when iam able to run it is spamming enter and trying to open the app. It pops the error window that there is an issue running the app, please check logs.
Logs attached, also my hardware. 
Fresh install windows 11 fully updated. Updated drivers for motherboard, CPU and GPU. 

P.S
Love your software. Keep up good work. <3

![hwmonitor](https://github.com/user-attachments/assets/30990530-0a14-462f-bd7b-0bd4f1ed3d8d)
[log.txt](https://github.com/user-attachments/files/17636340/log.txt)

**Comment by Rem0o** [comment]
Are you trying to run the software from a non-admin account?

**Comment by thesaintone** [comment]
No, I am owner/admin of this PC, also running FC with admin rights.

**Comment by Rem0o** [comment]
All I get from your log is the various errors from the "spam". Delete that log. 
Does it eventually works? When you open it normally, do you get a process in task manager or does it crashes?

**Comment by thesaintone** [comment]
Basicaly, when i open it normally it doesnt show in task manager and the app dont start. When i spam it it will give me the error, open app, and run normally.

**Comment by thesaintone** [comment]
11/6/2024 6:41:22 PM: IPC Error: 
11/6/2024 6:41:22 PM: CheckForOtherInstance - Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrpcDotNetNamedPipes.Internal.MessageReader`1.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrpcDotNetNamedPipes.Internal.MessageReader`1.<>c__DisplayClass9_0.<<ReadNextMessage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Bootstrap.<CheckForOtherInstance>d__26.MoveNext()
11/6/2024 6:41:24 PM: IPC Error: 
11/6/2024 6:41:24 PM: CheckForOtherInstance - Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrpcDotNetNamedPipes.Internal.MessageReader`1.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GrpcDotNetNamedPipes.Internal.MessageReader`1.<>c__DisplayClass9_0.<<ReadNextMessage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Bootstrap.<CheckForOtherInstance>d__26.MoveNext()

**Comment by Rem0o** [comment]
There has to be a crash repprt in event viewer if it doesn’t even appear in task manager.

**Comment by thesaintone** [comment]
> There has to be a crash repprt in event viewer if it doesn’t even appear in task manager.

Thanks for replying.
That is correct. File attached.
[events.txt](https://github.com/user-attachments/files/17652974/events.txt)

**Comment by Rem0o** [comment]
The AMD driver/handle is crashing.   Do you have any plugin? Also, make sure you got ADLX disabled in your sensor sources.

**Comment by thesaintone** [comment]
No plugins at all. Just fresh windows install with all drivers updated.

**Comment by Rem0o** [comment]
Open your json config file with a text editor, edit it to put ADLX to false instead of true.

**Comment by thesaintone** [comment]
> Open your json config file with a text editor, edit it to put ADLX to false instead of true. Try and start it then.

Ive manage to change through settings menu. Works :) Thank you so much. I love this software and definietly will support you after my paycheck 👯  keep up awesome work :D

**Comment by K1Lc4m** [comment]
So AMD gpu control is not working for now ? I've follow these steps too and it works again but the gpu control is gone.

**Comment by Rem0o** [comment]
@K1Lc4m  do not hijack issues, especially closed one. 

OP didn't have an AMD gpu.

If you have issues -> Make sure you got the latest adrenaline version.  There were crashes with previous versions.

**Comment by K1Lc4m** [comment]
Sorry, I was trying to find solution for an hour and it's the first one that was working.
I've rolled back my adrenaline version because there's crash with full screen video on discord with my vertical display.
I will try with the next driver release, sorry for the comment and have a great day.
