### ISSUE TITLE
Kraken plugin not being recoignised

### ISSUE THREAD

**Issue by zefrogi** [Rem0o/FanControl.Releases#2827]
**If you are experiencing a crash**
12/11/2024 17:45:43: Unhandled exception in FanControl v207.0.0.0
12/11/2024 17:45:43: LogUnhandledException - System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at FanControl.Domain.PluginService.InstallPlugin(String zipFilePath)
   at FanControl.ViewModels.SensorSettingsViewModel.<InstallPluginDialog>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.MVVM.AsyncCommand.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FanControl.MVVM.AsyncCommand.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Describe the bug**
I download the Kraken plugin https://github.com/brokenmass/Fancontrol.NzxtKraken but it doesn't appear at the 'Install Pluing...' selection window.

If I'm quick enough as it appears for a second, there is is the error below:
![image](https://github.com/user-attachments/assets/9ef2aeaf-d3ae-4a8d-9331-f534ec3456ca)

I tried to move the plugin to another folder, Documents, FanControl but no luck.

**Is there a log.txt file next to FanControl.exe with recent date entries?**

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
The "install plugin" dialog only supports .zip for now.   Just manually copy the dll over the plugin folder of the application.

**Comment by zefrogi** [comment]
I download the dll and copied it over to the plugin folder, but now get this error:
![image](https://github.com/user-attachments/assets/9c2e4110-a6c7-4b7e-9348-d898c0cae61c)

**Comment by Rem0o** [comment]
As the message says, right click the dll -> properties -> unlock.
