### ISSUE TITLE
Fresh install - DirectoryNotFoundException

### ISSUE THREAD

**Issue by danherb** [Rem0o/FanControl.Releases#2860]
Hey, I downloaded portable version and ran it without extracting it. Then I realized it wont work but it was too late, I already was creating some configuration. I got some errors in UI with message being empty string. Then I downloaded installable version, installed it but Im just getting `DirectoryNotFoundException` exception.

```
29.11.2024 22:41:28: SaveAllConfig - System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myname\AppData\Local\Temp\Rar$EXa9340.33028\Configurations\userConfig.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at FanControl.Domain.ApplicationState.SaveAllConfig(String fileName)
29.11.2024 22:41:28: SaveCache - System.IO.DirectoryNotFoundException: Could not find a part of the path 
'C:\Users\myname\AppData\Local\Temp\Rar$EXa9340.33028\Configurations\CACHE'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at FanControl.Domain.ApplicationState.SaveCache()
```
Folder `Configurations` indeed doesnt exist. I can not create new configuration, basically nothing works.
Thanks for any help.

**Comment by Fr0stX76** [comment]
Reboot then try this, then install

https://www.solveyourtech.com/how-to-clear-temp-files-windows-11-a-step-by-step-guide/

**Comment by Rem0o** [comment]
> and ran it without extracting it.

You can't do that. 

You got to extract the whole thing in a folder/location of your choice.

**Comment by danherb** [comment]
done. Works, thanks!
