### ISSUE TITLE
Fan Control don't launch - Autofac.Core.DependencyResolutionException

### ISSUE THREAD

**Issue by johnlenfr** [Rem0o/FanControl.Releases#2882]
Hi, don't know if my motherboard is supported: ZOTAC GeForce 9300-ITX WiFi

**If you are experiencing a crash**
Log file :
`
12/21/2024 5:32:01 PM: Startup - Autofac.Core.DependencyResolutionException: An exception was thrown while activating FanControl.ViewModels.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, FanControl.Domain.IApplicationState, FanControl.Domain.IWindowsSettings, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.IPluginService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> System.TypeLoadException: Could not find Windows Runtime type 'Windows.UI.ViewManagement.UISettings'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
   at FanControl.ViewModels.WindowSettingsViewModel..ctor(IApplicationState state, IDialogService dialogService, IApplicationContext applicationContext, IWindowsSettings windowsSettings, IUpdaterService updaterService, ILogger logger, ObservableCollection`1 tempSources, ObservableCollection`1 fanSources)
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, IApplicationState applicationState, IWindowsSettings windowsSetting, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, IPluginService pluginService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.Bootstrap.<Startup>d__15.MoveNext()
21/12/2024 17:32:03: Dispose - System.TypeLoadException: Could not find Windows Runtime type 'Windows.UI.Notifications.ScheduledToastNotification'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Uninstall()
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at FanControl.Bootstrap.Dispose()`

**Describe the bug**
Fan control won't start. Get the "An unexpeted error occured " box.

**Relevant hardware specs and setup**
Operating System
			Windows 7 Édition Intégrale 64-bit SP1
		CPU
			Intel Pentium E5200 @ 2.50GHz	38 °C
			Wolfdale 45nm Technology
		RAM
			4,00 Go Dual-Channel DDR2 @ 399MHz (7-15-15-63)
		Motherboard
			ZOTAC GeForce 9300-ITX WiFi / NVIDIA MCP7A (Socket 775)
		Graphics
			IPS226 (1920x1080@60Hz)
			4095MB NVIDIA GeForce GTX 1650 (NVIDIA)	30 °C
		Storage
			55GB KingDian S200 60GB ATA Device (SATA (SSD))	40 °C
		Optical Drives
			No optical disk drives detected
		Audio
			Realtek High Definition Audio

**Comment by Fr0stX76** [comment]
[FAQ](https://github.com/Rem0o/FanControl.Releases?tab=readme-ov-file#faq)
Q: Does it run on my OS?
A: If your OS is Windows 10 Or 11, yes.

**Comment by johnlenfr** [comment]
Thank you for the quick reply.

Is there a fork for W7?

**Comment by Fr0stX76** [comment]
Fan Control is close source, so creating forks is not an option

**Comment by johnlenfr** [comment]
Ok thank you
