### ISSUE TITLE
FanControl.exe doesn't open

### ISSUE THREAD

**Issue by daKRAZI** [Rem0o/FanControl.Releases#298]
any idea of the problem, the app doesn't open at all

**Comment by Rem0o** [comment]
Without you giving me any details, like logs, type of computer, how do you expect me to help you?

**Comment by melpeln** [comment]
I don't know what else would be useful, but I've noticed it always happens when closing the app's window and then trying to open the app again.

**Comment by briannaxrene** [comment]
I just downloaded this on Windows 10, opened fine at first. Closed it, went to re-open, same issue here. Shows as a background process but doesn't show in the taskbar, and no window comes up. I did get a pop up to Allow Access, I click yes, nothing yet. 

I'll try a restart and see if that does it though, may just be a minor error.

**Comment by JoshBatt1** [comment]
Does it show in the system tray? That’s how my issues was solved. You can open it from there. Bottom right hand side of taskbar where the arrow is.

**Comment by briannaxrene** [comment]
> Does it show in the system tray? That’s how my issues was solved. You can open it from there. Bottom right hand side of taskbar where the arrow is.

Ahhh, see that would have been it. My fans aren't detected on my MSI anyway, I ended up having to uninstall unfortunately :/

Shame, the app looks amazing as well.

**Comment by LegitM8** [comment]
Hello, Im getting the game issue. Here are my logs 

12/10/2022 3:27:22 PM: System.InvalidOperationException
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at FanControl.Domain.IPC.MultiInstanceMessaging.OnNewInstance(OnMessageEventArgs`1 args)
   at FanControl.Domain.InterProcessMessaging`1.<>c__DisplayClass10_0.<StartReceiverLoop>b__0()
