### ISSUE TITLE
Doesn't work on hybrid Intel/Nvidia laptop (Asus notebook)

### ISSUE THREAD

**Issue by Noruas29** [Rem0o/FanControl.Releases#30]
When I launch the tool, nothing happened on [my Asus](https://www.asus.com/Laptops/K551LN/specifications/).

My log:

`03/09/2020 09:33:07: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   à NvAPIWrapper.Native.GPUApi.GetCoolerSettings(PhysicalGPUHandle gpuHandle, CoolerTarget coolerTarget)
   à NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   à System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   à System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à FanControl.Domain.ComputerAccessLayer.Initialize()
03/09/2020 09:33:07: Could not initialize.`

**Comment by BrainSlayer** [comment]
yes. its a better solution. because fancontrol does simply not work on such devices and does silently exit withthis exception log.

**Comment by nmdanny** [comment]
In the current release (v90) this prevents the GUI from being shown, yielding the following exception:

```

13/08/2021 22:30:30: Unhandled exception in FanControl v1.0.0.0
13/08/2021 22:30:30: Autofac.Core.DependencyResolutionException: An exception was thrown while activating FanControl.ViewModels.MainWindowViewModel. ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILicenceService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Models.NVApiTempSensor.get_Name()
   at FanControl.ViewModels.TempSensorViewModel..ctor(ISensor sensor, Action`2 registerOnChanged)
   at FanControl.ViewModels.MainWindowViewModel.<LoadSensors>b__16_1(ISensor ts)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at FanControl.MVVM.Extentions.AddRange[T](ObservableCollection`1 observableCollection, IEnumerable`1 items)
   at FanControl.ViewModels.MainWindowViewModel.LoadSensors()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILicenceService licenceService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at FanControl.App.OnStartup(StartupEventArgs eventArgs)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
13/08/2021 22:30:30: Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(FanControl.Domain.IComputerAccessLayer, FanControl.Domain.IApplicationClock, FanControl.Domain.IApplicationContext, MaterialDesignThemes.Wpf.ISnackbarMessageQueue, FanControl.ViewModels.IFanCurveProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.ViewModels.ICustomSensorProvider`1[FanControl.ViewModels.MainWindowViewModel], FanControl.Domain.IDialogService, FanControl.Domain.IUpdaterService, FanControl.Domain.ILicenceService, FanControl.Domain.ILogger)' on type 'MainWindowViewModel'. ---> NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Models.NVApiTempSensor.get_Name()
   at FanControl.ViewModels.TempSensorViewModel..ctor(ISensor sensor, Action`2 registerOnChanged)
   at FanControl.ViewModels.MainWindowViewModel.<LoadSensors>b__16_1(ISensor ts)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at FanControl.MVVM.Extentions.AddRange[T](ObservableCollection`1 observableCollection, IEnumerable`1 items)
   at FanControl.ViewModels.MainWindowViewModel.LoadSensors()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILicenceService licenceService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<ConfigurePipeline>b__11_0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
13/08/2021 22:30:30: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_GPU_NOT_POWERED
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Models.NVApiTempSensor.get_Name()
   at FanControl.ViewModels.TempSensorViewModel..ctor(ISensor sensor, Action`2 registerOnChanged)
   at FanControl.ViewModels.MainWindowViewModel.<LoadSensors>b__16_1(ISensor ts)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at FanControl.MVVM.Extentions.AddRange[T](ObservableCollection`1 observableCollection, IEnumerable`1 items)
   at FanControl.ViewModels.MainWindowViewModel.LoadSensors()
   at FanControl.ViewModels.MainWindowViewModel..ctor(IComputerAccessLayer computerAccessLayer, IApplicationClock applicationClock, IApplicationContext applicationContext, ISnackbarMessageQueue messageQueue, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider, IDialogService dialogService, IUpdaterService updaterService, ILicenceService licenceService, ILogger logger)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
```
