### ISSUE TITLE
v88 update couldn't read config file

### ISSUE THREAD

**Issue by Alokin-ITA** [Rem0o/FanControl.Releases#301]
After the autoupdate to v88, opening FanControl i was greeted with a message sayin that there was an error, my confing was not being read.
In the log this appeared:

```
23/07/2021 20:24:33: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.ViewModels.MixFanCurveViewModel.UpdateCurrentCommandTarget()
   at FanControl.ViewModels.MixFanCurveViewModel.UpdatedSelectedFromWanted()
   at FanControl.ViewModels.MixFanCurveViewModel.Deserialize(IMixFanCurve mixFanCurve, Func`2 validateName, Action`1 deleteFanCurve, ObservableCollection`1 fanCurves, IApplicationClock applicationClock, IDialogService dialogService)
   at FanControl.App.<>c__DisplayClass18_0.<RegisterTypes>b__8(MainWindowViewModel c, SerializableMixFanCurve fc)
   at FanControl.ViewModels.FanCurveProvider`1.<Deserialize>d__4.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider)
   at FanControl.ViewModels.MainWindowViewModel.LoadCurrentApplicationState()
23/07/2021 20:24:34: Unhandled exception in FanControl v1.0.0.0
23/07/2021 20:24:34: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.ViewModels.MixFanCurveViewModel.UpdateCurrentCommandTarget()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I will add my config if needed

**Comment by joncrocks** [comment]
I'm having similar issues having updated to v88. Was working fine, now it's not working at all. Not registering any temps/controlling fans.

Very similar messages (over and over):

24/07/2021 08:12:39: Unhandled exception in FanControl v1.0.0.0
24/07/2021 08:12:39: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.ViewModels.MixFanCurveViewModel.UpdateCurrentCommandTarget()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by joncrocks** [comment]
v87 (via the tag) seems to work OK for the same configuration.

**Comment by Rem0o** [comment]
Can you send your config file?

**Comment by bfeist** [comment]
Same thing here. Interface shows everything disabled and all fans running at a constant speed.

I get about 300 lines of these exceptions:
7/24/2021 11:39:35 AM: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.ViewModels.MainWindowViewModel.<ShowError>d__142.MoveNext()
7/24/2021 11:39:35 AM: Unhandled exception in FanControl v1.0.0.0
7/24/2021 11:39:35 AM: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.ViewModels.MixFanCurveViewModel.UpdateCurrentCommandTarget()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
7/24/2021 11:39:36 AM: Unhandled exception in FanControl v1.0.0.0
7/24/2021 11:39:36 AM: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.ViewModels.MixFanCurveViewModel.UpdateCurrentCommandTarget()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---


Here is my config file:
[userConfig.zip](https://github.com/Rem0o/FanControl.Releases/files/6872677/userConfig.zip)

**Comment by joncrocks** [comment]
[Jon1.zip](https://github.com/Rem0o/FanControl.Releases/files/6872788/Jon1.zip)

**Comment by Rem0o** [comment]
Could reproduce the bug with your configs, thanks! Fix coming soon.

**Comment by Alokin-ITA** [comment]
b2daa78
issue fixed

**Comment by bfeist** [comment]
Thanks so much. Excellent app btw!
