### ISSUE TITLE
Error on boot

### ISSUE THREAD

**Issue by Enferlain** [Rem0o/FanControl.Releases#344]
Every time I reboot it does this and I have to refresh like 5 times and then adjust something for the profiles to start working

![image](https://user-images.githubusercontent.com/15861396/135286100-851515c0-8be9-45cc-8031-a720a61da412.png)

error logs

9/29/2021 4:11:15 PM: LibreHardwareMonitor.Hardware.Psu.Corsair.CommunicationProtocolError: Error communicating with the PSU controller at \\?\hid#vid_1b1c&pid_1c06#a&2c7d192&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: Can't read product
   at LibreHardwareMonitor.Hardware.Psu.Corsair.UsbApi.FwInfo(HidStream stream)
   at LibreHardwareMonitor.Hardware.Psu.Corsair.CorsairPsu..ctor(HidDevice device, ISettings settings, Int32 index)
   at LibreHardwareMonitor.Hardware.Psu.Corsair.CorsairPsuGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()

That's all I have in there

**Comment by Enferlain** [comment]
Yeah, basically ever since I started using fan control corsair service keeps dying. Dunno why it's doing that, only thing it controls is the psu fan and nothing else

![image](https://user-images.githubusercontent.com/15861396/135680934-6d1ee590-2fa7-4bad-b6f8-e809dd6ddb6f.png)

**Comment by Rem0o** [comment]
See V96. Exclude the PSU.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V96
