### ISSUE TITLE
LibreHardwareMonitor.Hardware.Controller.AquaComputer.MPS.Update

### ISSUE THREAD

**Issue by Mushin** [Rem0o/FanControl.Releases#366]
The error message "An unexpected error has occurred and has been added to the log file" pops up. Sometimes it doesn't happen for hours, and sometimes it happens every few seconds. This interferes with me using the computer, as the error message takes focus even when the program is only running in the system tray.

I've been having this issue since v90 and still have it now on v94. I've tried clean installs and updating. I've also tried hiding storage sensors. Note the application itself seems to run fine (apart from missing sensors at login) - gets temperatures and sets fan speeds.

I've also donated but this doesn't seem to have registered in the app.

Here's a log (this is repeated every few seconds):
```
25/10/2021 08:26:34: Unhandled exception in FanControl v1.0.0.0
25/10/2021 08:26:34: System.IO.IOException: GetFeature failed. ---> System.ComponentModel.Win32Exception: The operation completed successfully
   --- End of inner exception stack trace ---
   at HidSharp.Platform.Windows.WinHidStream.GetFeature(Byte[] buffer, Int32 offset, Int32 count)
   at LibreHardwareMonitor.Hardware.Controller.AquaComputer.MPS.Update()
   at FanControl.Domain.UpdateVisitor.VisitHardware(IHardware hardware)
   at LibreHardwareMonitor.Hardware.Computer.Traverse(IVisitor visitor)
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
25/10/2021 08:26:34: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
```

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/140417938-bc48a322-bc1c-43b8-bebb-fb6e61df8fbe.png)

Coming soon.

**Comment by Mushin** [comment]
Thanks - would this change still allow me to access the sensor via the HWInfo plugin?

**Comment by Rem0o** [comment]
Of course.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V96
