### ISSUE TITLE
Update from v91 to latest app is crashed

### ISSUE THREAD

**Issue by pagratios** [Rem0o/FanControl.Releases#398]
After updating from V91 and I am trying to open the app's UI then it is crashed
If I delete userConfig.json then it worked fine

**Logs**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/7574961/log.txt)
: 

**Event Viewer:**
Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(System.Windows.DependencyProperty)
   at System.Windows.Controls.Primitives.ButtonBase.get_Command()
   at System.Windows.Controls.Primitives.ButtonBase.UpdateCanExecute()
   at FanControl.Domain.Logger.Log(System.String, Boolean)
   at FanControl.App.LogUnhandledException(FanControl.Domain.ILogger, FanControl.Domain.IDialogService, System.Exception, System.String)
   at FanControl.App.<SetupExceptionHandling>b__12_2(System.Object, System.Threading.Tasks.UnobservedTaskExceptionEventArgs)
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(System.Object, System.Threading.Tasks.UnobservedTaskExceptionEventArgs)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()

Faulting application name: FanControl.exe, version: 1.0.0.0, time stamp: 0xa5d45b0a
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1348, time stamp: 0x76fcd692
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x627c
Faulting application start time: 0x01d7de35b4eb0da1
Faulting application path: G:\Users\pagratios\Desktop\HW Tools\FanControl\FanControl.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: a5f87713-9deb-43f2-9d54-5a401e130afd
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Rem0o** [comment]
Can you send your config json file? Seems like you got an unexpected value in a graph curve.

**Comment by pagratios** [comment]
Let me know if you need any other info
[userConfig.zip](https://github.com/Rem0o/FanControl.Releases/files/7628650/userConfig.zip)

**Comment by Rem0o** [comment]
How did you get those 0 deg C values in your graph?

I can't seem to find a way to input these from the software, since it floors at 20.

![image](https://user-images.githubusercontent.com/14118956/144124129-8ceb432d-bfd5-4334-8a80-e92d1a1508da.png)

Simply remove these entries in the file and it will work.

**Comment by pagratios** [comment]
Because it wasn't so simple to configure it from the UI I edited the .json

**Comment by pagratios** [comment]
I updated the values to start from 20 instead of 0 and I updated to the latest version without any issue

Although you might need to consider that case and handle all values <20 as 20
