### ISSUE TITLE
Error message when closing the app [Windows 11 Pro]

### ISSUE THREAD

**Issue by Merchal** [Rem0o/FanControl.Releases#457]
I am getting "An unexpected error has occurred and has been added to the log file" when I try to close the app. The error occurs every time.

I am on Win 11 Pro.
The PC is a new build that is running with an old NVIDIA 750 ti windforce while I wait for the new one if that helps.

Here is the error report

```

07/01/2022 02:22:44: Unhandled exception in FanControl v1.0.0.0
07/01/2022 02:22:44: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
07/01/2022 02:22:48: Unhandled exception in FanControl v1.0.0.0
07/01/2022 02:22:48: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
07/01/2022 02:23:17: Unhandled exception in FanControl v1.0.0.0
07/01/2022 02:23:17: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
07/01/2022 02:23:25: Unhandled exception in FanControl v1.0.0.0
07/01/2022 02:23:25: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at FanControl.MVVM.AsyncCommand.<Execute>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
07/01/2022 02:23:30: Unhandled exception in FanControl v1.0.0.0
07/01/2022 02:23:30: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
07/01/2022 02:23:44: Unhandled exception in FanControl v1.0.0.0
07/01/2022 02:23:44: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
07/01/2022 02:48:43: Unhandled exception in FanControl v1.0.0.0
07/01/2022 02:48:43: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
07/01/2022 03:19:38: Unhandled exception in FanControl v1.0.0.0
07/01/2022 03:19:38: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
07/01/2022 03:20:43: Unhandled exception in FanControl v1.0.0.0
07/01/2022 03:20:43: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
```

**
Motherboard

SMBios Version: 3.4

BIOS Vendor: American Megatrends International, LLC.
BIOS Version: 1.10
BIOS Date: 17/12/2021
BIOS Size: 32 MB

System Manufacturer: Micro-Star International Co., Ltd.
System Name: MS-7D32
System Version: 1.0
System Wakeup: PowerSwitch

Motherboard Manufacturer: Micro-Star International Co., Ltd.
Motherboard Name: MAG Z690 TOMAHAWK WIFI DDR4 (MS-7D32)
Motherboard Version: 1.0
Motherboard Serial: 07D3211_LA1E455886

Chassis Type: Desktop
Chassis Manufacturer: Micro-Star International Co., Ltd.
Chassis Version: 1.0
Chassis Serial: Default string
Chassis Asset Tag: Default string
Chassis SKU: Default string
Chassis Boot Up State: Safe
Chassis Power Supply State: Safe
Chassis Thermal State: Safe
Chassis Power Cords: 1
Chassis Lock Detected: No
Chassis Security Status: None

Processor Manufacturer: Intel(R) Corporation
Processor Type: CentralProcessor
Processor Version: 12th Gen Intel(R) Core(TM) i5-12600K
Processor Serial: To Be Filled By O.E.M.
Processor Socket Destignation: U3E1
Processor Socket: Other
Processor Version: 12th Gen Intel(R) Core(TM) i5-12600K
Processor Family: IntelCoreI5
Processor Core Count: 10
Processor Core Enabled: 10
Processor Thread Count: 16
Processor External Clock: 100 Mhz
Processor Max Speed: 8500 Mhz
Processor Current Speed: 3663 Mhz

Cache [L1] Size: 288
Cache [L1] Associativity: 12Way

Cache [L1] Size: 192
Cache [L1] Associativity: 8Way

Cache [L2] Size: 7680
Cache [L2] Associativity: Other

Cache [L3] Size: 20480
Cache [L3] Associativity: Other

Cache [L1] Size: 128
Cache [L1] Associativity: 8Way

Cache [L1] Size: 256
Cache [L1] Associativity: 8Way

Cache [L2] Size: 2048
Cache [L2] Associativity: 16Way

Cache [L3] Size: 20480
Cache [L3] Associativity: Other

Memory Device [0] Manufacturer: 
Memory Device [0] Part Number: 
Memory Device [0] Device Locator: Controller0-DIMMA1
Memory Device [0] Bank Locator: BANK 0
Memory Device [0] Speed: 0
Memory Device [0] Size: 0 MB

Memory Device [1] Manufacturer: Corsair
Memory Device [1] Part Number: CMT32GX4M2C3200C16
Memory Device [1] Device Locator: Controller0-DIMMA2
Memory Device [1] Bank Locator: BANK 0
Memory Device [1] Speed: 3200
Memory Device [1] Size: 16384 MB

Memory Device [2] Manufacturer: 
Memory Device [2] Part Number: 
Memory Device [2] Device Locator: Controller1-DIMMB1
Memory Device [2] Bank Locator: BANK 0
Memory Device [2] Speed: 0
Memory Device [2] Size: 0 MB

Memory Device [3] Manufacturer: Corsair
Memory Device [3] Part Number: CMT32GX4M2C3200C16
Memory Device [3] Device Locator: Controller1-DIMMB2
Memory Device [3] Bank Locator: BANK 0
Memory Device [3] Speed: 3200
Memory Device [3] Size: 16384 MB

Intel CPU

Name: 12th Gen Intel Core i5-12600K
Number of Cores: 10
Threads per Core: 2
Timer Frequency: 10 MHz
Time Stamp Counter: None
Estimated Time Stamp Counter Frequency: 3686.41 MHz
Estimated Time Stamp Counter Frequency Error: 0 Mhz
Time Stamp Counter Frequency: 3686.41 MHz

MSR Core #1

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  000026E7  00002F00
 0000019C  00000000  883D8000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #2

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  000026E7  00002F00
 0000019C  00000000  884A8000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #3

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  000026E7  00002F00
 0000019C  00000000  88468000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #4

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  000026E7  00002F00
 0000019C  00000000  88498000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #5

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  000026E7  00002F00
 0000019C  00000000  88498000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #6

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  000026E7  00002F00
 0000019C  00000000  88478000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #7

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  00002710  00002200
 0000019C  00000000  884A8000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #8

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  00002880  00002400
 0000019C  00000000  884A8000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #9

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  00002710  00002200
 0000019C  00000000  884A8000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD966C5
 00000641  00000000  002694AF

MSR Core #10

 MSR       EDX       EAX
 000000CE  08040838  F1812500
 00000198  00002880  00002400
 0000019C  00000000  884A8000
 000001A2  00000000  80641400
 000001B1  00000000  883D0000
 00000606  00000000  000A0E03
 00000611  00000000  23B55A76
 00000619  00000000  00000000
 00000639  00000000  1CD9695F
 00000641  00000000  002694AF

MicroArchitecture: AlderLake
Time Stamp Counter Multiplier: 37

Storage

Drive Name: CT1000MX500SSD1
Firmware Version: M3CR033

 Id Description                        Raw Value    Worst Value ThresholdPhysical
 01 Read Error Rate                    000000000000 100   100   0     0       
 05 Reallocated NAND Block Count       000000000000 100   100   10    0       
 09 Power-On Hours (POH)               B20900000000 100   100   0     2482    
 0C Power Cycle Count                  780400000000 100   100   0     1144    
 AB Program Fail Count                 000000000000 100   100   0     0       
 AC Erase Fail Count                   000000000000 100   100   0     0       
 AD Wear Leveling Count                0E0000000000 100   100   0     14      
 AE Unexpected Power Loss Count        0E0000000000 100   100   0     14      
 B4 Unused Reserve NAND Blocks         1F0000000000 0     0     0     31      
 B7 SATA Downshift Error Count         000000000000 100   100   0     0       
 B8 Error Correction Count             000000000000 100   100   0     0       
 BB Reported Uncorrectable Errors      000000000000 100   100   0     0       
 C2 Temperature                        200000003500 47    68    0     32      
 C4 Reallocation Event Count           000000000000 100   100   0     0       
 C5 Current Pending Sector Count       000000000000 100   100   0     -       
 C6 Off-Line Uncorrectable Error Count 000000000000 100   100   0     0       
 C7 UltraDMA CRC Error Count           000000000000 100   100   0     0       
 CA Remaining Life                     000000000000 100   100   1     100     
 CE Write Error Rate                   000000000000 100   100   0     0       
 D2 Successful RAIN Recovery Count     000000000000 100   100   0     0       
 F6 Total LBAs Written                 7AB7FB100100 100   100   0     2183.866
 F7 Host Program NAND Pages Count      476A39020000 100   100   0     3.731719E+07
 F8 FTL Program NAND Pages Count       4F36600B0000 100   100   0     1.908547E+08

Logical Drive Name: D:\
Format: NTFS
Total Size: 1000186310656
Total Free Space: 996760940544

Storage

Drive Name: WDS500G1X0E-00AFY0
Firmware Version: 614900WD

PCI Vendor ID: 0x15b7
IEEE OUI Identifier: 0x001b44
Total NVM Capacity: 500107862016
Unallocated NVM Capacity: 0
Controller ID: 8224
Number of Namespaces: 1
Critical Warning: -
Temperature: 40 Celsius
Available Spare: 100%
Available Spare Threshold: 10%
Percentage Used: 0%
Data Units Read: 255319
Data Units Written: 303196
Host Read Commands: 3492597
Host Write Commands: 3643833
Controller Busy Time: 4
Power Cycles: 31
Power On Hours: 13
Unsafe Shutdowns: 11
Media Errors: 0
Number of Error Information Log Entries: 0
Warning Composite Temperature Time: 0
Critical Composite Temperature Time: 0
Logical Drive Name: C:\
Format: NTFS
Total Size: 499343421440
Total Free Space: 398047805440

Storage

Drive Name: CT1000P5PSSD8
Firmware Version: P7CR402

PCI Vendor ID: 0xc0a9
IEEE OUI Identifier: 0x00a075
Total NVM Capacity: 1000204886016
Unallocated NVM Capacity: 0
Controller ID: 0
Number of Namespaces: 1
Critical Warning: -
Temperature: 35 Celsius
Available Spare: 100%
Available Spare Threshold: 5%
Percentage Used: 0%
Data Units Read: 494902
Data Units Written: 615828
Host Read Commands: 1489877
Host Write Commands: 1350185
Controller Busy Time: 2
Power Cycles: 29
Power On Hours: 5
Unsafe Shutdowns: 12
Media Errors: 0
Number of Error Information Log Entries: 34
Warning Composite Temperature Time: 0
Critical Composite Temperature Time: 0
Temperature Sensor 1: 35 Celsius
Logical Drive Name: E:\
Format: NTFS
Total Size: 1000186310656
Total Free Space: 800350969856
**

**Comment by Rem0o** [comment]
Try and save a config immediately when you open the app. I think I found the issue, will fix.

**Comment by Merchal** [comment]
Sorry I do not follow you. Do you need me to send you generate some report and send it to you?

Thanks
