### ISSUE TITLE
Exception when replacing single digit in any NumericUpDown control

### ISSUE THREAD

**Issue by kccricket** [Rem0o/FanControl.Releases#458]
FanControl v100 throws an exception if you attempt to highlight and replace any single digit in any NumericUpDown control in the main window.

Steps to reproduce:

1. Open the left drawer in the main FanControl window.
2. Enable the "Start with Windows" check box.
3. Highlight one of the digits in the "Delay" input control.
4. Press a number greater than zero on your keyboard.

Receive exception:

```
1/7/2022 7:59:14 AM: Unhandled exception in FanControl v1.0.0.0
1/7/2022 7:59:14 AM: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FanControl.Views.Controls.NumericUpDown.GetText(TextCompositionEventArgs e, TextBox textBox)
   at FanControl.Views.Controls.NumericUpDown.GetTextAndPad(TextCompositionEventArgs e, TextBox textBox)
   at FanControl.Views.Controls.NumericUpDown.TextBox_PreviewTextInput(Object sender, TextCompositionEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessTextInputAction(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by kccricket** [comment]
Note this is the same exception reported in #447, but different trigger.

**Comment by Rem0o** [comment]
Yep, same issue, will fix.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V101
