### ISSUE TITLE
Error when closing the application

### ISSUE THREAD

**Issue by codingchili** [Rem0o/FanControl.Releases#467]
When attempting to close the application an error message appears "An unexpected error has occurred and has been added to the log file." 

Reproducing

1. Download and unzip FanControl v100.
2. Start the application.
3. Close the application.
4. Error message appears as userConfig.json is missing.

Closing the application works after using 'Save configuration' from the menu.

The following stack trace is in the log file,

```
2022-01-11 12:10:08: Unhandled exception in FanControl v1.0.0.0
2022-01-11 12:10:09: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
2022-01-11 12:10:12: Unhandled exception in FanControl v1.0.0.0
2022-01-11 12:10:12: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
2022-01-11 12:10:15: Unhandled exception in FanControl v1.0.0.0
2022-01-11 12:10:15: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
2022-01-11 12:10:26: Unhandled exception in FanControl v1.0.0.0
2022-01-11 12:51:07: Unhandled exception in FanControl v1.0.0.0
2022-01-11 12:51:07: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at FanControl.Domain.ApplicationContext.ApplicationStateHasChanged(Boolean& isNew)
   at FanControl.ViewModels.MainWindowViewModel.<AskForSaveIfChanged>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<<MainWindow_Closing>b__16_0>d.MoveNext()
```

**Comment by Rem0o** [comment]
Did spot already, will be fixed.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V101
