### ISSUE TITLE
starting after LibreHardwareMonitor 

### ISSUE THREAD

**Issue by kamkie** [Rem0o/FanControl.Releases#520]
when FanControl starts after LibreHardwareMonitor  some sensors and controls are not avalible

**Comment by Rem0o** [comment]
I would expect such issues, since both use the same backend and will conflict where querying.

**Comment by kamkie** [comment]
in LibreHardwareMonitor I can see all of sensors even when it is started after FanControl 

as FanControl has no graphs or monitoring features it is a bit annoing

**Comment by kamkie** [comment]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/471273/155999981-4f094e73-c83c-4b0f-815f-ead2a858c395.png">

**Comment by kamkie** [comment]
other sourcces as temperature or gpu fans are working as expected 
only this one controler from motherboard is problematic

**Comment by kamkie** [comment]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/471273/156000237-1497cea4-15c2-402d-bae4-176ec95d7325.png">

**Comment by kamkie** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/471273/156000689-36acfcfd-a2ad-4771-bc88-63d342688d58.png">
second one has problem then also

**Comment by Rem0o** [comment]
So the problem isn't specific to how FanControl uses the library, it's just a current limitation to run multiple instances.

**Comment by kamkie** [comment]
starting FanControl  and after that LibreHardwareMonitor make it work in both at the same time, so there is more to it

**Comment by Rem0o** [comment]
Any logs.txt to share in your FanControl folder?

**Comment by kamkie** [comment]
only some unrelated exceptions when I was editing graph 
nothing for last ~1.5 days
```
2022-03-02 00:12:23: Unhandled exception in FanControl v1.0.0.0
2022-03-02 00:12:23: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at MS.Utility.FrugalStructList`1.set_Item(Int32 index, T value)
   at System.Windows.Media.PointCollection.set_Item(Int32 index, Point value)
   at FanControl.Views.Graph.<>c__DisplayClass63_0.<SetMovingPoint>g__movePoint|1(Point point)
   at FanControl.Views.Graph.OnMouseMove(MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2022-03-02 00:12:23: Unhandled exception in FanControl v1.0.0.0
```

**Comment by kamkie** [comment]
seams to be working corretly now with v112 and LibreHardwareMonitor 0.9
