### ISSUE TITLE
some sort of out of range error causes UI to stop responding

### ISSUE THREAD

**Issue by acme64** [Rem0o/FanControl.Releases#557]
i'm on v108.
I try to edit one of the fan graph curves and when i click ok i get an error and then the edit buttons to stop responding. All the values still update but I can't edit the curves any more.

small excerpt of the log, i can't post the whole thing:
```
3/29/2022 6:06:30 PM: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at MS.Utility.FrugalStructList`1.set_Item(Int32 index, T value)
   at System.Windows.Media.PointCollection.set_Item(Int32 index, Point value)
   at FanControl.Views.Graph.<>c__DisplayClass63_0.<SetMovingPoint>g__movePoint|0(Point point)
   at FanControl.Views.Graph.OnMouseMove(MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Epikest** [comment]
i am getting the same thing, edit button does nothing after it happened

**Comment by Rem0o** [comment]
Does it still happen with 109?

**Comment by Geonfr** [comment]
Hey Rem0o, still happening for me on v109. I get the same error in my log as above, a complete restart of the tool fixes the issue until I edit a curve again and after the window is closed the error occurs again.

**Comment by Geonfr** [comment]
It seems only to happen when the curve window is moving a bit while editing the points. So I edit the curve and the left and right side of the curve window is expanding and retracting slightly as I move the point, it looks like it tries to scale it somehow. The point also isn't moving with the cursor but jumps to the endpoint when releasing the left mouse button. I hope that helps somehow

**Comment by sl4ppy** [comment]
I've just resorted to editing the values directly in the JSON file until this is resolved.  Editing any curve throws the error.

**Comment by Rem0o** [comment]
if your temp source is a non-decimal value, does the bug still occur?

**Comment by acme64** [comment]
If i change the temp source to something else and back to tctl/tdie it seems to work

**Comment by Rem0o** [comment]
Yeah, it's the optional decimal point changing the width of the graph dynamically as you edit which breaks it. WIll fix.
