### ISSUE TITLE
Alienware M17 R4 No GUI and NVAPI Error

### ISSUE THREAD

**Issue by Demon6281** [Rem0o/FanControl.Releases#591]
Seems as though it is having trouble both initializing the NVAPI and displaying the program itself. I've tried manually selecting which GPU Windows uses to open the program, and that didn't help. I'm still not used to using a laptop as a main rig, and the dual graphics has royally bunged a few applications, so if unfixable totally understandable.

i9-10980HK
32GB 3000Mhz DDR4
1.5TB NVME(1TBx500GB)
3080 165W

With and without the API Enabled:
4/22/2022 6:54:54 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   at NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
4/22/2022 6:54:54 PM: NVApi could not initialize.

**Comment by techspec6** [comment]
Laptops are not supported.  Found this out when I searched "NVAPI_NOT_SUPPORTED" here and saw a previous post.

**Comment by Rem0o** [comment]
See README.

Sadly, laptops use proprietary stuff which isn't standard.

Closing.
