### ISSUE TITLE
Unable to Load Plugin HWInfo

### ISSUE THREAD

**Issue by MoridinTX** [Rem0o/FanControl.Releases#592]
Installed FanControl in C:\FanControl folder.
Have HWInfo v7.22 running, with the shared memory option enabled.
Have HWInfo plugin files in the plugins folder.

When I check the settings, it does not show any plugin loaded.  Opening the log shows this:

4/22/2022 6:10:03 PM: System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
4/22/2022 6:10:03 PM: Failed to load plugin FanControl.Plugins.dll.
4/22/2022 6:10:03 PM: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\FanControl\Plugins\FanControl.Plugins.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\FanControl\Plugins\FanControl.Plugins.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at FanControl.Domain.PluginService.LoadAssembly(FileInfo dll)

**Comment by xhul-dev** [comment]
Hello there.
Just in case, did you enable the hwinfo in the options?

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/164867989-bacbfe21-f106-41ad-969e-22fd15b339b9.png)

**Comment by ryan-mccullough** [comment]
Had the same issue. Refresh sensor detection from the three dot menu fixed it.

**Comment by MAUtastic** [comment]
Same problem with this Plugin. I did unblock the dll and enabled the hwinfo plugin. What could cause this issue?

**Comment by Nrde** [comment]
Started to get this problem probably after update to v114. hwinfo is running and I think all the necessary options enabled as mentioned in the plugin install instructions.
```
16.5.2022 11.02.53: System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 16
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
16.5.2022 11.02.53: HWInfo plugin could not initialize. See the error log for more details.
```
![image](https://user-images.githubusercontent.com/7312751/168558718-8d8c7111-00b6-4450-bbfd-8d47c6ccd2f3.png)

**Comment by Rem0o** [comment]
Make sure you got the latest version of hwinfo and that it is running in sensor mode.
