### ISSUE TITLE
Fan Control is looking for HWInfo plugin in wrong location

### ISSUE THREAD

**Issue by Huntakillaz** [Rem0o/FanControl.Releases#646]
Updated to FanControl 111

Running as portable (zip extracted) in location D:\Portable - Utilities\FanControl
Plugin location is D:\Portable - Utilities\FanControl\Plugins

but for some reason it's looking for it in "C:\projects\fancontrol-hwinfo"?

Log:

23/04/2022 4:02:58 pm: System.IO.FileNotFoundException: Unable to find the specified file.
   at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
23/04/2022 4:02:58 pm: HWInfo could not initialize.

**Comment by Rem0o** [comment]
Shared memory is not enabled in hwinfo or is not running
