### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by Dracconis** [Rem0o/FanControl.Releases#657]
Apologies ahead of time if this has already been covered. When starting the Assisted setup or using the ellipses "Detect fan start % automatically ..." for the GPU, either of the 2 will start testing and will get to 102% and then throws an error. Afterwards when in the main GUI the GPU will show it's temp but not fan speed. Using HWM it will show the same thing as well. Temp but not Speed. I am guessing that is part of what has already been discussed about no way to monitor currently. However I wanted to provide the error log for you to look at to make sure nothing was missed and that I and possibly others will just have to wait until such control over GPUs can be done.

`
4/24/2022 12:11:43 AM: Unhandled exception in FanControl v1.0.0.0
4/24/2022 12:11:43 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_INVALID_ARGUMENT
   at FanControl.Models.NVApiControlSensor.HandleException(NVIDIAApiException exception)
   at FanControl.Models.NVApiControlSensor.Set(Single val)
   at FanControl.ViewModels.Utilities.FanStartUtility.<Run>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtility`1.<Run>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtilityExtensions.<>c__DisplayClass0_0`1.<<HoldStateAndRunInProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass8_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
4/24/2022 9:39:11 AM: Unhandled exception in FanControl v1.0.0.0
4/24/2022 9:39:11 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_INVALID_ARGUMENT
   at FanControl.Models.NVApiControlSensor.HandleException(NVIDIAApiException exception)
   at FanControl.Models.NVApiControlSensor.Set(Single val)
   at FanControl.ViewModels.Utilities.FanStartUtility.<Run>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtility`1.<Run>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtilityExtensions.<>c__DisplayClass0_0`1.<<HoldStateAndRunInProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass8_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
4/24/2022 9:45:02 AM: Unhandled exception in FanControl v1.0.0.0
4/24/2022 9:45:02 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_INVALID_ARGUMENT
   at FanControl.Models.NVApiControlSensor.HandleException(NVIDIAApiException exception)
   at FanControl.Models.NVApiControlSensor.Set(Single val)
   at FanControl.ViewModels.Utilities.FanStartUtility.<Run>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtility`1.<Run>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.AssistedSetup.<FanStartUtility>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.AssistedSetup.<RunAutomaticTests>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass8_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
4/24/2022 10:08:24 AM: Unhandled exception in FanControl v1.0.0.0
4/24/2022 10:08:24 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_INVALID_ARGUMENT
   at FanControl.Models.NVApiControlSensor.HandleException(NVIDIAApiException exception)
   at FanControl.Models.NVApiControlSensor.Set(Single val)
   at FanControl.ViewModels.Utilities.FanStartUtility.<Run>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtility`1.<Run>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.ViewModels.Utilities.FanTaskUtilityExtensions.<>c__DisplayClass0_0`1.<<HoldStateAndRunInProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass8_0`1.<<ProgressDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8549992/log.txt)

**Comment by Rem0o** [comment]
That 102% thing is a bug. Will clamp the value.

**Comment by Dracconis** [comment]
Appreciate it. Anything in the error log to help out or is it aforementioned issue with major manufacts not providing code to work with?

**Comment by Rem0o** [comment]
The 102% bug is already fixed, will push it in the next version.

**Comment by Dracconis** [comment]
Cool. I guess what I was asking and meaning was the error log I posted give any clue as to maybe also why GPUs like the NVidia 1050 Ti not having fan speeds being reported by your SW or is that because of needing code that is unavailable currently?

**Comment by Rem0o** [comment]
The error log only showed than an API call was given a wrong argument, aka 102% (NVAPI_INVALID_ARGUMENT).

**Comment by Dracconis** [comment]
Oh ok. Well still thank you for all your hard work and effort in putting this great software together for something that even the majors can't be arsed to do.

**Comment by Rem0o** [comment]
See V112

**Comment by Dracconis** [comment]
All good and no errors this time.
