### ISSUE TITLE
Bug: Unhandled exception in FanControl v1.0.0.0 - Causes unresponsive UI

### ISSUE THREAD

**Issue by MattMills** [Rem0o/FanControl.Releases#723]
Hello,

I have a Corsair HX750i power supply that I was trying to get working with Fan Control.

When I enable the PSU sensors and refresh, I get the following 3 stacks in the error log:

```
5/1/2022 2:27:46 AM: LibreHardwareMonitor.Hardware.Psu.Corsair.CommunicationProtocolError: Error communicating with the PSU controller at \\?\hid#vid_1b1c&pid_1c05#8&2ecb87ad&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: Can't read vendor string
   at LibreHardwareMonitor.Hardware.Psu.Corsair.UsbApi.FwInfo(HidStream stream)
   at LibreHardwareMonitor.Hardware.Psu.Corsair.CorsairPsu..ctor(HidDevice device, ISettings settings, Int32 index)
   at LibreHardwareMonitor.Hardware.Psu.Corsair.CorsairPsuGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
5/1/2022 2:27:46 AM: LibreHardwareMonitor could not initialize.
5/1/2022 2:27:46 AM: Unhandled exception in FanControl v1.0.0.0
5/1/2022 2:27:46 AM: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.ViewModels.MainWindowViewModel.<ShowError>d__135.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.ViewModels.MainWindowViewModel.<ShowError>d__135.MoveNext()<---

5/1/2022 2:27:46 AM: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   at FanControl.ViewModels.MainWindowViewModel.<ShowError>d__135.MoveNext()
5/1/2022 2:27:46 AM: Unhandled exception in FanControl v1.0.0.0
5/1/2022 2:27:46 AM: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: DialogHost is already open.
   at MaterialDesignThemes.Wpf.DialogHost.<ShowInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaterialDesignThemes.Wpf.DialogHost.<Show>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass5_0`1.<<ShowDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<ShowDialog>d__5`1.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: DialogHost is already open.
   at MaterialDesignThemes.Wpf.DialogHost.<ShowInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaterialDesignThemes.Wpf.DialogHost.<Show>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass5_0`1.<<ShowDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<ShowDialog>d__5`1.MoveNext()<---

5/1/2022 2:27:46 AM: System.InvalidOperationException: DialogHost is already open.
   at MaterialDesignThemes.Wpf.DialogHost.<ShowInternal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaterialDesignThemes.Wpf.DialogHost.<Show>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<>c__DisplayClass5_0`1.<<ShowDialog>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.ApplicationContext.<InvokeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<ShowDialog>d__5`1.MoveNext()
```

It also seems to fail to refresh most of the sensors, only a single one shows up. The UI is still responsive to clicks, but things like the exit button don't work (click it and nothing happens). 

The UI must be end-task'd and restarted to get it to work again.

I understand the root of the issue is within LibreHardwareMonitor, and I will open a bug there if I can't find one, but I thought I should open one here for the UI issue, as it'd obviously be better to fail gracefully then just stacktrace and shrug violently.

**Comment by Rem0o** [comment]
Agree. Will bullet proof this section a bit more to isolate the problem better and not crash everything around it.
