### ISSUE TITLE
Waking from sleep causes FanControl to "forget" sensors.

### ISSUE THREAD

**Issue by Jonathanese** [Rem0o/FanControl.Releases#736]
First of all it's obligatory that I think the bajeezus out of you for making this software. Hopefully you either have the time or the extra hands to tackle the influx of issue submissions post-Jay. Might fork it to try to create some features of my own and present them for consideration in the main branch.

I have my PC set to turn off the screen after about 30min. I'll have to check the sleep settings and update this post.

But I notice when it goes into one of these states, the fans spin up. I don't mind that because I would rather the software freeze in a cooling state, and a "speed on sleep/close" might be a useful feature. But when I log back in to the computer, FanControl basically comes up with a configuration failure that requires either a refresh, a restart of the program, or a full reboot.

I am using the Corsair Commander Pro plugin, so I'll do some additional testing to see if it originates from the plugin.

Relevant specs:
Windows 11
Corsair Commander Pro
Corsair H115i
Z370 Extreme 4
All other fan and RGB software completely removed.

Steps to reproduce:
- FanControl installed
- Corsair Commander Pro plugin installed
- About 6 graph curves and 3 mix curves
- PC idles long enough for screen to enter sleep

Hypotheses:
- BIOS settings may cut off many peripherals in sleep. May need to check if USB ports disable on sleep for Commander Pro
- Might also benefit from a hardware rescan on wake.

**Comment by Rem0o** [comment]
Are the missing sensors only the commander pro ones? Any log.txt also?

**Comment by knaackville** [comment]
Having the same issue with waking from sleep, but without the Commander Pro plugin.  Seems like it wasn't having this issue a few releases ago, but I did add some fans in the interim as well.  Program also won't exit when right clicking on systray icon and choosing exit.

MB: MSI Z690 Unify-X


Error log below:

5/11/2022 8:33:07 PM: Unhandled exception in FanControl v1.0.0.0
5/11/2022 8:33:07 PM: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: No loaded DialogHost instances.
   at MaterialDesignThemes.Wpf.DialogHost.GetInstance(Object dialogIdentifier)
   at FanControl.Domain.DialogService.<Queue>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<ShowDialog>d__6`1.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: No loaded DialogHost instances.
   at MaterialDesignThemes.Wpf.DialogHost.GetInstance(Object dialogIdentifier)
   at FanControl.Domain.DialogService.<Queue>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<ShowDialog>d__6`1.MoveNext()<---

5/11/2022 8:33:07 PM: System.InvalidOperationException: No loaded DialogHost instances.
   at MaterialDesignThemes.Wpf.DialogHost.GetInstance(Object dialogIdentifier)
   at FanControl.Domain.DialogService.<Queue>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.Domain.DialogService.<ShowDialog>d__6`1.MoveNext()

**Comment by mooseweener** [comment]
After sleep close FanControl, open HWMonitor and close, open FanControl and it will work.
