### ISSUE TITLE
Loading configuration from file without saving current gives NullReferenceException

### ISSUE THREAD

**Issue by ebaldebo** [Rem0o/FanControl.Releases#75]
Dont think this was present in v56

Repro steps:
1. Downloaded new release(57) from Github and start it
2. Click load configuration
3. Press No in the popup asking if you want to save current configuration(It pops up even though there are no changes made)
4. Click Load in the next popup asking you to select config file

Output from log.txt:
`
2020-11-18 09:57:32: Unhandled exception in FanControl v1.0.0.0
2020-11-18 09:57:32: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.MVVM.AsyncCommand.a.d()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2020-11-18 09:57:57: Unhandled exception in FanControl v1.0.0.0
2020-11-18 09:57:57: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.MVVM.AsyncCommand.a.d()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by Rem0o** [comment]
Well did you select a file in step 4) ?

**Comment by ebaldebo** [comment]
There was no file to select at all in the list.

The workaround was just to save the current userConfig.json and then load the other config I made. So I can still use the application with my 5800X(Thanks a lot for updating so quickly btw!).

Either way, shouldn't there be a null check/disabled button in place to catch this if a config file is not selected?

**Comment by Rem0o** [comment]
Yeah missing a null check there clearly, but why are you trying to "load" nothing basically?

**Comment by ebaldebo** [comment]
I have a custom config file in the folder made in an earlier version.
However it does not show up if I chose "No" when prompted to save changes even though I haven't made any changes and try to load it.

Like I said, I can workaround it by just clicking "Yes" in the unsaved changes prompt and then it shows up in the list.

**Comment by Rem0o** [comment]
The "Load" button will be blank if no file is selected in the future version.

**Comment by Rem0o** [comment]
Fixed in V58.
