### ISSUE TITLE
Aqua Cpomputer D5 Next Sensor Detection Issue

### ISSUE THREAD

**Issue by Dilvanon** [Rem0o/FanControl.Releases#843]
I am using HWiNFO to import the D5's water temperature sensor data to control my fan curves. On start-up, FanControl recognizes the sensor with the temperature value. A few seconds later, the sensor is still detected but it does not pick up the temperature anymore (it shows 0 °C). This results in the fans spinning up like crazy - I have to manually refresh the sensor detection so that the temperature value is picked up correctly again.

Setting a higher start-up delay does not help and the error log does not have any entries about this.
Is there a possibility to have the sensors automatically refresh on start to circumvent this issue?

**Comment by Dilvanon** [comment]
Thanks for the quick response. Now sadly the plugin does not work at all anymore. (I set up all the steps in HWiNFO as said). Sorry if I made some rookie mistakes - I have no experience in this field.
The error log now gives me these errors:

31.05.2022 17:11:27: Failed to load plugin FanControl.HWInfo.dll.
31.05.2022 17:11:27: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files\FanControl\Plugins\FanControl.HWInfo.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Program Files\FanControl\Plugins\FanControl.HWInfo.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at FanControl.Domain.PluginService.LoadAssembly(FileInfo dll)

31.05.2022 17:11:27: System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

**Comment by Dilvanon** [comment]
Thank you so much - now everything runs smoothly.
Will definitely donate now - great programm and great support! :)
