### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by ycodryn** [Rem0o/FanControl.Releases#888]
I`m using latest Fan Control, HWinFO64 and hwinfo plugin 1.0.35.

22/06/2022 18:00:56: Unhandled exception in FanControl v1.0.0.0
22/06/2022 18:00:56: System.Exception: HWInfo sensors were changed during operation
   at FanControl.HWInfo.HWInfoPlugin.Update() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 69
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Rem0o** [comment]
"HWInfo sensors were changed during operation"

Did you do something with HWInfo while FanControl was running? That messages indicates that one sensor through the gadget interface went missing.

**Comment by ycodryn** [comment]
No, HWInfo is running in background. Every time after I`m clicking fan control to open it from tray I got that message.

**Comment by ycodryn** [comment]
After latest updates to fan and plugin, I got the same error.

**Comment by Rem0o** [comment]
@ycodryn  If I were you, I would untick every sensor from the gadget tab and only check those you need, see if that helps.

**Comment by ycodryn** [comment]
@Rem0o already did that, as I need only one sensor, pump+ speed.

**Comment by daverdfw** [comment]
I am having the same issue, running HWinfo 7.26-4800

**Comment by ArbiterGR** [comment]
Same issue here as well with HWINFO plugin. Only reporting sensors for aio liquid temp/fan speeds/pump speed. HW Info is running in the background and continues to report normally after the error occurs. Another issue here, is that as soon as the error pops up in fancontrol, the plugin stops reporting untill i restart the app.

15/8/2022 1:17:43 μμ: Unhandled exception in FanControl v1.0.0.0
15/8/2022 1:17:43 μμ: System.Exception: HWInfo sensors were changed during operation
   at FanControl.HWInfo.HWInfoPlugin.Update() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 68
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Rem0o** [comment]
Please report this in the HWInfo plugin repo. If someone could debug this with source code and tell what's happening with the missing sensor, that would help.

**Comment by Rem0o** [comment]
Should be fixed with https://github.com/Rem0o/FanControl.HWInfo/releases/tag/1.2

**Comment by ycodryn** [comment]
Thank you, I will test it.
