### ISSUE TITLE
Fan Control initialization failed. See log.txt for details.

### ISSUE THREAD

**Issue by VForest** [Rem0o/FanControl.Releases#972]
I've had this error for while now, but wasn't paying much attention to it. Decided it might be worth checking that out. Happens on startup. Windows 11 KB5015732.

![image](https://user-images.githubusercontent.com/79280741/180648945-adef024d-0898-403e-b268-f089364b40e8.png)

Logs:

2022-07-24 9:18:27 AM: System.Management.ManagementException: Timed out 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
2022-07-24 9:18:27 AM: LibreHardwareMonitor could not initialize or has no sensors. See the error log for more details.
2022-07-24 9:18:27 AM: Could not initialize.

**Comment by Rem0o** [comment]
Seems like the WMI request to get storage info is timing out. If you don't need storage stuff, I would untick it in the sensor settings.

**Comment by VForest** [comment]
Looks like it fixed it, I don't believe I use storage stuff anyways. Thanks for the fast reply, keep up the good work !
